/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:36:38 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/91AA76A0-F2FF-4AAA-BCD2-7E5978B32B63/Skype.app/Skype
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Skype/SKPViewController.h>

@class SKPActivityToken, UIViewController;

@interface SKPModalViewController : SKPViewController {

	SKPActivityToken* _modalActivity;
	UIViewController* _containedController;

}

@property (nonatomic,retain) SKPActivityToken * modalActivity;                    //@synthesize modalActivity=_modalActivity - In the implementation block
@property (nonatomic,retain) UIViewController * containedController;              //@synthesize containedController=_containedController - In the implementation block
-(SKPActivityToken *)modalActivity;
-(void)setModalActivity:(SKPActivityToken *)arg1 ;
-(UIViewController *)containedController;
-(void)setContainedController:(UIViewController *)arg1 ;
-(id)initWithChildController:(id)arg1 ;
-(void)dealloc;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(BOOL)accessibilityPerformEscape;
@end

