/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:36:39 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/91AA76A0-F2FF-4AAA-BCD2-7E5978B32B63/Skype.app/Skype
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Skype/SKPLazyPropertyContainer.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <Skype/SKPUniquing.h>

@class NSDate, NSString, SKPConversation;

@interface SKPSearchHistoryItem : SKPLazyPropertyContainer <NSCoding, SKPUniquing> {

	unsigned long long _objectId;
	NSDate* _timestamp;
	NSString* _conversationIdentity;
	SKPConversation* _conversation;

}

@property (nonatomic,retain) SKPConversation * conversation;               //@synthesize conversation=_conversation - In the implementation block
@property (nonatomic,retain) NSString * conversationIdentity;              //@synthesize conversationIdentity=_conversationIdentity - In the implementation block
@property (nonatomic,retain) NSDate * timestamp;                           //@synthesize timestamp=_timestamp - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) unsigned long long objectId;                  //@synthesize objectId=_objectId - In the implementation block
+(id)lazyLoadedPropertiesKeypaths;
-(NSString *)conversationIdentity;
-(void)setConversationIdentity:(NSString *)arg1 ;
-(id)fetchOperationForLazyProperty:(id)arg1 fetchQueueIdentifier:(id*)arg2 ;
-(BOOL)flushLazyProperty:(id)arg1 ;
-(id)initWithTimestamp:(id)arg1 conversationObjectId:(unsigned long long)arg2 conversationIdentity:(id)arg3 ;
-(id)fetchConversationOperation;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)debugDescription;
-(NSDate *)timestamp;
-(void)setTimestamp:(NSDate *)arg1 ;
-(SKPConversation *)conversation;
-(void)setConversation:(SKPConversation *)arg1 ;
-(unsigned long long)objectId;
-(void)setObjectId:(unsigned long long)arg1 ;
@end

