/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 12:01:47 AM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/3822BE3B-29D4-4DEB-BFFF-FDA22D01C707/AngryBirdsClassic.app/AngryBirdsClassic
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class BITPLCrashReportSymbolInfo;

@interface BITPLCrashReportStackFrameInfo : NSObject {

	unsigned long long _instructionPointer;
	BITPLCrashReportSymbolInfo* _symbolInfo;

}

@property (nonatomic,readonly) unsigned long long instructionPointer;                //@synthesize instructionPointer=_instructionPointer - In the implementation block
@property (nonatomic,readonly) BITPLCrashReportSymbolInfo * symbolInfo;              //@synthesize symbolInfo=_symbolInfo - In the implementation block
-(id)initWithInstructionPointer:(unsigned long long)arg1 symbolInfo:(id)arg2 ;
-(unsigned long long)instructionPointer;
-(BITPLCrashReportSymbolInfo *)symbolInfo;
-(void)dealloc;
@end

