/*
* This header is generated by classdump-dyld 0.7
* on Thursday, November 19, 2015 at 5:05:16 PM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/BE5DA1E5-E5C1-4952-A4BE-28BA22319130/Gumtree.app/Gumtree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Gumtree/Gumtree-Structs.h>
#import <Gumtree/ECIpadBaseAnimatedFlowLayout.h>

@class NSMutableDictionary;

@interface ECIpadSearchResultsFlowLayout : ECIpadBaseAnimatedFlowLayout {

	int _markerStopPoint;
	NSMutableDictionary* _attributesCache;

}

@property (assign,nonatomic) int markerStopPoint;                                //@synthesize markerStopPoint=_markerStopPoint - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * attributesCache;              //@synthesize attributesCache=_attributesCache - In the implementation block
-(void)setMarkerStopPoint:(int)arg1 ;
-(void)setAttributesCache:(NSMutableDictionary *)arg1 ;
-(id)createMarkerAttributesWithSortedCells:(id)arg1 ;
-(id)createSectionTitleAttributesWithSortedCells:(id)arg1 ;
-(BOOL)shouldDisplayTimelineMarkerForIndexPath:(id)arg1 ;
-(id)createMarkerAttributeForCell:(id)arg1 andIndex:(id)arg2 ;
-(void)fixFramesForCustomMarkerFloatingBehavior:(id)arg1 andCells:(id)arg2 ;
-(id)getMarkerForFirstCellInColumnBeforeIndexPath:(id)arg1 ;
-(int)markerStopPoint;
-(id)createSectionTitleAttribute:(CGRect)arg1 andIndexPath:(id)arg2 ;
-(NSMutableDictionary *)attributesCache;
-(id)init;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(void)prepareLayout;
-(BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(void)prepareForAnimatedBoundsChange:(CGRect)arg1 ;
@end

