/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:41:46 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/91D74E3C-0E85-4CEF-8E44-3072C9AFF7E4/AlienBlue.app/AlienBlue
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface EDAMTypesConstants : NSObject
+(id)CLASSIFICATION_RECIPE_USER_NON_RECIPE;
+(id)CLASSIFICATION_RECIPE_USER_RECIPE;
+(id)CLASSIFICATION_RECIPE_SERVICE_RECIPE;
+(id)EDAM_NOTE_SOURCE_WEB_CLIP;
+(id)EDAM_NOTE_SOURCE_MAIL_CLIP;
+(id)EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
+(void)initialize;
@end

