/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 10:10:01 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/4C83B32D-E9D7-434B-B0B8-8A6C2C13527D/SportyTrader.app/SportyTrader
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FlurryPLCrashReportRegisterInfo : NSObject {

	NSString* _registerName;
	unsigned long long _registerValue;

}

@property (nonatomic,readonly) NSString * registerName;                       //@synthesize registerName=_registerName - In the implementation block
@property (nonatomic,readonly) unsigned long long registerValue;              //@synthesize registerValue=_registerValue - In the implementation block
-(id)initWithRegisterName:(id)arg1 registerValue:(unsigned long long)arg2 ;
-(NSString *)registerName;
-(unsigned long long)registerValue;
-(void)dealloc;
@end

