/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 10:10:01 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/4C83B32D-E9D7-434B-B0B8-8A6C2C13527D/SportyTrader.app/SportyTrader
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>
#import <SportyTrader/FlurryTumblrPostPhotoDialogControllerDelegate.h>
#import <SportyTrader/FlurryTumblrPostTextDialogControllerDelegate.h>

@protocol FlurryTumblrPostNavControllerDelegate;
@class FlurryTumblrBasePostDialogController, UIImageView, NSString;

@interface FlurryTumblrPostNavController : UINavigationController <FlurryTumblrPostPhotoDialogControllerDelegate, FlurryTumblrPostTextDialogControllerDelegate> {

	int _postType;
	id<FlurryTumblrPostNavControllerDelegate> _postsDelegate;
	FlurryTumblrBasePostDialogController* _dialogController;
	UIImageView* _tumblrLogo;

}

@property (assign,nonatomic,__weak) id<FlurryTumblrPostNavControllerDelegate> postsDelegate;              //@synthesize postsDelegate=_postsDelegate - In the implementation block
@property (assign,nonatomic) int postType;                                                                //@synthesize postType=_postType - In the implementation block
@property (nonatomic,retain) FlurryTumblrBasePostDialogController * dialogController;                     //@synthesize dialogController=_dialogController - In the implementation block
@property (nonatomic,retain) UIImageView * tumblrLogo;                                                    //@synthesize tumblrLogo=_tumblrLogo - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTextTitle:(id)arg1 body:(id)arg2 blogName:(id)arg3 ;
-(void)setDialogController:(FlurryTumblrBasePostDialogController *)arg1 ;
-(FlurryTumblrBasePostDialogController *)dialogController;
-(void)setTextViewDimensions;
-(void)setPostType:(int)arg1 ;
-(id)initWithImagePath:(id)arg1 imageCaption:(id)arg2 blogName:(id)arg3 ;
-(void)setImageViewDimensions;
-(void)setTumblrLogo:(UIImageView *)arg1 ;
-(UIImageView *)tumblrLogo;
-(int)postType;
-(void)setupNavigationBar;
-(void)setupTumblrLogo;
-(void)setViewDimensions;
-(id<FlurryTumblrPostNavControllerDelegate>)postsDelegate;
-(void)pressedCancel;
-(void)pressedPostImage:(id)arg1 withCaption:(id)arg2 andBlogName:(id)arg3 tags:(id)arg4 ;
-(void)pressedPostText:(id)arg1 withBody:(id)arg2 andBlogName:(id)arg3 tags:(id)arg4 ;
-(void)setPostsDelegate:(id<FlurryTumblrPostNavControllerDelegate>)arg1 ;
-(void)viewDidLoad;
@end

