/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:47:04 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/342EE397-EC3B-4D13-968C-80EF1D13592D/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WAFieldStatsEvent.h>

@interface WAFieldStatsEventChatConnection : WAFieldStatsEvent {

	double _chat_state;
	double _chat_socket_connect_t;
	double _chat_login_t;
	double _chat_post_login_t;
	double _chat_connected_t;

}

@property (assign,nonatomic) double chat_state;                         //@synthesize chat_state=_chat_state - In the implementation block
@property (assign,nonatomic) double chat_socket_connect_t;              //@synthesize chat_socket_connect_t=_chat_socket_connect_t - In the implementation block
@property (assign,nonatomic) double chat_login_t;                       //@synthesize chat_login_t=_chat_login_t - In the implementation block
@property (assign,nonatomic) double chat_post_login_t;                  //@synthesize chat_post_login_t=_chat_post_login_t - In the implementation block
@property (assign,nonatomic) double chat_connected_t;                   //@synthesize chat_connected_t=_chat_connected_t - In the implementation block
-(double)chat_state;
-(void)setChat_state:(double)arg1 ;
-(double)chat_socket_connect_t;
-(void)setChat_socket_connect_t:(double)arg1 ;
-(double)chat_login_t;
-(void)setChat_login_t:(double)arg1 ;
-(double)chat_post_login_t;
-(void)setChat_post_login_t:(double)arg1 ;
-(double)chat_connected_t;
-(void)setChat_connected_t:(double)arg1 ;
-(void)submit;
-(id)init;
@end

