/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:47:03 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/342EE397-EC3B-4D13-968C-80EF1D13592D/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WhatsApp-Structs.h>
#import <WhatsApp/WAViewController.h>
#import <WhatsApp/WAWallpaperImageViewDelegate.h>

@class UIScrollView, NSArray, UIImageView, UIView, NSString;

@interface WAWallpaperPickerViewController : WAViewController <WAWallpaperImageViewDelegate> {

	UIScrollView* _scrollView;
	NSArray* _imageViews;
	UIImageView* _beforeRotationSnapshotImageView;
	UIImageView* _afterRotationSnapshotImageView;
	UIView* _whiteBackgroundView;
	CGPoint _contentOffsetAtStartOfRotation;
	BOOL _disableImageRelayout;
	long long _pickerMode;

}

@property (assign,nonatomic) long long pickerMode;                  //@synthesize pickerMode=_pickerMode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)userDidSelectWallpaperImageView:(id)arg1 ;
-(void)loadAllImages;
-(void)loadAllColors;
-(void)layoutAllPreviews;
-(void)selectImage:(id)arg1 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(id)snapshot;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(long long)pickerMode;
-(void)setPickerMode:(long long)arg1 ;
@end

