/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:34:06 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/3DFA7E95-0979-4D86-B373-C986386EF259/Reddit.app/Reddit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Reddit/Reddit-Structs.h>
#import <Reddit/PagedTabViewController.h>
#import <Reddit/ComposeMessageViewControllerDelegate.h>
#import <Reddit/ActionSheetViewControllerDelegate.h>
#import <Reddit/ThemeUpdateCallbackProtocol.h>

@class LoggedOutView, MessageListViewController, CommentListViewController, NSString;

@interface InboxViewController : PagedTabViewController <ComposeMessageViewControllerDelegate, ActionSheetViewControllerDelegate, ThemeUpdateCallbackProtocol> {

	LoggedOutView* _loggedOutView;
	MessageListViewController* _messagesController;
	CommentListViewController* _userCommentsController;
	CommentListViewController* _postRepliesController;
	CommentListViewController* _mentionsController;

}

@property (nonatomic,retain) LoggedOutView * loggedOutView;                                   //@synthesize loggedOutView=_loggedOutView - In the implementation block
@property (nonatomic,retain) MessageListViewController * messagesController;                  //@synthesize messagesController=_messagesController - In the implementation block
@property (nonatomic,retain) CommentListViewController * userCommentsController;              //@synthesize userCommentsController=_userCommentsController - In the implementation block
@property (nonatomic,retain) CommentListViewController * postRepliesController;               //@synthesize postRepliesController=_postRepliesController - In the implementation block
@property (nonatomic,retain) CommentListViewController * mentionsController;                  //@synthesize mentionsController=_mentionsController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)analyticsScreenViewName;
-(void)layoutViewsForFrame:(CGRect)arg1 ;
-(void)actionSheetViewController:(id)arg1 didSelectItem:(id)arg2 ;
-(LoggedOutView *)loggedOutView;
-(void)didTapLoginButton;
-(void)didTapSignupButton;
-(void)setLoggedOutView:(LoggedOutView *)arg1 ;
-(void)themeDidChange:(id)arg1 ;
-(void)locallyMarkAllAsRead;
-(void)setUserCommentsController:(CommentListViewController *)arg1 ;
-(CommentListViewController *)userCommentsController;
-(void)setPostRepliesController:(CommentListViewController *)arg1 ;
-(CommentListViewController *)postRepliesController;
-(void)setMentionsController:(CommentListViewController *)arg1 ;
-(CommentListViewController *)mentionsController;
-(void)setupNavBarItems;
-(void)didTapComposeButton:(id)arg1 ;
-(void)didTapMarkAllReadButton:(id)arg1 ;
-(BOOL)shouldScrollContentViewToTop;
-(void)composeMessageViewController:(id)arg1 didFinishWithSuccess:(BOOL)arg2 ;
-(id)init;
-(void)dealloc;
-(void)viewDidLoad;
-(MessageListViewController *)messagesController;
-(void)setMessagesController:(MessageListViewController *)arg1 ;
@end

