/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:34:06 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/3DFA7E95-0979-4D86-B373-C986386EF259/Reddit.app/Reddit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class MPVASTLinearAd, NSArray, NSURL;

@interface MPVideoPlaybackCandidate : NSObject {

	MPVASTLinearAd* _linearAd;
	NSArray* _errorURLs;
	NSArray* _impressionURLs;
	double _minimumViewabilityTimeInterval;
	double _minimumFractionOfVideoVisible;
	NSURL* _viewabilityTrackingURL;

}

@property (nonatomic,retain) MPVASTLinearAd * linearAd;                          //@synthesize linearAd=_linearAd - In the implementation block
@property (nonatomic,retain) NSArray * errorURLs;                                //@synthesize errorURLs=_errorURLs - In the implementation block
@property (nonatomic,retain) NSArray * impressionURLs;                           //@synthesize impressionURLs=_impressionURLs - In the implementation block
@property (assign,nonatomic) double minimumViewabilityTimeInterval;              //@synthesize minimumViewabilityTimeInterval=_minimumViewabilityTimeInterval - In the implementation block
@property (assign,nonatomic) double minimumFractionOfVideoVisible;               //@synthesize minimumFractionOfVideoVisible=_minimumFractionOfVideoVisible - In the implementation block
@property (nonatomic,retain) NSURL * viewabilityTrackingURL;                     //@synthesize viewabilityTrackingURL=_viewabilityTrackingURL - In the implementation block
-(MPVASTLinearAd *)linearAd;
-(void)setLinearAd:(MPVASTLinearAd *)arg1 ;
-(NSArray *)errorURLs;
-(void)setErrorURLs:(NSArray *)arg1 ;
-(NSArray *)impressionURLs;
-(void)setImpressionURLs:(NSArray *)arg1 ;
-(double)minimumViewabilityTimeInterval;
-(void)setMinimumViewabilityTimeInterval:(double)arg1 ;
-(double)minimumFractionOfVideoVisible;
-(void)setMinimumFractionOfVideoVisible:(double)arg1 ;
-(NSURL *)viewabilityTrackingURL;
-(void)setViewabilityTrackingURL:(NSURL *)arg1 ;
@end

