/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:34:06 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/3DFA7E95-0979-4D86-B373-C986386EF259/Reddit.app/Reddit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class TWTRNetworkingPipelinePackage;

@interface TWTRRequestSigningOperation : NSOperation {

	TWTRNetworkingPipelinePackage* _networkingPackage;
	/*^block*/id _successCallbackToExecute;
	/*^block*/id _cancelCallbackToExecute;

}

@property (nonatomic,copy) id successCallbackToExecute;                                        //@synthesize successCallbackToExecute=_successCallbackToExecute - In the implementation block
@property (nonatomic,copy) id cancelCallbackToExecute;                                         //@synthesize cancelCallbackToExecute=_cancelCallbackToExecute - In the implementation block
@property (nonatomic,readonly) TWTRNetworkingPipelinePackage * networkingPackage;              //@synthesize networkingPackage=_networkingPackage - In the implementation block
-(TWTRNetworkingPipelinePackage *)networkingPackage;
-(void)invokeSuccessBlock:(id)arg1 ;
-(void)invokeCancelBlock;
-(id)successCallbackToExecute;
-(void)didInvokeCompletionBlock;
-(id)cancelCallbackToExecute;
-(void)setCancelCallbackToExecute:(id)arg1 ;
-(void)setSuccessCallbackToExecute:(id)arg1 ;
-(id)initWithPackage:(id)arg1 success:(/*^block*/id)arg2 cancel:(/*^block*/id)arg3 ;
-(id)init;
-(void)cancel;
-(void)main;
-(id)signRequest:(id)arg1 ;
@end

