/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:54:31 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/EDDCC4DC-B551-47FD-8F2D-ADD28D2EEB77/eBay.app/eBay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol EBNFollowedDataManagerObserver <EBNDataManagerObserver>
@optional
-(void)followedDataManager:(id)arg1 didUpdateDefaultSortOption:(long long)arg2;
-(void)followedDataManager:(id)arg1 didUpdateFollowStateForEntity:(id)arg2;
-(void)followedDataManager:(id)arg1 didUpdate:(long long)arg2;
-(void)followedDataManager:(id)arg1 didUpdateHiddenEntities:(long long)arg2;
-(void)followedDataManager:(id)arg1 didUpdateNotifyMeForEntity:(id)arg2;
-(void)followedDataManager:(id)arg1 didUpdateEmailNotificationForEntity:(id)arg2;
-(void)followedDataManager:(id)arg1 didUpdateBadgeCountForEntities:(id)arg2;
-(void)followedDataManager:(id)arg1 didUpdateViewedDateForEntity:(id)arg2;
-(void)followedDataManager:(id)arg1 willBeginFetch:(long long)arg2;
-(void)followedDataManager:(id)arg1 didCompleteFetch:(long long)arg2;
-(void)followedDataManager:(id)arg1 didError:(long long)arg2;
-(void)followedDataManager:(id)arg1 willBeginBadgeUpdate:(long long)arg2;
-(void)followedDataManager:(id)arg1 didCompleteBadgeUpdate:(long long)arg2;

@end

