/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:54:33 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/EDDCC4DC-B551-47FD-8F2D-ADD28D2EEB77/eBay.app/eBay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <eBay/EBUCartItemCellBase.h>

@class EBUItemSectionView, EBNShoppingCartItem;

@interface EBUCartItemImageCell : EBUCartItemCellBase {

	BOOL _isSaveForLaterItem;
	BOOL _isAuctionItem;
	BOOL _isCartItem;
	EBUItemSectionView* _itemSectionView;
	EBNShoppingCartItem* _cartItem;

}

@property (nonatomic,retain) EBUItemSectionView * itemSectionView;              //@synthesize itemSectionView=_itemSectionView - In the implementation block
@property (nonatomic,retain) EBNShoppingCartItem * cartItem;                    //@synthesize cartItem=_cartItem - In the implementation block
@property (assign) BOOL isSaveForLaterItem;                                     //@synthesize isSaveForLaterItem=_isSaveForLaterItem - In the implementation block
@property (assign) BOOL isAuctionItem;                                          //@synthesize isAuctionItem=_isAuctionItem - In the implementation block
@property (assign) BOOL isCartItem;                                             //@synthesize isCartItem=_isCartItem - In the implementation block
+(id)emptyCell;
-(double)optimalHeight;
-(void)imageLoadFailed:(id)arg1 error:(id)arg2 ;
-(void)setCartItem:(EBNShoppingCartItem *)arg1 ;
-(void)setupItemSectionView;
-(BOOL)isCartItem;
-(BOOL)isAuctionItem;
-(EBUItemSectionView *)itemSectionView;
-(void)setupFromEbayItem:(id)arg1 ;
-(double)itemSectionViewHeight;
-(void)setIsSaveForLaterItem:(BOOL)arg1 ;
-(void)setIsAuctionItem:(BOOL)arg1 ;
-(void)setIsCartItem:(BOOL)arg1 ;
-(void)imageLoadCompleted:(id)arg1 image:(id)arg2 ;
-(void)setupImage;
-(void)executeLoader:(id)arg1 ;
-(void)setItemSectionView:(EBUItemSectionView *)arg1 ;
-(void)setupItemViewSubtitleText;
-(void)setupItemViewPrice;
-(void)setupItemViewTitle;
-(void)setupItemEEKRating;
-(void)setupItemViewShippingPrice;
-(id)modelContextForLoader;
-(EBNShoppingCartItem *)cartItem;
-(BOOL)isSaveForLaterItem;
-(void)layoutSubviews;
-(double)actualHeight;
@end

