//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKPBaseConfiguration.h"

@class NSString;

@interface SKPConfiguration : SKPBaseConfiguration
{
}

@property(readonly, nonatomic, getter=isMOSEnabledForAllCalls) _Bool enableMOSForAllCalls;
@property(readonly, nonatomic, getter=isExpressionsSearchEnabled) _Bool expressionsSearchEnabled;
@property(readonly, nonatomic, getter=isLogoutRecoveryEnabled) _Bool logoutRecoveryEnabled;
@property(readonly, nonatomic, getter=isTypeCheckingInChatEnabled) _Bool typeCheckingInChatEnabled;
@property(readonly, nonatomic, getter=isLocalPlayoutOfDTMFToneEnabled) _Bool localPlayoutOfDTMFToneEnabled;
@property(readonly, nonatomic, getter=isShareExtensionEnabled) _Bool shareExtensionEnabled;
@property(readonly, nonatomic, getter=isAssertOnVideoBindingFailureEnabled) _Bool assertOnVideoBindingFailureEnabled;
@property(readonly, nonatomic, getter=isCallPushCancellationEnabled) _Bool callPushCancellationEnabled;
@property(readonly, nonatomic, getter=isShowPushFirstEnabled) _Bool showPushFirstEnabled;
@property(readonly, nonatomic, getter=isAssertCallInitializationEnabled) _Bool assertCallInitializationEnabled;
@property(readonly, nonatomic, getter=isUnifiedLoginEnabled) _Bool unifiedLoginEnabled;
@property(readonly, nonatomic, getter=isMsaCreateAccountEnabled) _Bool msaCreateAccountEnabled;
@property(readonly, nonatomic, getter=isMojisInRecentsEnabled) _Bool mojisInRecentsEnabled;
@property(readonly, nonatomic, getter=isShowLibraryVersionEnabled) _Bool showLibraryVersionEnabled;
@property(readonly, nonatomic, getter=isCoreSpotlightEnabled) _Bool coreSpotlightEnabled;
@property(readonly, nonatomic, getter=isForceUpgradeEnabled) _Bool forceUpgradeEnabled;
@property(readonly, nonatomic, getter=isCallFromNotificationEnabled) _Bool callFromNotificationEnabled;
@property(readonly, nonatomic, getter=isScrollingEmoticonPickerEnabled) _Bool scrollingEmoticonPickerEnabled;
@property(readonly, nonatomic, getter=isURLPreviewFetchCancellationEnabled) _Bool URLPreviewFetchCancellationEnabled;
@property(readonly, nonatomic, getter=isSimplifiedMobilePresenceEnabled) _Bool simplifiedMobilePresenceEnabled;
@property(readonly, nonatomic, getter=isEmoticonPickerCloudConfigurationEnabled) _Bool emoticonPickerCloudConfigurationEnabled;
@property(readonly, nonatomic, getter=isHeartCallToActionForLatestEnabled) _Bool heartCallToActionForLatestEnabled;
@property(readonly, nonatomic, getter=isHeartCallToActionForMediaEnabled) _Bool heartCallToActionForMediaEnabled;
@property(readonly, nonatomic, getter=isMessageHeartColumnEnabled) _Bool messageHeartColumnEnabled;
@property(readonly, nonatomic, getter=isMessageHeartRecentsEnabled) _Bool messageHeartRecentsEnabled;
@property(readonly, nonatomic, getter=isMessageHeartNotificationsEnabled) _Bool messageHeartNotificationsEnabled;
@property(readonly, nonatomic, getter=isMessageHeartingEnabled) _Bool messageHeartingEnabled;
@property(readonly, nonatomic, getter=isMessageDeliveryStatusEnabled) _Bool messageDeliveryStatusEnabled;
@property(readonly, nonatomic, getter=isCloudEmoticonsEnabled) _Bool cloudEmoticonsEnabled;
@property(readonly, nonatomic, getter=isWebMediaChatPickerEnabled) _Bool webMediaChatPickerEnabled;
@property(readonly, nonatomic, getter=isWebKitInternalBrowserEnabled) _Bool webKitInternalBrowserEnabled;
@property(readonly, nonatomic, getter=isLocationSharingErrorAlertEnabled) _Bool locationSharingErrorAlertEnabled;
@property(readonly, nonatomic, getter=isSendingLocationAvailable) _Bool sendingLocationAvailable;
@property(readonly, nonatomic, getter=isSendingContactsEnabled) _Bool sendingContactsEnabled;
@property(readonly, nonatomic, getter=isShareContactsEnabled) _Bool shareContactsEnabled;
@property(readonly, nonatomic, getter=isLastSeenEnabled) _Bool lastSeenEnabled;
@property(readonly, nonatomic, getter=isLocationSharingEnabled) _Bool locationSharingEnabled;
@property(readonly, nonatomic, getter=isDumpChatDebugInfoEnabled) _Bool dumpChatDebugInfoEnabled;
@property(readonly, nonatomic, getter=isIAPEnabled) _Bool IAPEnabled;
@property(readonly, nonatomic, getter=isChatInputEmoticonsEnabled) _Bool chatInputEmoticonsEnabled;
@property(readonly, nonatomic, getter=isChatCommandForTestingEnabled) _Bool chatCommandForTestingEnabled;
@property(readonly, nonatomic, getter=isBuildNumberOverridingEnabled) _Bool buildNumberOverridingEnabled;
@property(readonly, nonatomic, getter=isPushRegistrationSelfCheckInMyInfoEnabled) _Bool pushRegistrationSelfCheckInMyInfoEnabled;
@property(readonly, nonatomic, getter=isPushRegistrationSelfCheckAfterLoginEnabled) _Bool pushRegistrationSelfCheckAfterLoginEnabled;
@property(readonly, nonatomic, getter=isPushNotificationLoggingEnabled) _Bool pushNotificationLoggingEnabled;
@property(readonly, nonatomic, getter=isTokenCachingEnabled) _Bool tokenCachingEnabled;
@property(readonly, nonatomic, getter=isAutologinInstrumentationEnabled) _Bool autologinInstrumentationEnabled;
@property(readonly, nonatomic, getter=isCloudConferenceAvatarAssignmentEnabled) _Bool enableCloudConferenceAvatarAssignment;
@property(readonly, nonatomic, getter=isAccountStateMonitorEnabled) _Bool accountStateMonitorEnabled;
@property(readonly, nonatomic, getter=isAddFavoritesEnabled) _Bool addFavoritesEnabled;
@property(readonly, nonatomic, getter=isEchoCancellationEnabled) _Bool echoCancellationEnabled;
@property(readonly, nonatomic, getter=isPresenceEnabledInRecents) _Bool presenceEnabledInRecents;
@property(readonly, nonatomic, getter=isCallBackgroundBlurEnabled) _Bool callBackgroundBlurEnabled;
@property(readonly, nonatomic, getter=isCallAnimationEnabled) _Bool callAnimatedEnabled;
@property(readonly, nonatomic, getter=isHubCloudAnimationEnabled) _Bool hubCloudAnimationEnabled;
@property(readonly, nonatomic, getter=isTracingEnabled) _Bool tracingEnabled;
@property(readonly, nonatomic, getter=isStatisticsEnabled) _Bool statisticsEnabled;
@property(readonly, nonatomic, getter=isCompoundAvatarsEnabled) _Bool compoundAvatarsEnabled;
@property(readonly, nonatomic, getter=isVideoInRecentsEnabled) _Bool videoInRecentsEnabled;
@property(readonly, nonatomic, getter=isTrouterBombingEnabled) _Bool trouterBombingEnabled;
@property(readonly, nonatomic, getter=isExtendedTrouterDebuggingEnabled) _Bool extendedTrouterDebuggingEnabled;
@property(readonly, nonatomic, getter=isAdsEnabled) _Bool adsEnabled;
@property(readonly, nonatomic, getter=isProfileInWebPage) _Bool profileInWebPage;
@property(readonly, nonatomic, getter=isPerformanceMonitorEnabled) _Bool performanceMonitorEnabled;
@property(readonly, nonatomic, getter=isTrouterDebugTemplateKeyEnabled) _Bool trouterDebugTemplateKeyEnabled;
@property(readonly, nonatomic, getter=isHubVerticalPanoramaDynamicsEnabled) _Bool hubVerticalPanoramaDynamicsEnabled;
@property(readonly, nonatomic, getter=isWelcomeFlowEnabled) _Bool welcomeFlowEnabled;
@property(readonly, nonatomic, getter=isConsoleLoggingEnabled) _Bool consoleLoggingEnabled;
@property(readonly, nonatomic, getter=isDebugToolsEnabled) _Bool debugToolsEnabled;
@property(readonly, nonatomic, getter=isDogfoodFeedbackEnabled) _Bool dogfoodFeedbackEnabled;
@property(readonly, nonatomic, getter=isDebugTestLoggingEnabled) _Bool debugTestLoggingEnabled;
@property(readonly, nonatomic, getter=isLibraryLoggingEnabled) _Bool libraryLoggingEnabled;
@property(readonly, nonatomic, getter=isLoggingEnabled) _Bool loggingEnabled;
@property(readonly, nonatomic, getter=isAssertWhenLeakingOnLogoutEnabled) _Bool assertWhenLeakingOnLogoutEnabled;
@property(readonly, nonatomic, getter=isSessionContextObjectInvalidationEnabled) _Bool sessionContextObjectInvalidationEnabled;
- (_Bool)isInterAppCommunicationEnabled;
@property(readonly, nonatomic) NSString *applicationGroupIdentifier;
@property(readonly, nonatomic) NSString *customHockeyAppIdentifier;
@property(readonly, nonatomic) NSString *skypeRegistrarHostname;
@property(readonly, nonatomic) NSString *skypeWebServicesHostname;
@property(readonly, nonatomic) NSString *coreLibraryBuildName;
@property(readonly, nonatomic) NSString *coreLibraryConfigTypeName;
@property(readonly, nonatomic) NSString *coreLibraryBuildNumber;
@property(readonly, nonatomic) unsigned long long coreLibraryBranch;
@property(readonly, nonatomic) NSString *platformID;
- (_Bool)isValidSkypeVersionID:(id)arg1;
@property(readonly, nonatomic) NSString *skypeVersionID;
@property(readonly, nonatomic, getter=isCoreLibraryTrunk) _Bool coreLibraryTrunk;
@property(readonly, nonatomic, getter=isCoreLibraryRelease) _Bool coreLibraryRelease;
@property(readonly, nonatomic, getter=isCoreLibraryTestenv) _Bool coreLibraryTestenv;
@property(readonly, nonatomic, getter=isCoreLibraryInternal) _Bool coreLibraryInternal;
@property(readonly, nonatomic, getter=isChinaBuild) _Bool chinaBuild;
@property(readonly, nonatomic, getter=isFrankBuild) _Bool frankBuild;
@property(readonly, nonatomic, getter=isTestflightBuild) _Bool testflightBuild;
@property(readonly, nonatomic, getter=isDogfoodBuild) _Bool dogfoodBuild;
@property(readonly, nonatomic, getter=isAppStoreBuild) _Bool appStoreBuild;
@property(readonly, nonatomic, getter=isRelease) _Bool release;
@property(readonly, nonatomic, getter=isTest) _Bool test;
@property(readonly, nonatomic, getter=isDebug) _Bool debug;
@property(readonly, nonatomic, getter=isSimulator) _Bool simulator;
- (id)init;

@end

