//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MKSwitch, NSString, UIButton, UIView;

@interface SKPGroupProfileTableViewCell : UITableViewCell
{
    _Bool _settingsTitleHidden;
    _Bool _settingsSubTitleHidden;
    _Bool _buttonHidden;
    _Bool _switchOn;
    _Bool _switchHidden;
    _Bool _shouldShowSeparator;
    CDUnknownBlockType _actionBlock;
    NSString *_settingsTitle;
    NSString *_settingsSubTitle;
    UIButton *_cellButton;
    NSString *_buttonTitle;
    NSString *_cellAccessibilityLabel;
    MKSwitch *_cellSwitch;
    UIView *_separatorLine;
}

@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) MKSwitch *cellSwitch; // @synthesize cellSwitch=_cellSwitch;
@property(readonly, nonatomic) _Bool shouldShowSeparator; // @synthesize shouldShowSeparator=_shouldShowSeparator;
@property(retain, nonatomic) NSString *cellAccessibilityLabel; // @synthesize cellAccessibilityLabel=_cellAccessibilityLabel;
@property(nonatomic) _Bool switchHidden; // @synthesize switchHidden=_switchHidden;
@property(nonatomic) _Bool switchOn; // @synthesize switchOn=_switchOn;
@property(nonatomic) _Bool buttonHidden; // @synthesize buttonHidden=_buttonHidden;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) UIButton *cellButton; // @synthesize cellButton=_cellButton;
@property(nonatomic) _Bool settingsSubTitleHidden; // @synthesize settingsSubTitleHidden=_settingsSubTitleHidden;
@property(retain, nonatomic) NSString *settingsSubTitle; // @synthesize settingsSubTitle=_settingsSubTitle;
@property(nonatomic) _Bool settingsTitleHidden; // @synthesize settingsTitleHidden=_settingsTitleHidden;
@property(retain, nonatomic) NSString *settingsTitle; // @synthesize settingsTitle=_settingsTitle;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)attributesForTitleLabel;
@property(readonly, nonatomic) double cellHeight;
@property(nonatomic) _Bool buttonEnabled;
@property(nonatomic) _Bool switchEnabled;
- (void)setSwitchOn:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGPoint)accessibilityActivationPoint;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (id)accessibilityHint;
- (_Bool)isAccessibilityElement;
- (void)setupAccessibility;
- (void)setupLayout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

