//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TLSet_client_DH_params_answer.h"

@class NSData;

@interface TLSet_client_DH_params_answer$dh_gen_ok : TLSet_client_DH_params_answer
{
    NSData *_n_new_nonce_hash1;
}

@property(retain, nonatomic) NSData *n_new_nonce_hash1; // @synthesize n_new_nonce_hash1=_n_new_nonce_hash1;
- (void).cxx_destruct;
- (void)TLfillFieldsWithValues:(map_d3ce7d86 *)arg1;
- (id)TLbuildFromMetaObject:(shared_ptr_20f5e271)arg1;
- (int)TLconstructorName;
- (int)TLconstructorSignature;

@end

