/*
* This header is generated by classdump-dyld 0.7
* on Friday, October 30, 2015 at 11:57:02 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/8F19A127-6676-4AF1-9C62-4FB96FF45C56/Slack.app/Slack
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Slack/Slack-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>
#import <Slack/SLKTransitionDelegate.h>

@class SLKTransitionCoordinator, UIViewController, NSString;

@interface SLKModalWrapperController : UIViewController <UIViewControllerTransitioningDelegate, SLKTransitionDelegate> {

	unsigned long long _modalSheetStyle;
	SLKTransitionCoordinator* _transitionCoordinator;
	UIViewController* _nestedViewController;
	CGSize _preferredContentSize;
	CGRect _previousFrame;

}

@property (assign,nonatomic) unsigned long long modalSheetStyle;                            //@synthesize modalSheetStyle=_modalSheetStyle - In the implementation block
@property (nonatomic,retain) SLKTransitionCoordinator * transitionCoordinator;              //@synthesize transitionCoordinator=_transitionCoordinator - In the implementation block
@property (nonatomic,retain) UIViewController * nestedViewController;                       //@synthesize nestedViewController=_nestedViewController - In the implementation block
@property (assign,nonatomic) CGRect previousFrame;                                          //@synthesize previousFrame=_previousFrame - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithSheetStyle:(unsigned long long)arg1 ;
-(void)beginModalPresentation:(id)arg1 fromViewController:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)endModalPresentationAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(CGSize)transitionCoordinator:(id)arg1 sizeForViewController:(id)arg2 ;
-(unsigned long long)transitionCoordinator:(id)arg1 modalStyleForViewController:(id)arg2 ;
-(unsigned long long)transitionCoordinator:(id)arg1 buttonStyleForViewController:(id)arg2 ;
-(BOOL)transitionCoordinator:(id)arg1 canTapBackgroundToDismissViewController:(id)arg2 ;
-(BOOL)transitionCoordinator:(id)arg1 shouldDismissViewController:(id)arg2 ;
-(BOOL)transitionCoordinator:(id)arg1 shouldShowCloseButtonForViewController:(id)arg2 ;
-(void)transitionCoordinator:(id)arg1 willPresentViewController:(id)arg2 ;
-(void)transitionCoordinator:(id)arg1 willDismissViewController:(id)arg2 ;
-(void)transitionCoordinator:(id)arg1 didPresentViewController:(id)arg2 ;
-(void)transitionCoordinator:(id)arg1 didDismissViewController:(id)arg2 ;
-(void)setModalSheetStyle:(unsigned long long)arg1 ;
-(void)setPreviousFrame:(CGRect)arg1 ;
-(CGRect)previousFrame;
-(unsigned long long)modalSheetStyle;
-(void)beginModalPresentation:(id)arg1 fromViewController:(id)arg2 preferredContentSize:(CGSize)arg3 animated:(BOOL)arg4 completion:(/*^block*/id)arg5 ;
-(void)setNestedViewController:(UIViewController *)arg1 ;
-(CGRect)appropriateBounds;
-(UIViewController *)nestedViewController;
-(void)setTransitionCoordinator:(SLKTransitionCoordinator *)arg1 ;
-(void)dealloc;
-(id)init;
-(id)rootViewController;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(CGSize)preferredContentSize;
-(void)setPreferredContentSize:(CGSize)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3 ;
-(id)interactionControllerForPresentation:(id)arg1 ;
-(id)animationControllerForDismissedController:(id)arg1 ;
-(id)interactionControllerForDismissal:(id)arg1 ;
-(SLKTransitionCoordinator *)transitionCoordinator;
@end

