/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:34 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBAssetsLibraryListener.h>

@class FBUserSession, FBBackstageAssetsListenerAnnouncer, FBBackstageGeoCoder, NSArray, NSString;

@interface FBBackstageAssetsHandler : NSObject <FBAssetsLibraryListener> {

	FBUserSession* _session;
	unsigned long long _filters;
	FBBackstageAssetsListenerAnnouncer* _announcer;
	FBBackstageGeoCoder* _geocoder;
	NSArray* _assets;
	unsigned long long _hoursToCheck;

}

@property (assign,nonatomic) unsigned long long hoursToCheck;              //@synthesize hoursToCheck=_hoursToCheck - In the implementation block
@property (nonatomic,copy,readonly) NSArray * assets;                      //@synthesize assets=_assets - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)saveImage:(id)arg1 ;
+(id)saveVideo:(id)arg1 ;
+(void)removeTemporaryAssets;
-(void)assetsLibraryDidLoadAssets;
-(void)setHoursToCheck:(unsigned long long)arg1 ;
-(void)_indexAssets;
-(id)_filterWithPreIndexedAssets:(id)arg1 ;
-(id)_filterWithPostIndexedAssets:(id)arg1 ;
-(void)_geocodeAssets;
-(id)_applyFilter:(unsigned long long)arg1 toArray:(id)arg2 ;
-(id)initWithSession:(id)arg1 filters:(unsigned long long)arg2 ;
-(void)loadAssetsRequestingPermission:(BOOL)arg1 ;
-(unsigned long long)hoursToCheck;
-(void)setFilters:(unsigned long long)arg1 ;
-(NSArray *)assets;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
@end

