/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:34 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Facebook/FBComposerActivityTagIconPickerCollectionViewControllerDelegate.h>
#import <Facebook/FBComposerActivityTagObjectPickerViewControllerDelegate.h>
#import <Facebook/FBComposerExpressionPickerVerbViewControllerDelegate.h>
#import <Facebook/FBComposerActivityTagIconPickerViewControllerDelegate.h>
#import <Facebook/FBComposerCompositionStateChangedListener.h>

@protocol FBComposerExpressionPickerActivityViewControllerDelegate;
@class FBComposerCompositionState, UIViewController, FBComposerActivityTagIconPickerViewController, FBComposerActivityTagIconPickerCollectionViewController, FBComposerActivityTagObjectPickerViewController, FBComposerActivityTagPickerModelController, FBMemTaggableActivity, FBUserSession, FBComposerExpressionPickerVerbViewController, NSString;

@interface FBComposerExpressionPickerActivityViewController : UIViewController <FBComposerActivityTagIconPickerCollectionViewControllerDelegate, FBComposerActivityTagObjectPickerViewControllerDelegate, FBComposerExpressionPickerVerbViewControllerDelegate, FBComposerActivityTagIconPickerViewControllerDelegate, FBComposerCompositionStateChangedListener> {

	FBComposerCompositionState* _compositionState;
	UIViewController* _currentViewController;
	FBComposerActivityTagIconPickerViewController* _iconPickerController;
	FBComposerActivityTagIconPickerCollectionViewController* _iconPickerCollectionVC;
	FBComposerActivityTagObjectPickerViewController* _objectViewController;
	FBComposerActivityTagPickerModelController* _prefetchedActivityController;
	FBMemTaggableActivity* _selectedVerb;
	FBUserSession* _session;
	FBComposerExpressionPickerVerbViewController* _verbViewController;
	BOOL _viewAppeared;
	id<FBComposerExpressionPickerActivityViewControllerDelegate> _delegate;
	NSString* _preselectedActivityLegacyAPIID;
	NSString* _preselectedPickerTitle;

}

@property (assign,nonatomic,__weak) id<FBComposerExpressionPickerActivityViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * preselectedActivityLegacyAPIID;                                                   //@synthesize preselectedActivityLegacyAPIID=_preselectedActivityLegacyAPIID - In the implementation block
@property (nonatomic,copy) NSString * preselectedPickerTitle;                                                           //@synthesize preselectedPickerTitle=_preselectedPickerTitle - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)composerCompositionStateChangedFromPreviousCompositionState:(id)arg1 toCurrentCompositionState:(id)arg2 ;
-(void)composerActivityTagObjectPicker:(id)arg1 didPickTaggableActivity:(id)arg2 isFreeformEntry:(BOOL)arg3 ;
-(void)composerActivityTagIconPicker:(id)arg1 didPickTaggableActivity:(id)arg2 ;
-(void)composerActivityTagIconPickerCollectionViewController:(id)arg1 didPickTaggableActivity:(id)arg2 ;
-(id)initWithSession:(id)arg1 prefetchedActivityController:(id)arg2 ;
-(void)_presentObjectPickerAfterSelectingVerbWithPreselectedActivityLegacyAPIID:(id)arg1 preselectedPickerTitle:(id)arg2 ;
-(void)navigateToVerbPicker;
-(void)_navigateToPickerViewController:(id)arg1 ;
-(void)clearSelectedObject;
-(void)_presentIconPickerForObject:(id)arg1 ;
-(void)expressionPickerVerbViewController:(id)arg1 didPickVerb:(id)arg2 ;
-(void)expressionPickerVerbViewControllerDidClearSelectedObject:(id)arg1 ;
-(NSString *)preselectedActivityLegacyAPIID;
-(void)setPreselectedActivityLegacyAPIID:(NSString *)arg1 ;
-(NSString *)preselectedPickerTitle;
-(void)setPreselectedPickerTitle:(NSString *)arg1 ;
-(void)setDelegate:(id<FBComposerExpressionPickerActivityViewControllerDelegate>)arg1 ;
-(id<FBComposerExpressionPickerActivityViewControllerDelegate>)delegate;
-(void)viewWillLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
@end

