/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:35 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSSet, NSOrderedSet;

@interface FBComposerFeedTopicsPickerState : FBValueObject <NSCopying> {

	NSSet* _selectedIdentifiers;
	NSOrderedSet* _selectedFeedTopics;
	unsigned long long _maximumNumberOfTopicsAllowed;

}

@property (nonatomic,copy,readonly) NSSet * selectedIdentifiers;                             //@synthesize selectedIdentifiers=_selectedIdentifiers - In the implementation block
@property (nonatomic,copy,readonly) NSOrderedSet * selectedFeedTopics;                       //@synthesize selectedFeedTopics=_selectedFeedTopics - In the implementation block
@property (nonatomic,readonly) unsigned long long maximumNumberOfTopicsAllowed;              //@synthesize maximumNumberOfTopicsAllowed=_maximumNumberOfTopicsAllowed - In the implementation block
-(NSSet *)selectedIdentifiers;
-(unsigned long long)maximumNumberOfTopicsAllowed;
-(NSOrderedSet *)selectedFeedTopics;
-(id)initWithSelectedIdentifiers:(id)arg1 selectedFeedTopics:(id)arg2 maximumNumberOfTopicsAllowed:(unsigned long long)arg3 ;
@end

