/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:49 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@protocol FBCoveringSplitViewDelegate;
@class UITapGestureRecognizer, UIView, UIColor, UIImageView;

@interface FBCoveringSplitView : UIView {

	double _leftViewWidth;
	double _rightViewWidth;
	UITapGestureRecognizer* _tapGestureRecognizer;
	UIView* _statusBarBackground;
	UIColor* _statusBarBackgroundColor;
	UIView* _leftDividerView;
	UIView* _rightDividerView;
	UIView* _leftContainerView;
	UIView* _rightContainerView;
	UIView* _centerOuterContainerView;
	UIView* _centerContainerView;
	UIImageView* _topLeftCornerView;
	UIImageView* _topRightCornerView;
	int _splitMode;
	UIView* _leftTopView;
	UIView* _leftBottomView;
	id<FBCoveringSplitViewDelegate> _delegate;
	double _leftViewMaxWidth;
	double _smallerRightGutterWidthRatio;
	double _leftDividerPosition;
	double _rightDividerPosition;
	double _topLayoutGuideLength;
	double _bottomLayoutGuideLength;
	UIView* _gutterDismissView;

}

@property (nonatomic,retain) UIView * gutterDismissView;                                   //@synthesize gutterDismissView=_gutterDismissView - In the implementation block
@property (nonatomic,retain) UITapGestureRecognizer * tapGestureRecognizer;                //@synthesize tapGestureRecognizer=_tapGestureRecognizer - In the implementation block
@property (nonatomic,readonly) UIView * leftDividerView;                                   //@synthesize leftDividerView=_leftDividerView - In the implementation block
@property (nonatomic,readonly) UIView * leftContainerView;                                 //@synthesize leftContainerView=_leftContainerView - In the implementation block
@property (nonatomic,readonly) UIView * centerContainerView;                               //@synthesize centerContainerView=_centerContainerView - In the implementation block
@property (nonatomic,readonly) UIView * centerOuterContainerView;                          //@synthesize centerOuterContainerView=_centerOuterContainerView - In the implementation block
@property (nonatomic,readonly) UIView * leftTopView;                                       //@synthesize leftTopView=_leftTopView - In the implementation block
@property (nonatomic,readonly) UIView * leftBottomView;                                    //@synthesize leftBottomView=_leftBottomView - In the implementation block
@property (nonatomic,readonly) UIView * rightContainerView;                                //@synthesize rightContainerView=_rightContainerView - In the implementation block
@property (assign,nonatomic,__weak) id<FBCoveringSplitViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) double leftViewMaxWidth;                                      //@synthesize leftViewMaxWidth=_leftViewMaxWidth - In the implementation block
@property (nonatomic,readonly) double leftViewDefaultWidth; 
@property (assign,nonatomic) double smallerRightGutterWidthRatio;                          //@synthesize smallerRightGutterWidthRatio=_smallerRightGutterWidthRatio - In the implementation block
@property (nonatomic,readonly) int splitMode;                                              //@synthesize splitMode=_splitMode - In the implementation block
@property (nonatomic,retain) UIColor * statusBarBackgroundColor; 
@property (assign,nonatomic) double leftDividerPosition;                                   //@synthesize leftDividerPosition=_leftDividerPosition - In the implementation block
@property (assign,nonatomic) double rightDividerPosition;                                  //@synthesize rightDividerPosition=_rightDividerPosition - In the implementation block
@property (assign,nonatomic) double topLayoutGuideLength;                                  //@synthesize topLayoutGuideLength=_topLayoutGuideLength - In the implementation block
@property (assign,nonatomic) double bottomLayoutGuideLength;                               //@synthesize bottomLayoutGuideLength=_bottomLayoutGuideLength - In the implementation block
-(void)setBottomLayoutGuideLength:(double)arg1 ;
-(UIView *)rightContainerView;
-(double)topLayoutGuideLength;
-(void)setTopLayoutGuideLength:(double)arg1 ;
-(double)bottomLayoutGuideLength;
-(UIView *)leftContainerView;
-(void)_layoutDividerView;
-(void)_layoutLeftContainerView;
-(void)_layoutRightContainerView;
-(void)_layoutStatusBarBackground;
-(double)_defaultLeftGutterViewWidth;
-(UIColor *)statusBarBackgroundColor;
-(void)setSplitMode:(int)arg1 layoutMode:(int)arg2 withDuration:(double)arg3 animationOptions:(unsigned long long)arg4 completion:(/*^block*/id)arg5 ;
-(void)setGutterDismissView:(UIView *)arg1 ;
-(void)didTapToDismissGutter:(id)arg1 ;
-(void)_enableGutterDismissView;
-(double)_defaultRightGutterViewWidth;
-(void)_disableGutterDismissView;
-(void)_setDividerPosition:(double)arg1 fromDrag:(BOOL)arg2 layoutMode:(int)arg3 withDuration:(double)arg4 withAnimationOptions:(unsigned long long)arg5 completion:(/*^block*/id)arg6 ;
-(void)_layoutCenterContainerView;
-(void)_positionCornerViews;
-(void)_layoutRightDividerView;
-(void)setStatusBarBackgroundColor:(UIColor *)arg1 ;
-(BOOL)shouldShowLeftView;
-(BOOL)shouldShowRightView;
-(void)setSplitMode:(int)arg1 layoutMode:(int)arg2 withDuration:(double)arg3 completion:(/*^block*/id)arg4 ;
-(void)setLeftDividerPosition:(double)arg1 ;
-(double)leftViewDefaultWidth;
-(void)setLeftViewMaxWidth:(double)arg1 ;
-(void)setSmallerRightGutterWidthRatio:(double)arg1 ;
-(UIView *)leftDividerView;
-(UIView *)centerContainerView;
-(UIView *)centerOuterContainerView;
-(UIView *)leftTopView;
-(UIView *)leftBottomView;
-(double)leftViewMaxWidth;
-(double)smallerRightGutterWidthRatio;
-(double)leftDividerPosition;
-(double)rightDividerPosition;
-(void)setRightDividerPosition:(double)arg1 ;
-(UIView *)gutterDismissView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<FBCoveringSplitViewDelegate>)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)addSubview:(id)arg1 ;
-(void)layoutSubviews;
-(void)insertSubview:(id)arg1 atIndex:(long long)arg2 ;
-(id<FBCoveringSplitViewDelegate>)delegate;
-(void)insertSubview:(id)arg1 belowSubview:(id)arg2 ;
-(void)insertSubview:(id)arg1 aboveSubview:(id)arg2 ;
-(int)splitMode;
-(UITapGestureRecognizer *)tapGestureRecognizer;
-(void)setTapGestureRecognizer:(UITapGestureRecognizer *)arg1 ;
@end

