/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:40 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBEventLiveToolbarViewModel : FBValueObject <NSCopying> {

	BOOL _canShowSeenNux;
	BOOL _canPost;
	BOOL _canEdit;
	BOOL _canReport;
	BOOL _canInvite;
	BOOL _canSave;
	BOOL _canUnsave;
	BOOL _canShare;
	BOOL _hasRSVPd;
	BOOL _isCreator;
	BOOL _isHost;
	BOOL _isInvited;
	BOOL _isInterestedConnectionStyle;
	BOOL _hasPendingInvite;
	BOOL _initiallyGoing;
	BOOL _initiallyInvited;
	BOOL _isPast;
	BOOL _hasAlbum;
	BOOL _isHeadLoading;
	BOOL _hasTopBorder;
	BOOL _isPromotable;
	BOOL _isCanceled;
	BOOL _isCancelable;
	long long _rsvpStatus;
	long long _watchStatus;
	NSString* _eventKind;
	long long _inviteButtonPermutation;

}

@property (nonatomic,readonly) BOOL canShowSeenNux;                            //@synthesize canShowSeenNux=_canShowSeenNux - In the implementation block
@property (nonatomic,readonly) BOOL canPost;                                   //@synthesize canPost=_canPost - In the implementation block
@property (nonatomic,readonly) BOOL canEdit;                                   //@synthesize canEdit=_canEdit - In the implementation block
@property (nonatomic,readonly) BOOL canReport;                                 //@synthesize canReport=_canReport - In the implementation block
@property (nonatomic,readonly) BOOL canInvite;                                 //@synthesize canInvite=_canInvite - In the implementation block
@property (nonatomic,readonly) BOOL canSave;                                   //@synthesize canSave=_canSave - In the implementation block
@property (nonatomic,readonly) BOOL canUnsave;                                 //@synthesize canUnsave=_canUnsave - In the implementation block
@property (nonatomic,readonly) BOOL canShare;                                  //@synthesize canShare=_canShare - In the implementation block
@property (nonatomic,readonly) BOOL hasRSVPd;                                  //@synthesize hasRSVPd=_hasRSVPd - In the implementation block
@property (nonatomic,readonly) BOOL isCreator;                                 //@synthesize isCreator=_isCreator - In the implementation block
@property (nonatomic,readonly) BOOL isHost;                                    //@synthesize isHost=_isHost - In the implementation block
@property (nonatomic,readonly) BOOL isInvited;                                 //@synthesize isInvited=_isInvited - In the implementation block
@property (nonatomic,readonly) BOOL isInterestedConnectionStyle;               //@synthesize isInterestedConnectionStyle=_isInterestedConnectionStyle - In the implementation block
@property (nonatomic,readonly) long long rsvpStatus;                           //@synthesize rsvpStatus=_rsvpStatus - In the implementation block
@property (nonatomic,readonly) long long watchStatus;                          //@synthesize watchStatus=_watchStatus - In the implementation block
@property (nonatomic,readonly) BOOL hasPendingInvite;                          //@synthesize hasPendingInvite=_hasPendingInvite - In the implementation block
@property (nonatomic,readonly) BOOL initiallyGoing;                            //@synthesize initiallyGoing=_initiallyGoing - In the implementation block
@property (nonatomic,readonly) BOOL initiallyInvited;                          //@synthesize initiallyInvited=_initiallyInvited - In the implementation block
@property (nonatomic,readonly) BOOL isPast;                                    //@synthesize isPast=_isPast - In the implementation block
@property (nonatomic,readonly) BOOL hasAlbum;                                  //@synthesize hasAlbum=_hasAlbum - In the implementation block
@property (nonatomic,copy,readonly) NSString * eventKind;                      //@synthesize eventKind=_eventKind - In the implementation block
@property (nonatomic,readonly) BOOL isHeadLoading;                             //@synthesize isHeadLoading=_isHeadLoading - In the implementation block
@property (nonatomic,readonly) BOOL hasTopBorder;                              //@synthesize hasTopBorder=_hasTopBorder - In the implementation block
@property (nonatomic,readonly) BOOL isPromotable;                              //@synthesize isPromotable=_isPromotable - In the implementation block
@property (nonatomic,readonly) BOOL isCanceled;                                //@synthesize isCanceled=_isCanceled - In the implementation block
@property (nonatomic,readonly) BOOL isCancelable;                              //@synthesize isCancelable=_isCancelable - In the implementation block
@property (nonatomic,readonly) long long inviteButtonPermutation;              //@synthesize inviteButtonPermutation=_inviteButtonPermutation - In the implementation block
-(NSString *)eventKind;
-(BOOL)canReport;
-(BOOL)isInterestedConnectionStyle;
-(BOOL)isHeadLoading;
-(BOOL)isCreator;
-(long long)rsvpStatus;
-(BOOL)isPromotable;
-(long long)watchStatus;
-(BOOL)hasPendingInvite;
-(BOOL)initiallyGoing;
-(BOOL)initiallyInvited;
-(BOOL)canUnsave;
-(BOOL)canShare;
-(BOOL)canInvite;
-(long long)inviteButtonPermutation;
-(id)initWithCanShowSeenNux:(BOOL)arg1 canPost:(BOOL)arg2 canEdit:(BOOL)arg3 canReport:(BOOL)arg4 canInvite:(BOOL)arg5 canSave:(BOOL)arg6 canUnsave:(BOOL)arg7 canShare:(BOOL)arg8 hasRSVPd:(BOOL)arg9 isCreator:(BOOL)arg10 isHost:(BOOL)arg11 isInvited:(BOOL)arg12 isInterestedConnectionStyle:(BOOL)arg13 rsvpStatus:(long long)arg14 watchStatus:(long long)arg15 hasPendingInvite:(BOOL)arg16 initiallyGoing:(BOOL)arg17 initiallyInvited:(BOOL)arg18 isPast:(BOOL)arg19 hasAlbum:(BOOL)arg20 eventKind:(id)arg21 isHeadLoading:(BOOL)arg22 hasTopBorder:(BOOL)arg23 isPromotable:(BOOL)arg24 isCanceled:(BOOL)arg25 isCancelable:(BOOL)arg26 inviteButtonPermutation:(long long)arg27 ;
-(BOOL)canShowSeenNux;
-(BOOL)canPost;
-(BOOL)hasRSVPd;
-(BOOL)isInvited;
-(BOOL)isHost;
-(BOOL)isCanceled;
-(BOOL)hasAlbum;
-(BOOL)canEdit;
-(BOOL)isPast;
-(BOOL)isCancelable;
-(BOOL)hasTopBorder;
-(BOOL)canSave;
@end

