/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:36 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@protocol FBSerializableEdgeFilter;
@class NSArray;

@interface FBFeedGraphQLConnectionManagerEdgeFilter : NSObject <NSCoding> {

	id<FBSerializableEdgeFilter> _edgeFilter;
	NSArray* _feedTypes;

}

@property (nonatomic,readonly) id<FBSerializableEdgeFilter> edgeFilter;              //@synthesize edgeFilter=_edgeFilter - In the implementation block
@property (nonatomic,copy,readonly) NSArray * feedTypes;                             //@synthesize feedTypes=_feedTypes - In the implementation block
-(NSArray *)feedTypes;
-(id<FBSerializableEdgeFilter>)edgeFilter;
-(id)initWithEdgeFilter:(id)arg1 feedTypes:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

