/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:50 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSURL;

@interface FBFontResource : NSObject <NSCoding> {

	NSString* _name;
	NSString* _version;
	NSURL* _url;
	long long _packagingMask;

}

@property (nonatomic,copy,readonly) NSString * name;                 //@synthesize name=_name - In the implementation block
@property (nonatomic,copy,readonly) NSString * version;              //@synthesize version=_version - In the implementation block
@property (nonatomic,copy,readonly) NSURL * url;                     //@synthesize url=_url - In the implementation block
@property (nonatomic,readonly) long long packagingMask;              //@synthesize packagingMask=_packagingMask - In the implementation block
+(id)fontResourceWithName:(id)arg1 version:(id)arg2 url:(id)arg3 packagingMask:(long long)arg4 ;
-(id)initWithName:(id)arg1 version:(id)arg2 url:(id)arg3 packagingMask:(long long)arg4 ;
-(long long)packagingMask;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)description;
-(NSString *)name;
-(NSURL *)url;
-(NSString *)version;
@end

