/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:35 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class FBItemView, FBNetworkImageView, UIView;

@interface FBGroupsMemberCompaniesTableViewCell : UITableViewCell {

	FBItemView* _itemView;
	FBNetworkImageView* _networkImageView;
	UIView* _dividerView;
	BOOL _lastCell;

}

@property (assign,nonatomic) BOOL lastCell;              //@synthesize lastCell=_lastCell - In the implementation block
-(id)initWithImageDownloader:(id)arg1 reuseIdentifier:(id)arg2 ;
-(void)setWorkCommunity:(id)arg1 ;
-(void)setLastCell:(BOOL)arg1 ;
-(BOOL)lastCell;
-(void)layoutSubviews;
-(void)prepareForReuse;
@end

