/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:51 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBGraphQLInput.h>

@class NSNumber;

@interface FBGravityGeoLocation : FBGraphQLInput {

	NSNumber* _pulsarRssi;
	NSNumber* _latitude;
	NSNumber* _longitude;
	NSNumber* _horizontalAccuracy;
	NSNumber* _verticalAccuracy;
	NSNumber* _clientLocationTime;
	NSNumber* _clientCurrentTime;

}

@property (nonatomic,copy) NSNumber * pulsarRssi;                      //@synthesize pulsarRssi=_pulsarRssi - In the implementation block
@property (nonatomic,copy) NSNumber * latitude;                        //@synthesize latitude=_latitude - In the implementation block
@property (nonatomic,copy) NSNumber * longitude;                       //@synthesize longitude=_longitude - In the implementation block
@property (nonatomic,copy) NSNumber * horizontalAccuracy;              //@synthesize horizontalAccuracy=_horizontalAccuracy - In the implementation block
@property (nonatomic,copy) NSNumber * verticalAccuracy;                //@synthesize verticalAccuracy=_verticalAccuracy - In the implementation block
@property (nonatomic,copy) NSNumber * clientLocationTime;              //@synthesize clientLocationTime=_clientLocationTime - In the implementation block
@property (nonatomic,copy) NSNumber * clientCurrentTime;               //@synthesize clientCurrentTime=_clientCurrentTime - In the implementation block
-(void)setClientCurrentTime:(NSNumber *)arg1 ;
-(void)setClientLocationTime:(NSNumber *)arg1 ;
-(void)setPulsarRssi:(NSNumber *)arg1 ;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(NSNumber *)pulsarRssi;
-(NSNumber *)clientLocationTime;
-(NSNumber *)clientCurrentTime;
-(void)setHorizontalAccuracy:(NSNumber *)arg1 ;
-(void)setVerticalAccuracy:(NSNumber *)arg1 ;
-(void)setLatitude:(NSNumber *)arg1 ;
-(void)setLongitude:(NSNumber *)arg1 ;
-(NSNumber *)verticalAccuracy;
-(NSNumber *)horizontalAccuracy;
-(NSNumber *)latitude;
-(NSNumber *)longitude;
@end

