/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:38 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_group;
@class NSObject, FBUserSession;

@interface FBInspirationMaskDownloader : NSObject {

	NSObject*<OS_dispatch_group> _downloadGroup;
	FBUserSession* _session;

}
-(void)downloadMaskAssetsForMask:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_downloadMaskAssetsForMask:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_createMaskAndCallCompletion:(/*^block*/id)arg1 name:(id)arg2 facePlaceholderImageURL:(id)arg3 assets:(id)arg4 ;
-(id)initWithSession:(id)arg1 ;
@end

