/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:36 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/MNThreadMarkRunning.h>
#import <Facebook/FBViewerContextClassProvidable.h>

@protocol MNAuthenticationManager;
@class FBMMQTTSender, FBMMQTTConnectStateTrackerService, FBUserSession, NSString;

@interface FBMMQTTMarkingAdapter : NSObject <MNThreadMarkRunning, FBViewerContextClassProvidable> {

	FBMMQTTSender* _mqttSender;
	id<MNAuthenticationManager> _authenticationManager;
	FBMMQTTConnectStateTrackerService* _mqttConnectionStateTrackerService;
	FBUserSession* _session;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)initWithMQTTSender:(id)arg1 authenticationManager:(id)arg2 mqttConnectionStateTrackerService:(id)arg3 session:(id)arg4 ;
-(void)markThreadWithThreadKey:(id)arg1 action:(id)arg2 listener:(id)arg3 ;
@end

