/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:36 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBViewerContextClassProvidable.h>
#import <Facebook/MNMessagesSyncIrisDeltaProcessing.h>

@class MNFetchedThreadKeyTracker, FBMUserInvalidator, FBAnalytics, FBMSPForcedFetchDeltaHandlerListeningAnnouncer, NSString;

@interface FBMSPForcedFetchDeltaHandler : NSObject <FBViewerContextClassProvidable, MNMessagesSyncIrisDeltaProcessing> {

	MNFetchedThreadKeyTracker* _fetchedThreadKeyTracker;
	FBMUserInvalidator* _userInvalidator;
	FBAnalytics* _analytics;
	FBMSPForcedFetchDeltaHandlerListeningAnnouncer* _forceFetchListeningAnnouncer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)initWithFetchedThreadKeyTracker:(id)arg1 userInvalidator:(id)arg2 analytics:(id)arg3 forceFetchListeningAnnouncer:(id)arg4 ;
-(void)_logAnalyticsForDelta:(id)arg1 ;
-(void)_processForceFetchDelta:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)deltasWithMetadataFromDeltaWrapper:(id)arg1 startingWithSequenceId:(long long)arg2 ;
-(BOOL)shouldForceFetchInbox:(id)arg1 ;
-(void)handleDelta:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

