/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:31 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>
#import <Facebook/FBReactionBrickComponent.h>

@protocol FBQueriedReactionUnitComponentFieldsProtocol, FBQueriedReactionUnitFieldsProtocol;
@class NSArray, FBReactionContext, FBMemModelObject;

@interface FBReactionHorizontalActionListBrickComponent : CKCompositeComponent <FBReactionBrickComponent> {

	NSArray* _actionAdapters;
	NSArray* _buttonComponents;
	FBReactionContext* _reactionContext;
	FBMemModelObject*<FBQueriedReactionUnitComponentFieldsProtocol> _unitComponent;
	FBMemModelObject*<FBQueriedReactionUnitFieldsProtocol> _unit;

}
+(id)newWithReactionContext:(id)arg1 resultStyle:(id)arg2 reactionUnit:(id)arg3 reactionUnitComponent:(id)arg4 position:(unsigned long long)arg5 indexPath:(id)arg6 ;
+(id)defaultTextColorForReactionContext:(id)arg1 isFooterAction:(BOOL)arg2 ;
+(id)selectedTextColorForReactionContext:(id)arg1 isFooterAction:(BOOL)arg2 ;
+(id)highlightedTextColorForReactionContext:(id)arg1 isFooterAction:(BOOL)arg2 ;
+(id)imageForUIControlStateNormalForReactionContext:(id)arg1 actionAdapter:(id)arg2 componentStyle:(id)arg3 ;
+(id)imageForUIControlStateSelectedForReactionContext:(id)arg1 actionAdapter:(id)arg2 componentStyle:(id)arg3 ;
+(id)imageForUIControlStateHighlightedForReactionContext:(id)arg1 actionAdapter:(id)arg2 componentStyle:(id)arg3 ;
+(id)textFontForReactionContext:(id)arg1 isFooterAction:(BOOL)arg2 ;
+(UIEdgeInsets)verticalDividerInsetsForReactionContext:(id)arg1 ;
+(id)initialState;
-(void)buttonTapped:(id)arg1 ;
@end

