/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:29 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSArray;


@protocol FBSearchNullStateCombinedEndpointControllerProtocol <NSObject>
@property (nonatomic,copy,readonly) NSArray * modules; 
@property (assign,nonatomic,__weak) id<FBSearchNullStateCombinedEndpointControllerDelegate> delegate; 
@property (nonatomic,readonly) BOOL isCombinedEndpointReady; 
@property (nonatomic,readonly) BOOL isCombinedEndpointLoading; 
@required
-(NSArray *)modules;
-(void)requestTailModuleAsScrollPositionsReachingEnd;
-(id)removedSuggestionsIfNeeded;
-(void)clearCachedData;
-(void)refreshCombinedEndpointSection;
-(BOOL)isCombinedEndpointLoading;
-(id)statusDictForLogging;
-(void)unbadgeNullStateSuggestions;
-(void)checkForNewTopModuleTopics;
-(void)requestCombinedEndpointContentIfNeeded;
-(id)lastPersistedDate;
-(id)statusStringForLogging;
-(BOOL)isCombinedEndpointReady;
-(void)setDelegate:(id)arg1;
-(id<FBSearchNullStateCombinedEndpointControllerDelegate>)delegate;
-(id)initWithSession:(id)arg1;

@end

