/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:36 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class FBSearchResultsActivityListenerAnnouncer, FBSearchResultsLogEventListenerAnnouncer, FBSearchResultsStoryLoggingManager, NSString, FBSerpConfig, NSDictionary, CLLocation, FBListLogger;


@protocol FBSearchResultsContextProtocol <FBCommonComponentContextProtocol>
@property (nonatomic,readonly) FBSearchResultsActivityListenerAnnouncer * resultsActivityAnnouncer; 
@property (nonatomic,readonly) FBSearchResultsLogEventListenerAnnouncer * logAnnouncer; 
@property (nonatomic,readonly) FBSearchResultsStoryLoggingManager * storyLoggingManager; 
@property (nonatomic,copy,readonly) NSString * resultsSessionID; 
@property (nonatomic,copy,readonly) NSString * verticalToLog; 
@property (nonatomic,readonly) FBSerpConfig * serpConfig; 
@property (nonatomic,copy,readonly) NSDictionary * optionalDependencies; 
@property (nonatomic,copy,readonly) CLLocation * userLocation; 
@property (nonatomic,readonly) FBListLogger * logger; 
@required
-(NSString *)resultsSessionID;
-(NSString *)verticalToLog;
-(NSDictionary *)optionalDependencies;
-(FBSerpConfig *)serpConfig;
-(FBSearchResultsLogEventListenerAnnouncer *)logAnnouncer;
-(FBSearchResultsActivityListenerAnnouncer *)resultsActivityAnnouncer;
-(FBSearchResultsStoryLoggingManager *)storyLoggingManager;
-(FBListLogger *)logger;
-(CLLocation *)userLocation;

@end

