/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:34 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, FBMemPage;

@interface FBSocialSearchStoryConversionModel : FBValueObject <NSCopying> {

	NSString* _storyGraphQLID;
	FBMemPage* _place;

}

@property (nonatomic,copy,readonly) NSString * storyGraphQLID;              //@synthesize storyGraphQLID=_storyGraphQLID - In the implementation block
@property (nonatomic,copy,readonly) FBMemPage * place;                      //@synthesize place=_place - In the implementation block
-(NSString *)storyGraphQLID;
-(id)initWithStoryGraphQLID:(id)arg1 place:(id)arg2 ;
-(FBMemPage *)place;
@end

