/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:44 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBStickerResourceMetadata : FBValueObject <NSCopying> {

	NSString* _fbId;
	unsigned long long _resourceType;

}

@property (nonatomic,copy,readonly) NSString * fbId;                         //@synthesize fbId=_fbId - In the implementation block
@property (nonatomic,readonly) unsigned long long resourceType;              //@synthesize resourceType=_resourceType - In the implementation block
-(NSString *)fbId;
-(id)initWithFbId:(id)arg1 resourceType:(unsigned long long)arg2 ;
-(unsigned long long)resourceType;
@end

