/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:52 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSDictionary, NSString, NSURL;

@interface FBURLSessionRequest : NSObject <NSSecureCoding> {

	NSDictionary* _allHTTPHeaderFields;
	BOOL _allowsCellularAccess;
	unsigned long long _cachePolicy;
	NSString* _HTTPMethod;
	BOOL _HTTPShouldHandleCookies;
	BOOL _HTTPShouldUsePipelining;
	unsigned long long _networkServiceType;
	double _timeoutInterval;
	NSURL* _URL;

}
+(BOOL)supportsSecureCoding;
-(id)initWithURL:(id)arg1 cachePolicy:(unsigned long long)arg2 timeoutInterval:(double)arg3 networkServiceType:(unsigned long long)arg4 allowsCellularAccess:(BOOL)arg5 allHTTPHeaderFields:(id)arg6 HTTPMethod:(id)arg7 HTTPShouldHandleCookies:(BOOL)arg8 HTTPShouldUsePipelining:(BOOL)arg9 ;
-(id)buildRequest;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithRequest:(id)arg1 ;
@end

