/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:30 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/CKCompositeComponent.h>

@class NSString, FBMemExploreFeed, FBVideoHomeToolbox, FBVideoHomeChannelLoggingData;

@interface FBVideoHomeLiveTopicComponent : CKCompositeComponent {

	NSString* _mutationSurface;
	BOOL _isInHScroll;
	FBMemExploreFeed* _model;
	FBVideoHomeToolbox* _toolbox;
	FBVideoHomeChannelLoggingData* _channelData;
	long long _index;

}

@property (nonatomic,readonly) FBMemExploreFeed * model;                                 //@synthesize model=_model - In the implementation block
@property (nonatomic,readonly) FBVideoHomeToolbox * toolbox;                             //@synthesize toolbox=_toolbox - In the implementation block
@property (nonatomic,readonly) FBVideoHomeChannelLoggingData * channelData;              //@synthesize channelData=_channelData - In the implementation block
@property (nonatomic,readonly) long long index;                                          //@synthesize index=_index - In the implementation block
@property (nonatomic,readonly) BOOL isInHScroll;                                         //@synthesize isInHScroll=_isInHScroll - In the implementation block
+(id)newWithModel:(id)arg1 index:(long long)arg2 mutationSurface:(id)arg3 isCornerRounded:(BOOL)arg4 context:(id)arg5 channelData:(id)arg6 isInHScroll:(BOOL)arg7 size:(const CKComponentSize*)arg8 ;
-(FBVideoHomeToolbox *)toolbox;
-(BOOL)isInHScroll;
-(FBVideoHomeChannelLoggingData *)channelData;
-(void)didTap:(id)arg1 atIndex:(id)arg2 ;
-(void)didTapButton:(id)arg1 ;
-(FBMemExploreFeed *)model;
-(long long)index;
@end

