/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:36 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBWebRTCEngineListener <NSObject>
@required
-(void)callStarted:(id)arg1;
-(void)callChangedFromState:(id)arg1 toState:(id)arg2;
-(void)callConnectionStatusChangedFromConnectionStatus:(id)arg1 toConnectionStatus:(id)arg2 forCall:(id)arg3;
-(void)callEnded:(id)arg1 reason:(int)arg2 remoteEnded:(BOOL)arg3 callSummary:(id)arg4;
-(void)callAbortedWithFailedDeviceRequest:(unsigned long long)arg1;
-(void)callTransitionAborted:(id)arg1 withFailedDeviceRequest:(unsigned long long)arg2;
-(void)callUpdatedParticipantsFromState:(id)arg1 toState:(id)arg2;
-(void)callUpdatedLoudestParticipant:(id)arg1;
-(void)callUpdatedPeerUsersInfoFromState:(id)arg1 toState:(id)arg2;

@end

