/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:39 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBAudioSessionManagerClient.h>
#import <Facebook/MNVideoControllerProtocol.h>

@protocol FNFAssetForPlayer;
@class MNVideoPlaybackEventListenerAnnouncer, FNFPlayer, FNFPlayerLayer, FBKVOController, FBVideoNetworker, CALayer, NSString;

@interface MNVideoPlaybackController : NSObject <FBAudioSessionManagerClient, MNVideoControllerProtocol> {

	MNVideoPlaybackEventListenerAnnouncer* _announcer;
	FNFPlayer* _player;
	FNFPlayerLayer* _playerLayer;
	id<FNFAssetForPlayer> _currentAsset;
	FBKVOController* _observation;
	FBVideoNetworker* _networker;
	long long _state;
	double _duration;

}

@property (nonatomic,readonly) BOOL isPlaying; 
@property (nonatomic,readonly) BOOL isPaused; 
@property (nonatomic,readonly) BOOL isPreparing; 
@property (nonatomic,readonly) BOOL isUnprepared; 
@property (nonatomic,readonly) double currentPlaybackTime; 
@property (nonatomic,readonly) double duration;                                        //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) CALayer * layer; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) unsigned long long audioDirection; 
@property (nonatomic,readonly) unsigned long long outputCoordinationMode; 
@property (nonatomic,readonly) unsigned long long outputOptions; 
@property (nonatomic,readonly) unsigned long long inputOptions; 
@property (nonatomic,readonly) unsigned long long clientPriority; 
@property (nonatomic,readonly) unsigned long long audioSessionMode; 
-(void)finishInterruptionAndResume:(BOOL)arg1 ;
-(unsigned long long)audioDirection;
-(unsigned long long)outputCoordinationMode;
-(unsigned long long)outputOptions;
-(id)initWithNetworker:(id)arg1 ;
-(BOOL)isLoadingResources;
-(BOOL)hasLoadedResources;
-(void)_didEndPlaying:(id)arg1 ;
-(void)_didLoadPlayerItem:(id)arg1 ;
-(void)_playAndObserve;
-(void)_playerLayerIsReadyForDisplay;
-(void)_finishPlaying:(id)arg1 ;
-(void)loadAssetResourcesAndPlay:(id)arg1 videoID:(id)arg2 ;
-(BOOL)isUnprepared;
-(CALayer *)layer;
-(void)dealloc;
-(double)duration;
-(void)stop;
-(void)resume;
-(void)pause;
-(void)beginInterruption;
-(BOOL)isPreparing;
-(id)player;
-(double)currentPlaybackTime;
-(void)_playerItemStatusDidChange;
-(BOOL)isPaused;
-(BOOL)isPlaying;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
-(id)playerLayer;
@end

