/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:39:37 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/C3C2BD9F-C9D4-4E48-9EC0-40E7F1350599/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBQueriedActorFieldsProtocol;
@class FBMemModelObject, FBCrowdNoiseDelta;

@interface NotableDeltaAndActor : NSObject {

	FBMemModelObject*<FBQueriedActorFieldsProtocol> _actor;
	FBCrowdNoiseDelta* _delta;

}

@property (nonatomic,retain) FBMemModelObject*<FBQueriedActorFieldsProtocol> actor;              //@synthesize actor=_actor - In the implementation block
@property (nonatomic,retain) FBCrowdNoiseDelta * delta;                                          //@synthesize delta=_delta - In the implementation block
-(FBCrowdNoiseDelta *)delta;
-(void)setDelta:(FBCrowdNoiseDelta *)arg1 ;
-(FBMemModelObject*<FBQueriedActorFieldsProtocol>)actor;
-(void)setActor:(FBMemModelObject*<FBQueriedActorFieldsProtocol>)arg1 ;
@end

