/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:45:09 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/5A964037-04EE-4DC1-9951-0A6265E75908/SportyTrader.app/SportyTrader
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSData;

@interface FBSDKGraphRequestDataAttachment : NSObject {

	NSString* _contentType;
	NSData* _data;
	NSString* _filename;

}

@property (nonatomic,copy,readonly) NSString * contentType;              //@synthesize contentType=_contentType - In the implementation block
@property (nonatomic,readonly) NSData * data;                            //@synthesize data=_data - In the implementation block
@property (nonatomic,copy,readonly) NSString * filename;                 //@synthesize filename=_filename - In the implementation block
-(id)initWithData:(id)arg1 filename:(id)arg2 contentType:(id)arg3 ;
-(id)init;
-(NSData *)data;
-(NSString *)filename;
-(NSString *)contentType;
@end

