/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 1:40:34 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/C946ECFA-6A29-41D3-8F69-02583A041494/Rummikub.app/Rummikub
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@interface FlurryAnalytics : NSObject
+(void)startSession:(id)arg1 ;
+(char)sendUsageInfo;
+(void)setDebugLogEnabled:(char)arg1 ;
+(void)setSessionReportsOnCloseEnabled:(char)arg1 ;
+(void)setSessionReportsOnPauseEnabled:(char)arg1 ;
+(void)setEventLoggingEnabled:(char)arg1 ;
+(void)setUserID:(id)arg1 ;
+(void)createAndSendSession;
+(void)pauseSession;
+(void)resumeSession;
+(void)setLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(float)arg3 verticalAccuracy:(float)arg4 ;
+(void)stopBackgroundTask;
+(void)endTimedEvent:(id)arg1 withParameters:(id)arg2 ;
+(void)setShowErrorInLogEnabled:(char)arg1 ;
+(id)getFlurryAgentVersion;
+(void)setAppCircleEnabled:(char)arg1 ;
+(void)setVideoAdsEnabled:(char)arg1 ;
+(void)setAppSpotEnabled:(char)arg1 ;
+(void)setReEngageEnabled:(char)arg1 ;
+(char)appCircleEnabled;
+(char)videoAdsEnabled;
+(char)appSpotEnabled;
+(char)reEngageEnabled;
+(void)setSessionContinueSeconds:(int)arg1 ;
+(void)setMaxSessionsSaved:(int)arg1 ;
+(void)logEvent:(id)arg1 ;
+(void)logEvent:(id)arg1 withParameters:(id)arg2 ;
+(void)logEvent:(id)arg1 timed:(char)arg2 ;
+(void)logEvent:(id)arg1 withParameters:(id)arg2 timed:(char)arg3 ;
+(void)logError:(id)arg1 message:(id)arg2 exception:(id)arg3 ;
+(void)logError:(id)arg1 message:(id)arg2 error:(id)arg3 ;
+(void)logAllPageViews:(id)arg1 ;
+(void)logPageView;
+(void)setSavedResponseURL:(id)arg1 ;
+(void)setSecureTransportEnabled:(char)arg1 ;
+(char)udidEnabled;
+(id)savedResponseURL;
+(void)setGender:(id)arg1 ;
+(void)endSession;
+(void)setServerURL:(id)arg1 ;
+(id)appVersion;
+(void)setAppVersion:(id)arg1 ;
+(void)setAge:(int)arg1 ;
+(id)serverURL;
@end

