/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:30 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class FBContentInsetTracker, FBExpandableNavigationBar, UIView, UIScrollView;

@interface FBExpandableNavigationRootView : UIView {

	double _expansionVelocityThreshold;
	FBContentInsetTracker* _contentInsetTracker;
	BOOL _isScrollViewConfigured;
	double _prevScrollPosition;
	BOOL _expandAfterScrollingDown;
	BOOL _ignoreScrollEvents;
	long long _expansionState;
	long long _visibilityState;
	BOOL _layoutInProgress;
	BOOL _allowsExpansion;
	BOOL _navigationBarEnabled;
	FBExpandableNavigationBar* _navigationBar;
	UIView* _contentView;
	UIScrollView* _contentScrollView;
	double _navigationBarPercentVisible;
	double _navigationBarHeight;

}

@property (nonatomic,retain) UIView * contentView;                                     //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) UIScrollView * contentScrollView;                         //@synthesize contentScrollView=_contentScrollView - In the implementation block
@property (assign,nonatomic) double navigationBarHeight;                               //@synthesize navigationBarHeight=_navigationBarHeight - In the implementation block
@property (assign,nonatomic) BOOL allowsExpansion;                                     //@synthesize allowsExpansion=_allowsExpansion - In the implementation block
@property (nonatomic,readonly) FBExpandableNavigationBar * navigationBar;              //@synthesize navigationBar=_navigationBar - In the implementation block
@property (assign,getter=isExpanded,nonatomic) BOOL expanded; 
@property (assign,nonatomic) BOOL navigationBarEnabled;                                //@synthesize navigationBarEnabled=_navigationBarEnabled - In the implementation block
@property (assign,nonatomic) double navigationBarPercentVisible;                       //@synthesize navigationBarPercentVisible=_navigationBarPercentVisible - In the implementation block
+(SCD_Struct_FB70)expansionAnimationConfiguration;
-(void)_restoreContentScrollView;
-(void)setExpanded:(BOOL)arg1 animationConfig:(SCD_Struct_FB70)arg2 ;
-(void)setNavigationBarVisible:(BOOL)arg1 animationConfig:(SCD_Struct_FB70)arg2 ;
-(double)navigationBarPercentVisible;
-(void)setNavigationBarPercentVisible:(double)arg1 ;
-(BOOL)_isTransitionAllowed;
-(void)_scrollContentScrollViewByAmount:(double)arg1 withInitialVelocity:(CGPoint)arg2 ;
-(id)initWithNavigationBar:(id)arg1 contentView:(id)arg2 contentScrollView:(id)arg3 ;
-(void)setContentView:(id)arg1 contentScrollView:(id)arg2 ;
-(void)setNavigationBarVisible:(BOOL)arg1 ;
-(void)setNavigationBarEnabled:(BOOL)arg1 ;
-(BOOL)navigationBarEnabled;
-(BOOL)hasFocus;
-(void)setContentView:(UIView *)arg1 ;
-(void)setNeedsLayout;
-(void)layoutSubviews;
-(UIView *)contentView;
-(void)dealloc;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
-(FBExpandableNavigationBar *)navigationBar;
-(UIScrollView *)contentScrollView;
-(BOOL)isExpanded;
-(void)setExpanded:(BOOL)arg1 ;
-(void)viewDidDisappear;
-(void)viewWillAppear;
-(void)viewWillDisappear;
-(void)viewDidAppear;
-(void)setHasFocus:(BOOL)arg1 ;
-(BOOL)allowsExpansion;
-(void)setAllowsExpansion:(BOOL)arg1 ;
-(void)setContentScrollView:(UIScrollView *)arg1 ;
-(double)navigationBarHeight;
-(void)setNavigationBarHeight:(double)arg1 ;
@end

