/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:34 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBImageFilter.h>

@class UIColor, NSString;

@interface FBImageSquareBackgroundFilter : NSObject <FBImageFilter> {

	UIColor* _backgroundColor;
	double _imageSize;
	double _filterSize;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSString * filterID; 
-(id)filterImage:(id)arg1 ;
-(id)initWithBackgroundColor:(id)arg1 imageSize:(double)arg2 filterSize:(double)arg3 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)filterID;
@end

