/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:28 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBQueriedMessageBlobAttachmentFieldsProtocol
@required
-(id)legacyAttachmentId;
-(id)renderAsSticker;
-(long long)playableDurationValue;
-(id)messagingAttribution;
-(id)attributionApp;
-(id)attributionAppScopedIds;
-(id)attributionMetadata;
-(long long)filesizeValue;
-(id)originalDimensions;
-(id)custom_animated_full_screen_image;
-(id)custom_animated_preview_image;
-(BOOL)renderAsStickerValue;
-(BOOL)isVoicemailValue;
-(id)mimetype;
-(id)custom_full_screen_image;
-(id)custom_preview_image;
-(id)originalExtension;
-(id)preview_thumbnail;
-(id)video_filesize;
-(long long)video_filesizeValue;
-(id)filename;
-(id)isVoicemail;
-(id)videoType;
-(id)playableDuration;
-(id)imageType;
-(id)urlString;
-(id)filesize;

@end

