/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:22 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@protocol FBSnapshotViewControllerDelegate;
@class UIView, NSString;

@interface FBSnapshotViewController : UIViewController {

	UIView* _snapshotView;
	NSString* _analyticsModule;
	BOOL _previousStatusBarVisibility;
	long long _previousStatusBarStyle;
	id<FBSnapshotViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBSnapshotViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIView * snapshotView;                                             //@synthesize snapshotView=_snapshotView - In the implementation block
-(id)analyticsModule;
-(BOOL)fb_showAuxiliaryViewController;
-(BOOL)fb_hidesTabBar;
-(BOOL)fb_showNavBarSearchField;
-(BOOL)fb_hidesNavigationBar;
-(id)initWithWindow:(id)arg1 analyticsModule:(id)arg2 ;
-(void)setDelegate:(id<FBSnapshotViewControllerDelegate>)arg1 ;
-(id<FBSnapshotViewControllerDelegate>)delegate;
-(UIView *)snapshotView;
-(long long)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(unsigned long long)supportedInterfaceOrientations;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)setSnapshotView:(UIView *)arg1 ;
@end

