/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:26 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDate;

@interface FBSyncPresence : FBValueObject <NSCopying> {

	NSString* _personId;
	NSDate* _lastActiveTime;
	unsigned long long _presenceState;
	unsigned long long _voipCapabilities;

}

@property (nonatomic,copy,readonly) NSString * personId;                         //@synthesize personId=_personId - In the implementation block
@property (nonatomic,copy,readonly) NSDate * lastActiveTime;                     //@synthesize lastActiveTime=_lastActiveTime - In the implementation block
@property (nonatomic,readonly) unsigned long long presenceState;                 //@synthesize presenceState=_presenceState - In the implementation block
@property (nonatomic,readonly) unsigned long long voipCapabilities;              //@synthesize voipCapabilities=_voipCapabilities - In the implementation block
-(unsigned long long)presenceState;
-(NSDate *)lastActiveTime;
-(unsigned long long)voipCapabilities;
-(id)initWithPersonId:(id)arg1 lastActiveTime:(id)arg2 presenceState:(unsigned long long)arg3 voipCapabilities:(unsigned long long)arg4 ;
-(NSString *)personId;
@end

