/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:14 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBExperimentContext.h>

@class NSString;

@interface FBVideoHomeExperimentContext : FBExperimentContext {

	BOOL _showRecordedLiveLabel;
	BOOL _disableNavigationToDefaultTabPostForegrounding;
	BOOL _enableSound;
	long long _estimatedAveragePrefetchLength;
	BOOL _enableGuideReactionDark;
	BOOL _enableLoadingcardsInLitw;
	NSString* _forcePlayerVersion;
	BOOL _enableVideoTabFeed;
	BOOL _enableBrickStyleFeed;
	BOOL _includeCreatorsYouShouldFollow;
	BOOL _showVideoHomeTab;
	BOOL _showMessengerInNavigationBar;
	BOOL _showLiveCelebritiesUnit;
	BOOL _enableVideoHomeNotifications;
	BOOL _enableVideoPrefetchingInVideoHome;
	long long _topVideosNum;
	long long _latwInitialCount;
	BOOL _useExactThumbnailSize;
	NSString* _rankingSettingsName;
	BOOL _movePageChannelsToMysection;
	NSString* _leftRightSwipingBehaviorV58;
	long long _middleChannelsList;
	long long _badgeCountMax;
	long long _minimumBandwithRequiredForPrefetching;
	BOOL _showTopLivesUnit;
	NSString* _watchedLabelInHscrollsOption;
	BOOL _enableBadgeCountUpdateWithoutData;
	long long _maxConcurrentPrefetchInVideoHome;
	long long _maxVideoPrefetchingDepthForPrefetchedDataInVideoHome;
	BOOL _useOldLatwStyle;
	BOOL _enableStackContainerViewDark;
	long long _connectionBandwidthThresholdKbps;
	long long _searchInVideoHomeStatus;
	BOOL _defaultSoundOn;
	BOOL _showBadgePerVideo;
	BOOL _includeTopicsYouShouldPin;
	BOOL _enableDynamicGrouping;
	BOOL _enableCreatorChannelFeed;
	BOOL _enableVideoPrefetching;
	long long _topChannelsList;
	long long _prefetchDataExpirationIntervalInSeconds;
	BOOL _includeLiveInTheWorld;
	BOOL _enableDenseList;
	NSString* _videoHomeFeedRankingConfig;
	NSString* _vhLiveRankingConfig;
	BOOL _enableDiscoverPrototype;
	BOOL _enableVideoHomeChannel;
	BOOL _includeCreatorsUnit;
	long long _enablePlaceholderData;
	long long _tailCount;
	BOOL _showFeaturedChannelTitle;
	BOOL _allowPageFollow;
	BOOL _enableStackContainerView;
	BOOL _injectCachedVideos;
	NSString* _badgingOption;
	BOOL _includeUnconnected;
	BOOL _enableTopics;
	BOOL _specialEventLiveUnit;
	long long _delayCheckConnectionMs;
	long long _minLatwLiveCountToPrefetch;
	BOOL _enableSoundToggle;
	BOOL _enableHybridDenseListFeed;
	BOOL _requestTopFollowed;
	long long _checkConnectionTimeoutMs;
	NSString* _hscrollLayout;
	BOOL _showSocialContextInSharedChannel;
	long long _staleLimit;
	BOOL _enableCreatorSpace;
	long long _unitsNextPageRequestLimit;
	BOOL _exactVideothumbnailSize;
	long long _maxDepthPrefetchInVideoHome;
	long long _unitComponentsNextPageRequestLimit;
	BOOL _enableLiveNotificationsSwitchToVideoTab;
	BOOL _enableGoLiveHeader;
	BOOL _enableVideoHomeGuide;
	BOOL _enablePrefetching;
	BOOL _disablePrefetch;
	BOOL _enableTabReselectionReload;
	long long _headCount;
	BOOL _enableV2SwipePrototype;
	NSString* _badgingOptionChannelHeader;
	BOOL _requestExperimental;
	BOOL _enableBadgeUpdateSubscription;
	long long _badgeRefetchIntervalInSeconds;
	long long _inVideoHomeExperiment;
	BOOL _loadFeaturedWithOtherSections;
	BOOL _enablePublisherChannelHeader;
	long long _liveVideosCleanupDelay;

}

@property (assign,nonatomic) BOOL showRecordedLiveLabel;                                                  //@synthesize showRecordedLiveLabel=_showRecordedLiveLabel - In the implementation block
@property (assign,nonatomic) BOOL disableNavigationToDefaultTabPostForegrounding;                         //@synthesize disableNavigationToDefaultTabPostForegrounding=_disableNavigationToDefaultTabPostForegrounding - In the implementation block
@property (assign,nonatomic) BOOL enableSound;                                                            //@synthesize enableSound=_enableSound - In the implementation block
@property (assign,nonatomic) long long estimatedAveragePrefetchLength;                                    //@synthesize estimatedAveragePrefetchLength=_estimatedAveragePrefetchLength - In the implementation block
@property (assign,nonatomic) BOOL enableGuideReactionDark;                                                //@synthesize enableGuideReactionDark=_enableGuideReactionDark - In the implementation block
@property (assign,nonatomic) BOOL enableLoadingcardsInLitw;                                               //@synthesize enableLoadingcardsInLitw=_enableLoadingcardsInLitw - In the implementation block
@property (nonatomic,copy) NSString * forcePlayerVersion;                                                 //@synthesize forcePlayerVersion=_forcePlayerVersion - In the implementation block
@property (assign,nonatomic) BOOL enableVideoTabFeed;                                                     //@synthesize enableVideoTabFeed=_enableVideoTabFeed - In the implementation block
@property (assign,nonatomic) BOOL enableBrickStyleFeed;                                                   //@synthesize enableBrickStyleFeed=_enableBrickStyleFeed - In the implementation block
@property (assign,nonatomic) BOOL includeCreatorsYouShouldFollow;                                         //@synthesize includeCreatorsYouShouldFollow=_includeCreatorsYouShouldFollow - In the implementation block
@property (assign,nonatomic) BOOL showVideoHomeTab;                                                       //@synthesize showVideoHomeTab=_showVideoHomeTab - In the implementation block
@property (assign,nonatomic) BOOL showMessengerInNavigationBar;                                           //@synthesize showMessengerInNavigationBar=_showMessengerInNavigationBar - In the implementation block
@property (assign,nonatomic) BOOL showLiveCelebritiesUnit;                                                //@synthesize showLiveCelebritiesUnit=_showLiveCelebritiesUnit - In the implementation block
@property (assign,nonatomic) BOOL enableVideoHomeNotifications;                                           //@synthesize enableVideoHomeNotifications=_enableVideoHomeNotifications - In the implementation block
@property (assign,nonatomic) BOOL enableVideoPrefetchingInVideoHome;                                      //@synthesize enableVideoPrefetchingInVideoHome=_enableVideoPrefetchingInVideoHome - In the implementation block
@property (assign,nonatomic) long long topVideosNum;                                                      //@synthesize topVideosNum=_topVideosNum - In the implementation block
@property (assign,nonatomic) long long latwInitialCount;                                                  //@synthesize latwInitialCount=_latwInitialCount - In the implementation block
@property (assign,nonatomic) BOOL useExactThumbnailSize;                                                  //@synthesize useExactThumbnailSize=_useExactThumbnailSize - In the implementation block
@property (nonatomic,copy) NSString * rankingSettingsName;                                                //@synthesize rankingSettingsName=_rankingSettingsName - In the implementation block
@property (assign,nonatomic) BOOL movePageChannelsToMysection;                                            //@synthesize movePageChannelsToMysection=_movePageChannelsToMysection - In the implementation block
@property (nonatomic,copy) NSString * leftRightSwipingBehaviorV58;                                        //@synthesize leftRightSwipingBehaviorV58=_leftRightSwipingBehaviorV58 - In the implementation block
@property (assign,nonatomic) long long middleChannelsList;                                                //@synthesize middleChannelsList=_middleChannelsList - In the implementation block
@property (assign,nonatomic) long long badgeCountMax;                                                     //@synthesize badgeCountMax=_badgeCountMax - In the implementation block
@property (assign,nonatomic) long long minimumBandwithRequiredForPrefetching;                             //@synthesize minimumBandwithRequiredForPrefetching=_minimumBandwithRequiredForPrefetching - In the implementation block
@property (assign,nonatomic) BOOL showTopLivesUnit;                                                       //@synthesize showTopLivesUnit=_showTopLivesUnit - In the implementation block
@property (nonatomic,copy) NSString * watchedLabelInHscrollsOption;                                       //@synthesize watchedLabelInHscrollsOption=_watchedLabelInHscrollsOption - In the implementation block
@property (assign,nonatomic) BOOL enableBadgeCountUpdateWithoutData;                                      //@synthesize enableBadgeCountUpdateWithoutData=_enableBadgeCountUpdateWithoutData - In the implementation block
@property (assign,nonatomic) long long maxConcurrentPrefetchInVideoHome;                                  //@synthesize maxConcurrentPrefetchInVideoHome=_maxConcurrentPrefetchInVideoHome - In the implementation block
@property (assign,nonatomic) long long maxVideoPrefetchingDepthForPrefetchedDataInVideoHome;              //@synthesize maxVideoPrefetchingDepthForPrefetchedDataInVideoHome=_maxVideoPrefetchingDepthForPrefetchedDataInVideoHome - In the implementation block
@property (assign,nonatomic) BOOL useOldLatwStyle;                                                        //@synthesize useOldLatwStyle=_useOldLatwStyle - In the implementation block
@property (assign,nonatomic) BOOL enableStackContainerViewDark;                                           //@synthesize enableStackContainerViewDark=_enableStackContainerViewDark - In the implementation block
@property (assign,nonatomic) long long connectionBandwidthThresholdKbps;                                  //@synthesize connectionBandwidthThresholdKbps=_connectionBandwidthThresholdKbps - In the implementation block
@property (assign,nonatomic) long long searchInVideoHomeStatus;                                           //@synthesize searchInVideoHomeStatus=_searchInVideoHomeStatus - In the implementation block
@property (assign,nonatomic) BOOL defaultSoundOn;                                                         //@synthesize defaultSoundOn=_defaultSoundOn - In the implementation block
@property (assign,nonatomic) BOOL showBadgePerVideo;                                                      //@synthesize showBadgePerVideo=_showBadgePerVideo - In the implementation block
@property (assign,nonatomic) BOOL includeTopicsYouShouldPin;                                              //@synthesize includeTopicsYouShouldPin=_includeTopicsYouShouldPin - In the implementation block
@property (assign,nonatomic) BOOL enableDynamicGrouping;                                                  //@synthesize enableDynamicGrouping=_enableDynamicGrouping - In the implementation block
@property (assign,nonatomic) BOOL enableCreatorChannelFeed;                                               //@synthesize enableCreatorChannelFeed=_enableCreatorChannelFeed - In the implementation block
@property (assign,nonatomic) BOOL enableVideoPrefetching;                                                 //@synthesize enableVideoPrefetching=_enableVideoPrefetching - In the implementation block
@property (assign,nonatomic) long long topChannelsList;                                                   //@synthesize topChannelsList=_topChannelsList - In the implementation block
@property (assign,nonatomic) long long prefetchDataExpirationIntervalInSeconds;                           //@synthesize prefetchDataExpirationIntervalInSeconds=_prefetchDataExpirationIntervalInSeconds - In the implementation block
@property (assign,nonatomic) BOOL includeLiveInTheWorld;                                                  //@synthesize includeLiveInTheWorld=_includeLiveInTheWorld - In the implementation block
@property (assign,nonatomic) BOOL enableDenseList;                                                        //@synthesize enableDenseList=_enableDenseList - In the implementation block
@property (nonatomic,copy) NSString * videoHomeFeedRankingConfig;                                         //@synthesize videoHomeFeedRankingConfig=_videoHomeFeedRankingConfig - In the implementation block
@property (nonatomic,copy) NSString * vhLiveRankingConfig;                                                //@synthesize vhLiveRankingConfig=_vhLiveRankingConfig - In the implementation block
@property (assign,nonatomic) BOOL enableDiscoverPrototype;                                                //@synthesize enableDiscoverPrototype=_enableDiscoverPrototype - In the implementation block
@property (assign,nonatomic) BOOL enableVideoHomeChannel;                                                 //@synthesize enableVideoHomeChannel=_enableVideoHomeChannel - In the implementation block
@property (assign,nonatomic) BOOL includeCreatorsUnit;                                                    //@synthesize includeCreatorsUnit=_includeCreatorsUnit - In the implementation block
@property (assign,nonatomic) long long enablePlaceholderData;                                             //@synthesize enablePlaceholderData=_enablePlaceholderData - In the implementation block
@property (assign,nonatomic) long long tailCount;                                                         //@synthesize tailCount=_tailCount - In the implementation block
@property (assign,nonatomic) BOOL showFeaturedChannelTitle;                                               //@synthesize showFeaturedChannelTitle=_showFeaturedChannelTitle - In the implementation block
@property (assign,nonatomic) BOOL allowPageFollow;                                                        //@synthesize allowPageFollow=_allowPageFollow - In the implementation block
@property (assign,nonatomic) BOOL enableStackContainerView;                                               //@synthesize enableStackContainerView=_enableStackContainerView - In the implementation block
@property (assign,nonatomic) BOOL injectCachedVideos;                                                     //@synthesize injectCachedVideos=_injectCachedVideos - In the implementation block
@property (nonatomic,copy) NSString * badgingOption;                                                      //@synthesize badgingOption=_badgingOption - In the implementation block
@property (assign,nonatomic) BOOL includeUnconnected;                                                     //@synthesize includeUnconnected=_includeUnconnected - In the implementation block
@property (assign,nonatomic) BOOL enableTopics;                                                           //@synthesize enableTopics=_enableTopics - In the implementation block
@property (assign,nonatomic) BOOL specialEventLiveUnit;                                                   //@synthesize specialEventLiveUnit=_specialEventLiveUnit - In the implementation block
@property (assign,nonatomic) long long delayCheckConnectionMs;                                            //@synthesize delayCheckConnectionMs=_delayCheckConnectionMs - In the implementation block
@property (assign,nonatomic) long long minLatwLiveCountToPrefetch;                                        //@synthesize minLatwLiveCountToPrefetch=_minLatwLiveCountToPrefetch - In the implementation block
@property (assign,nonatomic) BOOL enableSoundToggle;                                                      //@synthesize enableSoundToggle=_enableSoundToggle - In the implementation block
@property (assign,nonatomic) BOOL enableHybridDenseListFeed;                                              //@synthesize enableHybridDenseListFeed=_enableHybridDenseListFeed - In the implementation block
@property (assign,nonatomic) BOOL requestTopFollowed;                                                     //@synthesize requestTopFollowed=_requestTopFollowed - In the implementation block
@property (assign,nonatomic) long long checkConnectionTimeoutMs;                                          //@synthesize checkConnectionTimeoutMs=_checkConnectionTimeoutMs - In the implementation block
@property (nonatomic,copy) NSString * hscrollLayout;                                                      //@synthesize hscrollLayout=_hscrollLayout - In the implementation block
@property (assign,nonatomic) BOOL showSocialContextInSharedChannel;                                       //@synthesize showSocialContextInSharedChannel=_showSocialContextInSharedChannel - In the implementation block
@property (assign,nonatomic) long long staleLimit;                                                        //@synthesize staleLimit=_staleLimit - In the implementation block
@property (assign,nonatomic) BOOL enableCreatorSpace;                                                     //@synthesize enableCreatorSpace=_enableCreatorSpace - In the implementation block
@property (assign,nonatomic) long long unitsNextPageRequestLimit;                                         //@synthesize unitsNextPageRequestLimit=_unitsNextPageRequestLimit - In the implementation block
@property (assign,nonatomic) BOOL exactVideothumbnailSize;                                                //@synthesize exactVideothumbnailSize=_exactVideothumbnailSize - In the implementation block
@property (assign,nonatomic) long long maxDepthPrefetchInVideoHome;                                       //@synthesize maxDepthPrefetchInVideoHome=_maxDepthPrefetchInVideoHome - In the implementation block
@property (assign,nonatomic) long long unitComponentsNextPageRequestLimit;                                //@synthesize unitComponentsNextPageRequestLimit=_unitComponentsNextPageRequestLimit - In the implementation block
@property (assign,nonatomic) BOOL enableLiveNotificationsSwitchToVideoTab;                                //@synthesize enableLiveNotificationsSwitchToVideoTab=_enableLiveNotificationsSwitchToVideoTab - In the implementation block
@property (assign,nonatomic) BOOL enableGoLiveHeader;                                                     //@synthesize enableGoLiveHeader=_enableGoLiveHeader - In the implementation block
@property (assign,nonatomic) BOOL enableVideoHomeGuide;                                                   //@synthesize enableVideoHomeGuide=_enableVideoHomeGuide - In the implementation block
@property (assign,nonatomic) BOOL enablePrefetching;                                                      //@synthesize enablePrefetching=_enablePrefetching - In the implementation block
@property (assign,nonatomic) BOOL disablePrefetch;                                                        //@synthesize disablePrefetch=_disablePrefetch - In the implementation block
@property (assign,nonatomic) BOOL enableTabReselectionReload;                                             //@synthesize enableTabReselectionReload=_enableTabReselectionReload - In the implementation block
@property (assign,nonatomic) long long headCount;                                                         //@synthesize headCount=_headCount - In the implementation block
@property (assign,nonatomic) BOOL enableV2SwipePrototype;                                                 //@synthesize enableV2SwipePrototype=_enableV2SwipePrototype - In the implementation block
@property (nonatomic,copy) NSString * badgingOptionChannelHeader;                                         //@synthesize badgingOptionChannelHeader=_badgingOptionChannelHeader - In the implementation block
@property (assign,nonatomic) BOOL requestExperimental;                                                    //@synthesize requestExperimental=_requestExperimental - In the implementation block
@property (assign,nonatomic) BOOL enableBadgeUpdateSubscription;                                          //@synthesize enableBadgeUpdateSubscription=_enableBadgeUpdateSubscription - In the implementation block
@property (assign,nonatomic) long long badgeRefetchIntervalInSeconds;                                     //@synthesize badgeRefetchIntervalInSeconds=_badgeRefetchIntervalInSeconds - In the implementation block
@property (assign,nonatomic) long long inVideoHomeExperiment;                                             //@synthesize inVideoHomeExperiment=_inVideoHomeExperiment - In the implementation block
@property (assign,nonatomic) BOOL loadFeaturedWithOtherSections;                                          //@synthesize loadFeaturedWithOtherSections=_loadFeaturedWithOtherSections - In the implementation block
@property (assign,nonatomic) BOOL enablePublisherChannelHeader;                                           //@synthesize enablePublisherChannelHeader=_enablePublisherChannelHeader - In the implementation block
@property (assign,nonatomic) long long liveVideosCleanupDelay;                                            //@synthesize liveVideosCleanupDelay=_liveVideosCleanupDelay - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(BOOL)allowPageFollow;
-(long long)badgeCountMax;
-(long long)badgeRefetchIntervalInSeconds;
-(NSString *)badgingOption;
-(NSString *)badgingOptionChannelHeader;
-(long long)checkConnectionTimeoutMs;
-(long long)connectionBandwidthThresholdKbps;
-(BOOL)defaultSoundOn;
-(long long)delayCheckConnectionMs;
-(BOOL)disableNavigationToDefaultTabPostForegrounding;
-(BOOL)disablePrefetch;
-(BOOL)enableBadgeCountUpdateWithoutData;
-(BOOL)enableBadgeUpdateSubscription;
-(BOOL)enableBrickStyleFeed;
-(BOOL)enableCreatorChannelFeed;
-(BOOL)enableCreatorSpace;
-(BOOL)enableDenseList;
-(BOOL)enableDiscoverPrototype;
-(BOOL)enableDynamicGrouping;
-(BOOL)enableGoLiveHeader;
-(BOOL)enableGuideReactionDark;
-(BOOL)enableHybridDenseListFeed;
-(BOOL)enableLiveNotificationsSwitchToVideoTab;
-(BOOL)enableLoadingcardsInLitw;
-(long long)enablePlaceholderData;
-(BOOL)enablePrefetching;
-(BOOL)enablePublisherChannelHeader;
-(BOOL)enableSound;
-(BOOL)enableSoundToggle;
-(BOOL)enableStackContainerView;
-(BOOL)enableStackContainerViewDark;
-(BOOL)enableTabReselectionReload;
-(BOOL)enableTopics;
-(BOOL)enableV2SwipePrototype;
-(BOOL)enableVideoHomeChannel;
-(BOOL)enableVideoHomeGuide;
-(BOOL)enableVideoHomeNotifications;
-(BOOL)enableVideoPrefetching;
-(BOOL)enableVideoPrefetchingInVideoHome;
-(BOOL)enableVideoTabFeed;
-(long long)estimatedAveragePrefetchLength;
-(BOOL)exactVideothumbnailSize;
-(NSString *)forcePlayerVersion;
-(long long)headCount;
-(NSString *)hscrollLayout;
-(long long)inVideoHomeExperiment;
-(BOOL)includeCreatorsUnit;
-(BOOL)includeCreatorsYouShouldFollow;
-(BOOL)includeLiveInTheWorld;
-(BOOL)includeTopicsYouShouldPin;
-(BOOL)includeUnconnected;
-(BOOL)injectCachedVideos;
-(long long)latwInitialCount;
-(NSString *)leftRightSwipingBehaviorV58;
-(long long)liveVideosCleanupDelay;
-(BOOL)loadFeaturedWithOtherSections;
-(long long)maxConcurrentPrefetchInVideoHome;
-(long long)maxDepthPrefetchInVideoHome;
-(long long)maxVideoPrefetchingDepthForPrefetchedDataInVideoHome;
-(long long)middleChannelsList;
-(long long)minLatwLiveCountToPrefetch;
-(long long)minimumBandwithRequiredForPrefetching;
-(BOOL)movePageChannelsToMysection;
-(long long)prefetchDataExpirationIntervalInSeconds;
-(NSString *)rankingSettingsName;
-(BOOL)requestExperimental;
-(BOOL)requestTopFollowed;
-(long long)searchInVideoHomeStatus;
-(BOOL)showBadgePerVideo;
-(BOOL)showFeaturedChannelTitle;
-(BOOL)showLiveCelebritiesUnit;
-(BOOL)showMessengerInNavigationBar;
-(BOOL)showRecordedLiveLabel;
-(BOOL)showSocialContextInSharedChannel;
-(BOOL)showTopLivesUnit;
-(BOOL)showVideoHomeTab;
-(BOOL)specialEventLiveUnit;
-(long long)staleLimit;
-(long long)tailCount;
-(long long)topChannelsList;
-(long long)topVideosNum;
-(long long)unitComponentsNextPageRequestLimit;
-(long long)unitsNextPageRequestLimit;
-(BOOL)useExactThumbnailSize;
-(BOOL)useOldLatwStyle;
-(NSString *)vhLiveRankingConfig;
-(NSString *)videoHomeFeedRankingConfig;
-(NSString *)watchedLabelInHscrollsOption;
-(void)setShowRecordedLiveLabel:(BOOL)arg1 ;
-(void)setDisableNavigationToDefaultTabPostForegrounding:(BOOL)arg1 ;
-(void)setEnableSound:(BOOL)arg1 ;
-(void)setEstimatedAveragePrefetchLength:(long long)arg1 ;
-(void)setEnableGuideReactionDark:(BOOL)arg1 ;
-(void)setEnableLoadingcardsInLitw:(BOOL)arg1 ;
-(void)setForcePlayerVersion:(NSString *)arg1 ;
-(void)setEnableVideoTabFeed:(BOOL)arg1 ;
-(void)setEnableBrickStyleFeed:(BOOL)arg1 ;
-(void)setIncludeCreatorsYouShouldFollow:(BOOL)arg1 ;
-(void)setShowVideoHomeTab:(BOOL)arg1 ;
-(void)setShowMessengerInNavigationBar:(BOOL)arg1 ;
-(void)setShowLiveCelebritiesUnit:(BOOL)arg1 ;
-(void)setEnableVideoHomeNotifications:(BOOL)arg1 ;
-(void)setEnableVideoPrefetchingInVideoHome:(BOOL)arg1 ;
-(void)setTopVideosNum:(long long)arg1 ;
-(void)setLatwInitialCount:(long long)arg1 ;
-(void)setUseExactThumbnailSize:(BOOL)arg1 ;
-(void)setRankingSettingsName:(NSString *)arg1 ;
-(void)setMovePageChannelsToMysection:(BOOL)arg1 ;
-(void)setLeftRightSwipingBehaviorV58:(NSString *)arg1 ;
-(void)setMiddleChannelsList:(long long)arg1 ;
-(void)setBadgeCountMax:(long long)arg1 ;
-(void)setMinimumBandwithRequiredForPrefetching:(long long)arg1 ;
-(void)setShowTopLivesUnit:(BOOL)arg1 ;
-(void)setWatchedLabelInHscrollsOption:(NSString *)arg1 ;
-(void)setEnableBadgeCountUpdateWithoutData:(BOOL)arg1 ;
-(void)setMaxConcurrentPrefetchInVideoHome:(long long)arg1 ;
-(void)setMaxVideoPrefetchingDepthForPrefetchedDataInVideoHome:(long long)arg1 ;
-(void)setUseOldLatwStyle:(BOOL)arg1 ;
-(void)setEnableStackContainerViewDark:(BOOL)arg1 ;
-(void)setConnectionBandwidthThresholdKbps:(long long)arg1 ;
-(void)setSearchInVideoHomeStatus:(long long)arg1 ;
-(void)setDefaultSoundOn:(BOOL)arg1 ;
-(void)setShowBadgePerVideo:(BOOL)arg1 ;
-(void)setIncludeTopicsYouShouldPin:(BOOL)arg1 ;
-(void)setEnableDynamicGrouping:(BOOL)arg1 ;
-(void)setEnableCreatorChannelFeed:(BOOL)arg1 ;
-(void)setEnableVideoPrefetching:(BOOL)arg1 ;
-(void)setTopChannelsList:(long long)arg1 ;
-(void)setPrefetchDataExpirationIntervalInSeconds:(long long)arg1 ;
-(void)setIncludeLiveInTheWorld:(BOOL)arg1 ;
-(void)setEnableDenseList:(BOOL)arg1 ;
-(void)setVideoHomeFeedRankingConfig:(NSString *)arg1 ;
-(void)setVhLiveRankingConfig:(NSString *)arg1 ;
-(void)setEnableDiscoverPrototype:(BOOL)arg1 ;
-(void)setEnableVideoHomeChannel:(BOOL)arg1 ;
-(void)setIncludeCreatorsUnit:(BOOL)arg1 ;
-(void)setEnablePlaceholderData:(long long)arg1 ;
-(void)setTailCount:(long long)arg1 ;
-(void)setShowFeaturedChannelTitle:(BOOL)arg1 ;
-(void)setAllowPageFollow:(BOOL)arg1 ;
-(void)setEnableStackContainerView:(BOOL)arg1 ;
-(void)setInjectCachedVideos:(BOOL)arg1 ;
-(void)setBadgingOption:(NSString *)arg1 ;
-(void)setIncludeUnconnected:(BOOL)arg1 ;
-(void)setEnableTopics:(BOOL)arg1 ;
-(void)setSpecialEventLiveUnit:(BOOL)arg1 ;
-(void)setDelayCheckConnectionMs:(long long)arg1 ;
-(void)setMinLatwLiveCountToPrefetch:(long long)arg1 ;
-(void)setEnableSoundToggle:(BOOL)arg1 ;
-(void)setEnableHybridDenseListFeed:(BOOL)arg1 ;
-(void)setRequestTopFollowed:(BOOL)arg1 ;
-(void)setCheckConnectionTimeoutMs:(long long)arg1 ;
-(void)setHscrollLayout:(NSString *)arg1 ;
-(void)setShowSocialContextInSharedChannel:(BOOL)arg1 ;
-(void)setStaleLimit:(long long)arg1 ;
-(void)setEnableCreatorSpace:(BOOL)arg1 ;
-(void)setUnitsNextPageRequestLimit:(long long)arg1 ;
-(void)setExactVideothumbnailSize:(BOOL)arg1 ;
-(void)setMaxDepthPrefetchInVideoHome:(long long)arg1 ;
-(void)setUnitComponentsNextPageRequestLimit:(long long)arg1 ;
-(void)setEnableLiveNotificationsSwitchToVideoTab:(BOOL)arg1 ;
-(void)setEnableGoLiveHeader:(BOOL)arg1 ;
-(void)setEnableVideoHomeGuide:(BOOL)arg1 ;
-(void)setEnablePrefetching:(BOOL)arg1 ;
-(void)setDisablePrefetch:(BOOL)arg1 ;
-(void)setEnableTabReselectionReload:(BOOL)arg1 ;
-(void)setHeadCount:(long long)arg1 ;
-(void)setEnableV2SwipePrototype:(BOOL)arg1 ;
-(void)setBadgingOptionChannelHeader:(NSString *)arg1 ;
-(void)setRequestExperimental:(BOOL)arg1 ;
-(void)setEnableBadgeUpdateSubscription:(BOOL)arg1 ;
-(void)setBadgeRefetchIntervalInSeconds:(long long)arg1 ;
-(void)setInVideoHomeExperiment:(long long)arg1 ;
-(void)setLoadFeaturedWithOtherSections:(BOOL)arg1 ;
-(void)setEnablePublisherChannelHeader:(BOOL)arg1 ;
-(void)setLiveVideosCleanupDelay:(long long)arg1 ;
@end

