/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:20 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol FBWebAppActionViewDelegate;
@class UIButton, UILabel, UIImageView, UIView;

@interface FBWebAppActionView : UIView {

	UIButton* _actionButton;
	UIButton* _dismissButton;
	UILabel* _subtitleLabel;
	UIImageView* _imageView;
	UIView* _bottomSeparator;
	id<FBWebAppActionViewDelegate> _delegate;
	UILabel* _titleLabel;

}

@property (nonatomic,retain) UILabel * titleLabel;                                        //@synthesize titleLabel=_titleLabel - In the implementation block
@property (assign,nonatomic,__weak) id<FBWebAppActionViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(double)defaultHeight;
-(void)_didTapActionButton:(id)arg1 ;
-(void)_didTapDismissButton:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 titleLabel:(id)arg2 buttonLabel:(id)arg3 style:(unsigned long long)arg4 ;
-(double)_separatorThickness;
-(id)initWithFrame:(CGRect)arg1 titleLabel:(id)arg2 subtitleLabel:(id)arg3 buttonLabel:(id)arg4 icon:(id)arg5 style:(unsigned long long)arg6 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<FBWebAppActionViewDelegate>)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<FBWebAppActionViewDelegate>)delegate;
-(UILabel *)titleLabel;
-(void)setTitleLabel:(UILabel *)arg1 ;
@end

