/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:18 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBViewerContextClassProvidable.h>
#import <Messenger/MNComposerControlExtension.h>

@class MNComposerControlExtensionStateListenerAnnouncer, MNComposerControlExtensionIconViewModel, FBLazyCreator, MNComposerControlExtensionBannerViewModel, NSString;

@interface MNComposerEphemeralControlExtension : NSObject <FBViewerContextClassProvidable, MNComposerControlExtension> {

	MNComposerControlExtensionStateListenerAnnouncer* _announcer;
	MNComposerControlExtensionIconViewModel* _iconViewModel;
	FBLazyCreator* _soundControllerCreator;
	BOOL _ephemeralModeEnabled;
	MNComposerControlExtensionBannerViewModel* _bannerViewModel;
	long long _messageLifetimeInMs;

}

@property (assign,nonatomic) long long messageLifetimeInMs;                                                   //@synthesize messageLifetimeInMs=_messageLifetimeInMs - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (getter=isEnabled,nonatomic,readonly) BOOL enabled;                                                 //@synthesize ephemeralModeEnabled=_ephemeralModeEnabled - In the implementation block
@property (nonatomic,copy,readonly) MNComposerControlExtensionBannerViewModel * bannerViewModel;              //@synthesize bannerViewModel=_bannerViewModel - In the implementation block
-(id)initWithProviderMapData:(id)arg1 ;
-(void)setEnabled:(BOOL)arg1 source:(id)arg2 ;
-(void)setMessageLifetimeInMs:(long long)arg1 ;
-(long long)messageLifetimeInMs;
-(id)initWithSoundController:(id)arg1 ;
-(id)newIconActionHandler;
-(id)iconViewModel;
-(MNComposerControlExtensionBannerViewModel *)bannerViewModel;
-(void)controlExtensionDidPressIcon;
-(BOOL)isEnabled;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
@end

