/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:20 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNMessageLocalNotificationBuzzHistoryReading.h>
#import <Messenger/MNMessageLocalNotificationBuzzHistoryRecording.h>

@protocol OS_dispatch_queue;
@class FBCache, NSObject, NSString;

@interface MNMessageLocalNotificationBuzzHistoryStore : NSObject <MNMessageLocalNotificationBuzzHistoryReading, MNMessageLocalNotificationBuzzHistoryRecording> {

	FBCache* _cache;
	long long _maxHistoryPerThread;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)buzzHistoryForThreadKey:(id)arg1 ;
-(void)recordBuzzHistory:(id)arg1 ;
-(id)initWithCache:(id)arg1 maxHistoryPerThread:(long long)arg2 queue:(id)arg3 ;
@end

