/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:16 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIActionSheetDelegate.h>
#import <Messenger/FBClassProvidable.h>

@protocol MNOmniMRidesPrefSettingControllerDelegate;
@class MNOmniMSettingsStore, UIActionSheet, NSString;

@interface MNOmniMRidesPrefSettingController : NSObject <UIActionSheetDelegate, FBClassProvidable> {

	MNOmniMSettingsStore* _omniMSettingsStore;
	UIActionSheet* _changeRidesPrefSettingActionSheet;
	long long _noneButtonIndex;
	long long _uberButtonIndex;
	long long _lyftButtonIndex;
	id<MNOmniMRidesPrefSettingControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNOmniMRidesPrefSettingControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)currentRidesPrefString;
-(void)omniMRidesPrefCellTappedWithActionSheetPresentationView:(id)arg1 fromSourceView:(id)arg2 ;
-(void)setDelegate:(id<MNOmniMRidesPrefSettingControllerDelegate>)arg1 ;
-(id<MNOmniMRidesPrefSettingControllerDelegate>)delegate;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2 ;
@end

