/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:21 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Messenger/MNPeopleSearchControllerDelegate.h>
#import <Messenger/MNPeopleSearchControllerActionButtonDelegate.h>
#import <Messenger/FBClassProvidable.h>

@protocol MNViewPreviewingHandling, MNLegacySyncEngineManaging, MNPeopleSearchViewControllerDelegate;
@class MNPeopleSearchController, MNPeopleSearchView, MNPeopleSearchAccessibilityController, MNPeopleCellActionButtonsStateCoordinator, UITableView, NSString;

@interface MNPeopleSearchViewController : UIViewController <MNPeopleSearchControllerDelegate, MNPeopleSearchControllerActionButtonDelegate, FBClassProvidable> {

	MNPeopleSearchController* _peopleSearchController;
	MNPeopleSearchView* _peopleSearchView;
	MNPeopleSearchAccessibilityController* _peopleSearchAccessibilityController;
	id<MNViewPreviewingHandling> _viewPreviewingHandler;
	id<MNLegacySyncEngineManaging> _DEPRECATED_legacySyncEngineManager;
	id<MNPeopleSearchViewControllerDelegate> _delegate;
	MNPeopleCellActionButtonsStateCoordinator* _peopleCellActionButtonsStateCoordinator;

}

@property (assign,nonatomic,__weak) id<MNPeopleSearchViewControllerDelegate> delegate;                                         //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UITableView * searchResultsTableView; 
@property (nonatomic,readonly) MNPeopleSearchController * peopleSearchController;                                              //@synthesize peopleSearchController=_peopleSearchController - In the implementation block
@property (nonatomic,retain) MNPeopleCellActionButtonsStateCoordinator * peopleCellActionButtonsStateCoordinator;              //@synthesize peopleCellActionButtonsStateCoordinator=_peopleCellActionButtonsStateCoordinator - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)analyticsModule;
-(void)addScrollingListener:(id)arg1 ;
-(void)_registerForPreviewing;
-(void)configureWithPeopleCellStyle:(id)arg1 ;
-(void)endSearchSession;
-(void)startSearch;
-(void)startSearchSession;
-(BOOL)peopleSearchControllerShouldIncludeGroup:(id)arg1 ;
-(BOOL)peopleSearchControllerShouldIncludeAddressBookContacts:(id)arg1 ;
-(unsigned long long)peopleSearchControllerPageFilterRule:(id)arg1 ;
-(BOOL)peopleSearchControllerShouldIncludeBlendedResults:(id)arg1 ;
-(BOOL)peopleSearchControllerShouldIncludeNicknameResults:(id)arg1 ;
-(id)searchTextForPeopleSearchController:(id)arg1 ;
-(id)pickedUserIdsForPeopleSearchController:(id)arg1 ;
-(void)peopleSearchControllerDidFinishSearch:(id)arg1 ;
-(BOOL)peopleSearchController:(id)arg1 shouldSelectResultWhenTapped:(id)arg2 ;
-(void)peopleSearchController:(id)arg1 didSelectResult:(id)arg2 withAnalyticsExtras:(id)arg3 ;
-(BOOL)peopleSearchController:(id)arg1 shouldShowResult:(id)arg2 ;
-(BOOL)peopleSearchControllerShouldSearchServer:(id)arg1 ;
-(unsigned long long)surfaceForPeopleSearchSession;
-(void)peopleSearchControllerSyncStoreDidChange:(id)arg1 ;
-(MNPeopleSearchController *)peopleSearchController;
-(void)removeScrollingListener:(id)arg1 ;
-(void)peopleSearchController:(id)arg1 didTapActionButtonForContact:(id)arg2 ;
-(void)_updateLoadingState;
-(void)setPeopleCellActionButtonsStateCoordinator:(MNPeopleCellActionButtonsStateCoordinator *)arg1 ;
-(MNPeopleCellActionButtonsStateCoordinator *)peopleCellActionButtonsStateCoordinator;
-(BOOL)_shouldShowLoading;
-(void)setDelegate:(id<MNPeopleSearchViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<MNPeopleSearchViewControllerDelegate>)delegate;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(UITableView *)searchResultsTableView;
-(void)cancelSearch;
@end

