/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:14 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBExperimentContext.h>

@class NSString;

@interface TODOFBFeedStoryAlbumCTAExperimentContext : FBExperimentContext {

	NSString* _feed_story_album_cta_button_title_photos;
	NSString* _feed_story_album_cta_description;
	NSString* _feed_story_album_cta_button_title_photos_videos;
	BOOL _feed_story_album_cta_enable_add_to_own_album_cta;

}

@property (nonatomic,copy) NSString * feed_story_album_cta_button_title_photos;                     //@synthesize feed_story_album_cta_button_title_photos=_feed_story_album_cta_button_title_photos - In the implementation block
@property (nonatomic,copy) NSString * feed_story_album_cta_description;                             //@synthesize feed_story_album_cta_description=_feed_story_album_cta_description - In the implementation block
@property (nonatomic,copy) NSString * feed_story_album_cta_button_title_photos_videos;              //@synthesize feed_story_album_cta_button_title_photos_videos=_feed_story_album_cta_button_title_photos_videos - In the implementation block
@property (assign,nonatomic) BOOL feed_story_album_cta_enable_add_to_own_album_cta;                 //@synthesize feed_story_album_cta_enable_add_to_own_album_cta=_feed_story_album_cta_enable_add_to_own_album_cta - In the implementation block
+(id)universeName;
+(id)parameterConfigurations;
+(unsigned)mobileconfigConfigSpecifier;
+(id)configurationName;
-(void)logExposure;
-(NSString *)feed_story_album_cta_button_title_photos;
-(NSString *)feed_story_album_cta_button_title_photos_videos;
-(NSString *)feed_story_album_cta_description;
-(BOOL)feed_story_album_cta_enable_add_to_own_album_cta;
-(void)setFeed_story_album_cta_button_title_photos:(NSString *)arg1 ;
-(void)setFeed_story_album_cta_description:(NSString *)arg1 ;
-(void)setFeed_story_album_cta_button_title_photos_videos:(NSString *)arg1 ;
-(void)setFeed_story_album_cta_enable_add_to_own_album_cta:(BOOL)arg1 ;
@end

