/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:29:36 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/85513C16-EFBE-4673-84DA-B31CD22289F8/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/ZZChannelOutput.h>

@interface ZZFileChannelOutput : NSObject <ZZChannelOutput> {

	int _fileDescriptor;
	unsigned _offset;

}

@property (assign,nonatomic) unsigned offset;              //@synthesize offset=_offset - In the implementation block
-(BOOL)seekToOffset:(unsigned)arg1 error:(out id*)arg2 ;
-(BOOL)truncateAtOffset:(unsigned)arg1 error:(out id*)arg2 ;
-(void)setOffset:(unsigned)arg1 ;
-(unsigned)offset;
-(void)close;
-(BOOL)writeData:(id)arg1 error:(out id*)arg2 ;
-(id)initWithFileDescriptor:(int)arg1 ;
@end

