/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:37 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBCommonAnimations : NSObject
+(id)springySingleBounceScaleAnimationWithDelay:(double)arg1 springiness:(double)arg2 ;
+(id)singleBounceScaleAnimation;
+(id)backgroundFadeOutAnimationWithColor:(id)arg1 ;
+(id)fadeInAnimation;
+(id)fadeOutAnimation;
+(id)slideUpAnimation;
+(id)slideDownAnimation;
+(id)scaleToAppearAnimation;
+(id)scaleToDisappearAnimationWithDuration:(double)arg1 endScaleValue:(double)arg2 ;
+(id)largeBounceTranslateAnimation;
+(id)springySingleBounceScaleAnimation;
+(id)singleBounceTranslateAnimation;
+(id)tripleBounceScaleAnimation;
+(id)scaleToDisappearAnimation;
+(id)iconTappedAnimationWithTransformValues:(id)arg1 ;
@end

