/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:22 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBPillView.h>

@class UIImageView;

@interface FBFeedNewStoriesPillView : FBPillView {

	UIImageView* _leftImageView;
	unsigned long long _unreadCount;

}

@property (assign,nonatomic) unsigned long long unreadCount;              //@synthesize unreadCount=_unreadCount - In the implementation block
-(id)messageToDisplay;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setUnreadCount:(unsigned long long)arg1 ;
-(unsigned long long)unreadCount;
@end

