/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:30 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>
#import <Messenger/FBNuxPromotionFooterViewProtocol.h>

@class UILabel, UIButton, FBUserSession, FBNetworkImageView, UIImageView;

@interface FBNuxPromotionFooterView : UIView <FBNuxPromotionFooterViewProtocol> {

	FBUserSession* _session;
	CGSize _dismissButtonSize;
	CGSize _imageSize;
	CGSize _titleLabelSize;
	CGSize _descriptionLabelSize;
	CGSize _buttonSize;
	UIButton* _dismissButton;
	UIButton* _primaryButton;
	UILabel* _descriptionLabel;
	UILabel* _titleLabel;
	FBNetworkImageView* _networkImageView;
	UIImageView* _imageView;

}

@property (nonatomic,retain) FBNetworkImageView * networkImageView;              //@synthesize networkImageView=_networkImageView - In the implementation block
@property (nonatomic,retain) UIImageView * imageView;                            //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,readonly) UILabel * titleLabel;                             //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,readonly) UILabel * descriptionLabel;                       //@synthesize descriptionLabel=_descriptionLabel - In the implementation block
@property (nonatomic,readonly) UIButton * primaryButton;                         //@synthesize primaryButton=_primaryButton - In the implementation block
@property (nonatomic,readonly) UIButton * dismissButton;                         //@synthesize dismissButton=_dismissButton - In the implementation block
-(id)initWithFrame:(CGRect)arg1 session:(id)arg2 ;
-(FBNetworkImageView *)networkImageView;
-(UIButton *)primaryButton;
-(void)setNetworkImageView:(FBNetworkImageView *)arg1 ;
-(void)unsetImage;
-(id)_animatedImageViewFromURL:(id)arg1 size:(CGSize)arg2 scale:(double)arg3 ;
-(CGRect)_calculateImageFrameForSize:(CGSize)arg1 scale:(double)arg2 ;
-(void)setAnimatedImageWithURL:(id)arg1 size:(CGSize)arg2 scale:(double)arg3 ;
-(id)_networkImageViewFromURL:(id)arg1 size:(CGSize)arg2 scale:(double)arg3 ;
-(void)setImageWithURL:(id)arg1 size:(CGSize)arg2 scale:(double)arg3 ;
-(id)initWithFrame:(CGRect)arg1 session:(id)arg2 buttonStyle:(unsigned long long)arg3 ;
-(void)setImage:(id)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(UILabel *)titleLabel;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(UIButton *)dismissButton;
-(UILabel *)descriptionLabel;
@end

