/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:35 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBAPISessionStoreFactory, OS_dispatch_queue;
#import <Messenger/Messenger-Structs.h>
@class FBProviderScopedObjectRegister, NSNotificationCenter, NSObject, FBKVOController, FBUserSession, FBAPISessionStore, NSString;

@interface FBSessionController : NSObject {

	id<FBAPISessionStoreFactory> _APISessionStoreFactory;
	FBProviderScopedObjectRegister* _scopedObjectRegister;
	NSNotificationCenter* _notificationCenter;
	/*^block*/id _initialization;
	NSObject*<OS_dispatch_queue> _apiSessionStoreReloadQueue;
	FBKVOController* _kvoController;
	recursive_mutex _sessionMutex;
	FBUserSession* _session;
	mutex _apiSessionStoreMutex;
	FBAPISessionStore* _apiSessionStore;
	NSString* _storeIdentifier;

}

@property (nonatomic,copy,readonly) NSString * storeIdentifier;                  //@synthesize storeIdentifier=_storeIdentifier - In the implementation block
@property (nonatomic,readonly) FBAPISessionStore * apiSessionStore; 
@property (nonatomic,readonly) FBUserSession * session; 
-(id)initWithAppSecret:(id)arg1 scopedObjectRegister:(id)arg2 initialization:(/*^block*/id)arg3 appGroup:(id)arg4 keychainBackupPolicy:(unsigned long long)arg5 ;
-(void)resetSession;
-(FBAPISessionStore *)apiSessionStore;
-(id)initWithAPISessionStoreFactory:(id)arg1 scopedObjectRegister:(id)arg2 notificationCenter:(id)arg3 initialization:(/*^block*/id)arg4 ;
-(void)_onProtectedDataAvailable:(id)arg1 ;
-(void)_loggedInUserFBIDDidChange;
-(id)_buildInitialSession;
-(void)_updatedUser;
-(id)initWithAppSecret:(id)arg1 scopedObjectRegister:(id)arg2 ;
-(id)initWithAPISessionStoreFactory:(id)arg1 scopedObjectRegister:(id)arg2 ;
-(void)dealloc;
-(NSString *)storeIdentifier;
-(FBUserSession *)session;
@end

