/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:31 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBExperimentManagerPolicy.h>

@protocol OS_dispatch_queue;
@class FBExperimentDebugHelper, FBUserSession, NSObject, NSString;

@interface FBSessionExperimentManagerPolicy : NSObject <FBExperimentManagerPolicy> {

	FBExperimentDebugHelper* _debugHelper;
	BOOL _includeAllGroupsAndParameters;
	FBUserSession* _session;
	NSObject*<OS_dispatch_queue> _persistenceQueue;
	BOOL _isEmployee;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)isEmployee;
-(id)allExperimentsInCatalogAsShortDescription;
-(void)setupDebugHelperWithExperimentCatalog:(id)arg1 debugInfoProvider:(id)arg2 ;
-(id)plistKey;
-(void)fetchWithExperimentCatalog:(id)arg1 withCompletionBlock:(/*^block*/id)arg2 withAllGroupsAndParameters:(BOOL)arg3 scenePath:(id)arg4 ;
-(double)expirationTimeIntervalInSeconds;
-(id)gatekeepers;
-(BOOL)sessionless;
-(void)loadExperiments:(/*^block*/id)arg1 ;
-(void)persistExperiments:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)loadOverrides:(/*^block*/id)arg1 ;
-(void)persistOverrides:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)initWithSession:(id)arg1 ;
-(id)keyValueStore;
@end

