/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:29 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSMutableArray, FBPersistentCache;

@interface FBTempAssetsManager : NSObject {

	NSMutableDictionary* _tempURLToTempAsset;
	NSMutableDictionary* _realAssetURLToTempURL;
	NSMutableArray* _tempAssets;
	FBPersistentCache* _tempURLToAssetURLCache;

}
+(id)sharedInstance;
-(id)assetURLForFetchingFromAssetURL:(id)arg1 ;
-(id)tempAssetURLFromAssetURL:(id)arg1 ;
-(id)createTempAssetFromUIImage:(id)arg1 onAssetsList:(id)arg2 ;
-(void)setRealAssetURL:(id)arg1 forTempAssetURL:(id)arg2 ;
-(void)releaseInMemoryAssetsForRealAssets:(id)arg1 ;
-(id)createTempAssetFromVideo:(id)arg1 onAssetsList:(id)arg2 ;
-(void)removeAllTempAssetsFromAssetList:(id)arg1 ;
-(id)assetsListAfterInjectingTempAssets:(id)arg1 filter:(unsigned long long)arg2 ;
-(id)assetForURL:(id)arg1 ;
-(id)init;
@end

