/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:20 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class FBWebRTCPhotoCircleView, UILabel, FBMUserName, FBWebRTCCircleAudioLevelView, MNProfileImageView;

@interface FBWebRTCInfoView : UIView {

	FBWebRTCPhotoCircleView* _photoCircleView;
	UILabel* _nameLabel;
	UILabel* _statusLabel;
	UILabel* _miniStatusLabel;
	UILabel* _disclaimerLabel;
	UILabel* _videoDisabledLabel;
	FBMUserName* _userName;
	BOOL _disclaimerLabelHidden;
	BOOL _videoDisabledLabelHidden;
	BOOL _disclaimerLabelHiddenByVideoDisabledLabel;
	BOOL _videoTheme;
	BOOL _allowTouchEvent;
	FBWebRTCCircleAudioLevelView* _outputAudioLevelView;

}

@property (assign,nonatomic) BOOL photoHidden; 
@property (assign,nonatomic) BOOL disclaimerLabelHidden;                                         //@synthesize disclaimerLabelHidden=_disclaimerLabelHidden - In the implementation block
@property (assign,nonatomic) BOOL videoDisabledLabelHidden;                                      //@synthesize videoDisabledLabelHidden=_videoDisabledLabelHidden - In the implementation block
@property (assign,nonatomic) BOOL disclaimerLabelHiddenByVideoDisabledLabel;                     //@synthesize disclaimerLabelHiddenByVideoDisabledLabel=_disclaimerLabelHiddenByVideoDisabledLabel - In the implementation block
@property (assign,getter=isVideoTheme,nonatomic) BOOL videoTheme;                                //@synthesize videoTheme=_videoTheme - In the implementation block
@property (assign,getter=isAllowTouchEvent,nonatomic) BOOL allowTouchEvent;                      //@synthesize allowTouchEvent=_allowTouchEvent - In the implementation block
@property (nonatomic,readonly) MNProfileImageView * photoView; 
@property (nonatomic,readonly) FBWebRTCCircleAudioLevelView * outputAudioLevelView;              //@synthesize outputAudioLevelView=_outputAudioLevelView - In the implementation block
-(id)initWithAvatarImageDecorator:(id)arg1 ;
-(FBWebRTCCircleAudioLevelView *)outputAudioLevelView;
-(id)_createLabelWithFont:(id)arg1 color:(id)arg2 numberOfLines:(long long)arg3 ;
-(BOOL)isAllowTouchEvent;
-(void)setDisclaimerLabelHidden:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)_setLabel:(id)arg1 hidden:(BOOL)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)setDisclaimerLabelHiddenByVideoDisabledLabel:(BOOL)arg1 ;
-(void)_setLabel:(id)arg1 hidden:(BOOL)arg2 animated:(BOOL)arg3 ;
-(void)_hideDisclaimerLabelIfNeeded;
-(void)_setDisabledTextWithName:(id)arg1 ;
-(void)setVideomailTheme;
-(void)setVideoDisabledLabelHidden:(BOOL)arg1 ;
-(BOOL)photoHidden;
-(BOOL)videoDisabledLabelHidden;
-(BOOL)isVideoTheme;
-(void)_updateColorsToTheme;
-(void)setDisclaimerLabelHidden:(BOOL)arg1 ;
-(void)setVideoTheme:(BOOL)arg1 ;
-(void)setAllowTouchEvent:(BOOL)arg1 ;
-(void)setMiniStatus:(id)arg1 ;
-(void)setPhotoHidden:(BOOL)arg1 ;
-(void)setVideoDisabledLabelHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(BOOL)disclaimerLabelHidden;
-(BOOL)disclaimerLabelHiddenByVideoDisabledLabel;
-(void)setDisclaimerLabelHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(void)setName:(id)arg1 ;
-(void)setStatus:(id)arg1 ;
-(void)setDisplayName:(id)arg1 ;
-(MNProfileImageView *)photoView;
@end

