/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:21 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNFrequentlyUsedEmojisStoring.h>

@protocol OS_dispatch_queue;
@class FBTimeThrottler, MNNonDiscardingBlobStore, NSObject, NSDictionary, NSArray, NSString;

@interface MNFrequentlyUsedEmojisStore : NSObject <MNFrequentlyUsedEmojisStoring> {

	FBTimeThrottler* _throttler;
	MNNonDiscardingBlobStore* _blobStore;
	NSObject*<OS_dispatch_queue> _queue;
	BOOL _restored;
	NSDictionary* _emojisUsageDict;
	NSArray* _sortedFrequentlyUsedEmojis;

}

@property (copy) NSDictionary * emojisUsageDict;                    //@synthesize emojisUsageDict=_emojisUsageDict - In the implementation block
@property (copy) NSArray * sortedFrequentlyUsedEmojis;              //@synthesize sortedFrequentlyUsedEmojis=_sortedFrequentlyUsedEmojis - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_readFromDisk;
-(void)_writeToDisk;
-(void)_scheduleWriteToDatabase;
-(void)incrementUsageCounterForEmoji:(id)arg1 ;
-(void)_incrementUsageCounterForEmoji:(id)arg1 ;
-(void)_updateFrequentlyUsedEmojis;
-(void)setEmojisUsageDict:(NSDictionary *)arg1 ;
-(void)setSortedFrequentlyUsedEmojis:(NSArray *)arg1 ;
-(NSArray *)sortedFrequentlyUsedEmojis;
-(NSDictionary *)emojisUsageDict;
-(void)_didRestoreFrequentlyUsedEmojisUsageDict:(id)arg1 ;
-(void)applyDefaultFrequentlyUsedEmojis:(id)arg1 ;
-(id)frequentlyUsedEmojis;
-(id)initWithBlobStore:(id)arg1 queue:(id)arg2 ;
@end

