/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:21 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNMediaPreviewActionSheetViewControllerDelegate <NSObject>
@required
-(void)mediaPreviewActionSheetViewControllerDidCancel:(id)arg1;
-(void)mediaPreviewActionSheetViewController:(id)arg1 didSendContent:(id)arg2;
-(void)mediaPreviewActionSheetViewController:(id)arg1 didTapEditContent:(id)arg2;
-(void)mediaPreviewActionSheetViewControllerDidDeselectContent:(id)arg1;
-(void)mediaPreviewActionSheetViewController:(id)arg1 didTapAttribution:(id)arg2;
-(BOOL)mediaPreviewActionSheetViewControllerAllowEditing:(id)arg1;
-(id)mediaPreviewActionSheetViewControllerCancelButtonTitle:(id)arg1;

@end

