/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:18:23 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6F5201FD-3D2F-4BE1-80E5-E1251C7564E3/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface MNViewLifecycleManager : NSObject {

	NSMutableDictionary* _reuseQueueByKey;
	BOOL _removalOnRecycle;

}
-(id)dequeueViewForKey:(id)arg1 ontoContainer:(id)arg2 viewBlock:(/*^block*/id)arg3 ;
-(void)recycleView:(id)arg1 forKey:(id)arg2 ;
-(id)initWithRemovalOnRecycle:(BOOL)arg1 ;
-(id)_dequeueViewForKey:(id)arg1 forContainerView:(id)arg2 ;
-(void)_setUpView:(id)arg1 toContainerView:(id)arg2 ;
-(void)_recycleView:(id)arg1 forKey:(id)arg2 ;
-(void)_tearDownView:(id)arg1 ;
-(void)purge;
@end

