/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 12:03:42 AM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FE008365-307B-4CDF-8948-1B974F28A799/SolitaireFree.app/SolitaireFree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface DisplayCell : UITableViewCell {

	UILabel* nameLabel;
	UIView* view;
	UIView* thumbnailView;
	float _thumbnailWidthRatio;
	float _thumbnailHeightRatio;

}

@property (nonatomic,retain) UIView * view; 
@property (nonatomic,retain) UILabel * nameLabel; 
@property (nonatomic,retain) UIView * thumbnailView; 
@property (assign,nonatomic) float thumbnailWidthRatio;               //@synthesize thumbnailWidthRatio=_thumbnailWidthRatio - In the implementation block
@property (assign,nonatomic) float thumbnailHeightRatio;              //@synthesize thumbnailHeightRatio=_thumbnailHeightRatio - In the implementation block
-(void)setThumbnailWidthRatio:(float)arg1 ;
-(void)setThumbnailHeightRatio:(float)arg1 ;
-(float)thumbnailHeightRatio;
-(float)thumbnailWidthRatio;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(UIView *)view;
-(void)setView:(UIView *)arg1 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setThumbnailView:(UIView *)arg1 ;
-(UIView *)thumbnailView;
-(UILabel *)nameLabel;
-(void)setNameLabel:(UILabel *)arg1 ;
@end

