/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:40:10 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, FBAllocationTrackerLogger;

@interface FBAllocationTrackerManager : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	BOOL _userOptedIn;
	BOOL _passedGK;
	FBAllocationTrackerLogger* _ctscanLogger;

}
+(void)_startTrackingAllocations;
+(void)stopTrackingAllocations;
+(void)startTrackingAllocationsIfEnabled;
+(BOOL)isAllocationTrackerEnabled;
+(id)sharedManager;
-(void)_startAllocationTrackerIfPossible;
-(void)_CTScanStartTrackingAllocations;
-(void)userOptedIn;
-(void)userPassedGK;
-(id)currentAllocationSummary;
-(id)init;
@end

