/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:40:48 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Messenger/MNMessageSenderExtension.h>

@protocol FBMPaymentsBridge;
@class FBUserSession, FBMessengerPaymentsPlugin, NSMutableDictionary, NSString;

@interface FBPaymentsMessageSenderExtension : NSObject <MNMessageSenderExtension> {

	id<FBMPaymentsBridge> _paymentsBridge;
	FBUserSession* _session;
	FBMessengerPaymentsPlugin* _paymentsPlugin;
	NSMutableDictionary* _threadMoneySenders;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)shouldHandleMessage:(id)arg1 ;
-(BOOL)isErrorRetriable:(id)arg1 ;
-(BOOL)isSendingForThread:(id)arg1 ;
-(void)handleMessage:(id)arg1 delegate:(id)arg2 ;
-(id)initWithSession:(id)arg1 paymentsBridge:(id)arg2 paymentsPlugin:(id)arg3 ;
-(void)_handleMessageSentSuccessWithRecipientId:(id)arg1 paymentId:(id)arg2 message:(id)arg3 delegate:(id)arg4 ;
-(void)_handleMessageSendFailureWithRecipientId:(id)arg1 message:(id)arg2 analyticsUUID:(id)arg3 error:(id)arg4 delegate:(id)arg5 ;
-(id)_preparePaymentAttachment:(id)arg1 withRecipientId:(id)arg2 ;
@end

