/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:40:34 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Messenger/FBServiceTransactionMutating.h>

@class FBMStickerResourceManager, FBUserSession, FBServiceTransactionTokenManager, NSString;

@interface FBStickerPackThumbnailDownloader : NSObject <FBServiceTransactionMutating> {

	unsigned long long _stickerPackId;
	FBMStickerResourceManager* _resourceManager;
	FBUserSession* _session;
	BOOL _done;
	long long _priority;
	FBServiceTransactionTokenManager* _tokenManager;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)changePriorityToNewPriority:(long long)arg1 ;
-(void)downloadWithCompletion:(/*^block*/id)arg1 ;
-(void)_handleError:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(void)_didFetchThumbnailURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_handleDoneWithThumbnail:(id)arg1 error:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_cancelOnMainThread;
-(id)initWithStickerPackId:(unsigned long long)arg1 resourceManager:(id)arg2 session:(id)arg3 ;
-(void)cancel;
-(void)dealloc;
@end

