/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:40:10 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Messenger/FBExceptionHandlerDiskCleanup.h>

@protocol OS_dispatch_queue;
@class NSObject, NSString;

@interface FBTrashCollector : NSObject <FBExceptionHandlerDiskCleanup> {

	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long deletedCount;
	BOOL _needsCancel;

}

@property (assign) BOOL needsCancel;                                //@synthesize needsCancel=_needsCancel - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)clearCachesDirectoryOnLowDiskSpace;
+(BOOL)clearDirectoryContentIfLowDiskSpace:(id)arg1 diskSpaceThreshold:(unsigned long long)arg2 toDeleteFilter:(id)arg3 ;
+(id)sharedCollector;
-(void)startEmptyingTrash;
-(BOOL)syncEmptyTrashAllowingCancellation:(BOOL)arg1 ;
-(BOOL)syncEmptyTrash;
-(void)_reportAnalytics:(unsigned long long)arg1 timeSpent:(double)arg2 ;
-(BOOL)collectURL:(id)arg1 error:(id*)arg2 ;
-(void)emptyAllTrash;
-(void)dealloc;
-(id)init;
-(void)willEnterForeground;
-(void)setNeedsCancel:(BOOL)arg1 ;
-(BOOL)needsCancel;
@end

