/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:41:00 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBContainerViewController.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <Messenger/FBKeyboardObserverDelegate.h>
#import <Messenger/MNNewThreadPeoplePickerViewDelegate.h>
#import <Messenger/MNPeoplePickerViewControllerDelegate.h>
#import <UIKit/UIAlertViewDelegate.h>
#import <Messenger/FBToastPresenterProviding.h>

@protocol FBProvider, MNSuggestedContactsRetriever;
@class MNNavigationCoordinator, FBKeyboardObserver, FBKeyboardResettingTracker, MNNewThreadView, UIView, FBUserSession, MNUserStore, NSArray, UIBarButtonItem, MNNewThreadViewControllerConfiguration, MNPeoplePickerViewController, UIActionSheet, MNNavigationBarController, MNProgressBarController, FBToastPresenter, NSString;

@interface MNNewThreadViewControllerBase : FBContainerViewController <UIActionSheetDelegate, FBKeyboardObserverDelegate, MNNewThreadPeoplePickerViewDelegate, MNPeoplePickerViewControllerDelegate, UIAlertViewDelegate, FBToastPresenterProviding> {

	id<FBProvider> _peoplePickerViewControllerProvider;
	MNNavigationCoordinator* _navigationCoordinator;
	FBKeyboardObserver* _keyboardObserver;
	FBKeyboardResettingTracker* _keyboardResettingTracker;
	MNNewThreadView* _newThreadView;
	UIView* _composeView;
	BOOL _disableSending;
	BOOL _firstViewWillLayoutSubviewsDuringAppearing;
	BOOL _firstViewDidLayoutSubviewsDuringAppearing;
	FBUserSession* _session;
	MNUserStore* _userStore;
	id<MNSuggestedContactsRetriever> _suggestedContactsRetriever;
	NSArray* _peopleSuggestionsListeners;
	NSArray* _pickedUsers;
	UIBarButtonItem* _cancelButtonItem;
	MNNewThreadViewControllerConfiguration* _configuration;
	MNPeoplePickerViewController* _peoplePickerViewController;
	UIActionSheet* _actionSheet;
	MNNavigationBarController* _navigationBarController;
	id _progressTitleId;
	MNProgressBarController* _progressBarController;
	unsigned long long _appearanceState;
	FBToastPresenter* _toastPresenter;

}

@property (nonatomic,copy) NSArray * pickedUsers;                                                    //@synthesize pickedUsers=_pickedUsers - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * cancelButtonItem;                                     //@synthesize cancelButtonItem=_cancelButtonItem - In the implementation block
@property (nonatomic,retain) UIView * composeView;                                                   //@synthesize composeView=_composeView - In the implementation block
@property (nonatomic,retain) MNNewThreadViewControllerConfiguration * configuration;                 //@synthesize configuration=_configuration - In the implementation block
@property (assign,nonatomic) BOOL disableSending;                                                    //@synthesize disableSending=_disableSending - In the implementation block
@property (nonatomic,retain) MNPeoplePickerViewController * peoplePickerViewController;              //@synthesize peoplePickerViewController=_peoplePickerViewController - In the implementation block
@property (nonatomic,retain) UIActionSheet * actionSheet;                                            //@synthesize actionSheet=_actionSheet - In the implementation block
@property (nonatomic,retain) MNNavigationBarController * navigationBarController;                    //@synthesize navigationBarController=_navigationBarController - In the implementation block
@property (assign,nonatomic) id progressTitleId;                                                     //@synthesize progressTitleId=_progressTitleId - In the implementation block
@property (nonatomic,retain) MNProgressBarController * progressBarController;                        //@synthesize progressBarController=_progressBarController - In the implementation block
@property (assign,nonatomic) unsigned long long appearanceState;                                     //@synthesize appearanceState=_appearanceState - In the implementation block
@property (nonatomic,retain) FBToastPresenter * toastPresenter;                                      //@synthesize toastPresenter=_toastPresenter - In the implementation block
@property (nonatomic,readonly) MNUserStore * userStore;                                              //@synthesize userStore=_userStore - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)keyboardObserverKeyboardDidHide:(id)arg1 ;
-(void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(CGRect)arg2 endFrame:(CGRect)arg3 duration:(double)arg4 curve:(long long)arg5 ;
-(void)keyboardObserver:(id)arg1 keyboardFrameDidChangeWithBeginFrame:(CGRect)arg2 endFrame:(CGRect)arg3 duration:(double)arg4 curve:(long long)arg5 ;
-(void)_updateKeyboardFrame:(CGRect)arg1 duration:(double)arg2 curve:(long long)arg3 ;
-(NSArray *)pickedUsers;
-(void)peoplePicker:(id)arg1 didChangePickedUsers:(id)arg2 ;
-(id)analyticsModuleForPeoplePicker:(id)arg1 ;
-(id)_suggestedContactsRetriever;
-(MNUserStore *)userStore;
-(MNProgressBarController *)progressBarController;
-(void)setProgressBarController:(MNProgressBarController *)arg1 ;
-(id)globalToastPresenter;
-(BOOL)mn_shouldShowToastInNavigationBar;
-(FBToastPresenter *)toastPresenter;
-(void)setAppearanceState:(unsigned long long)arg1 ;
-(unsigned long long)appearanceState;
-(void)setDisableSending:(BOOL)arg1 ;
-(BOOL)disableSending;
-(void)setPeoplePickerViewController:(MNPeoplePickerViewController *)arg1 ;
-(void)_startViewObservations;
-(void)_stopViewObservations;
-(void)setPickedUsers:(NSArray *)arg1 ;
-(void)setProgressTitleId:(id)arg1 ;
-(MNPeoplePickerViewController *)peoplePickerViewController;
-(MNNavigationBarController *)navigationBarController;
-(void)setNavigationBarController:(MNNavigationBarController *)arg1 ;
-(id)progressTitleId;
-(void)setToastPresenter:(FBToastPresenter *)arg1 ;
-(void)_updateStatusBarVisibilityAnimated:(BOOL)arg1 ;
-(void)_updateNavigationBarVisibilityAnimated:(BOOL)arg1 ;
-(void)peoplePickerViewDidDismissSuggestionOverlay:(id)arg1 ;
-(void)updateComposerState;
-(id)peoplePickerConfiguration;
-(void)loadComposeView;
-(void)_initToastPresenter;
-(void)_updateTopBarsVisibilityAnimated:(BOOL)arg1 ;
-(void)setUpKeyboard;
-(BOOL)shouldRespondToKeyboardUpdate;
-(BOOL)_hasEnoughSpaceForPeoplePicker;
-(id)accessibilityStringForComposedContent;
-(void)dismissComposer;
-(BOOL)shouldPresentCancelActionSheet;
-(void)_showAlertControllerFromButtonItem:(id)arg1 withCancelTitle:(id)arg2 andDontSaveTitle:(id)arg3 ;
-(void)_showActionSheetFromButtonItem:(id)arg1 withCancelTitle:(id)arg2 andDontSaveTitle:(id)arg3 ;
-(void)cancelCompose;
-(void)_cancelCompose:(id)arg1 ;
-(id)initWithPeoplePickerViewControllerProvider:(id)arg1 navigationCoordinator:(id)arg2 keyboardResettingTracker:(id)arg3 suggestedContactsRetriever:(id)arg4 peopleSuggestionsListeners:(id)arg5 session:(id)arg6 userStore:(id)arg7 ;
-(void)setAccessibilityFocusOnComposer;
-(void)peoplePickerDidDismissGraySuggestionsOverlay:(id)arg1 ;
-(void)toggleProgressIndicator:(BOOL)arg1 ;
-(void)focusComposer;
-(void)updateComposeViewHeight;
-(id)newThreadView;
-(void)setComposeView:(UIView *)arg1 ;
-(UIView *)composeView;
-(void)dealloc;
-(BOOL)prefersStatusBarHidden;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2 ;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)setConfiguration:(MNNewThreadViewControllerConfiguration *)arg1 ;
-(MNNewThreadViewControllerConfiguration *)configuration;
-(UIActionSheet *)actionSheet;
-(void)setActionSheet:(UIActionSheet *)arg1 ;
-(UIBarButtonItem *)cancelButtonItem;
-(void)setCancelButtonItem:(UIBarButtonItem *)arg1 ;
-(void)configure:(id)arg1 ;
@end

