/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:40:58 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/E282ADAB-AF96-4184-9890-B5E58B4BDDD0/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Messenger/FBSessionClassProvidable.h>
#import <Messenger/MNThreadLoadEventListener.h>
#import <Messenger/MNMessagesAppearanceEventListener.h>

@class NSString, FBMLocalThreadDescriptor, FBMNetworkProtocolController;

@interface MNThreadLoadPerfLogger : NSObject <FBSessionClassProvidable, MNThreadLoadEventListener, MNMessagesAppearanceEventListener> {

	NSString* _event;
	FBMLocalThreadDescriptor* _localThreadDescriptor;
	FBMNetworkProtocolController* _networkProtocolController;
	unsigned long long _state;
	BOOL _loadingFromNetwork;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(void)threadWillBeginLoadingWithLocalThreadDescriptor:(id)arg1 eventDescriptor:(id)arg2 ;
-(void)threadDidBeginLoadingFromNetwork:(id)arg1 ;
-(void)threadDidEndLoadingWithThreadViewModel:(id)arg1 ;
-(void)messagesWillAppearWithThreadViewModel:(id)arg1 ;
-(void)messagesDidAppearWithThreadViewModel:(id)arg1 ;
-(void)messagesWillDisappearWithThreadViewModel:(id)arg1 ;
-(void)messagesDidDisappearWithThreadViewModel:(id)arg1 ;
-(void)_cleanUpCachedStates;
-(void)_markStartForThreadLoadEvent:(id)arg1 localThreadDescriptor:(id)arg2 ;
-(void)_markThreadLoadedWithThreadViewModel:(id)arg1 ;
-(void)_markStopWhenMessagesDidAppearWithThreadViewModel:(id)arg1 ;
-(void)_markAbortedWhenMessagesDidDisappearWithThreadViewModel:(id)arg1 ;
-(BOOL)_checkThreadDescriptorMatchesThreadViewModel:(id)arg1 ;
@end

