/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:49:34 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A861CD42-DC74-45D3-9030-D3B6F185E279/Gumtree.app/Gumtree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Gumtree/ApptentiveSurveyAnswerCell.h>

@class UILabel, ApptentiveSurveyOptionButton, NSLayoutConstraint;

@interface ApptentiveSurveyChoiceCell : ApptentiveSurveyAnswerCell {

	UILabel* _textLabel;
	ApptentiveSurveyOptionButton* _button;
	NSLayoutConstraint* _buttonTopConstraint;

}

@property (nonatomic,retain) UILabel * textLabel;                                   //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic,retain) ApptentiveSurveyOptionButton * button;                 //@synthesize button=_button - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * buttonTopConstraint;              //@synthesize buttonTopConstraint=_buttonTopConstraint - In the implementation block
-(void)setButtonTopConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)buttonTopConstraint;
-(ApptentiveSurveyOptionButton *)button;
-(void)layoutSubviews;
-(void)awakeFromNib;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setSelected:(BOOL)arg1 ;
-(UILabel *)textLabel;
-(void)setButton:(ApptentiveSurveyOptionButton *)arg1 ;
-(void)setTextLabel:(UILabel *)arg1 ;
@end

