/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:49:35 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A861CD42-DC74-45D3-9030-D3B6F185E279/Gumtree.app/Gumtree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Gumtree/ECBaseViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <Gumtree/ECCreditCardViewDelegate.h>

@class ECPaymentMethod, ECAd, UITableView, UILabel, UIView, ECSectionMapDataSource, ECMetricsTracker, NSString;

@interface ECPaymentSelectionViewController : ECBaseViewController <UITableViewDelegate, ECCreditCardViewDelegate> {

	/*^block*/id _onCompletion;
	ECPaymentMethod* _paymentMethod;
	ECAd* _ad;
	UITableView* _tableView;
	UILabel* _saveCardWarningLabel;
	UIView* _saveCardWarningView;
	ECPaymentMethod* _creditCardNew;
	ECSectionMapDataSource* _tableDataSource;
	ECMetricsTracker* _metricsTracker;

}

@property (nonatomic,retain) UITableView * tableView;                               //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) UILabel * saveCardWarningLabel;                        //@synthesize saveCardWarningLabel=_saveCardWarningLabel - In the implementation block
@property (nonatomic,retain) UIView * saveCardWarningView;                          //@synthesize saveCardWarningView=_saveCardWarningView - In the implementation block
@property (nonatomic,retain) ECPaymentMethod * paymentMethod;                       //@synthesize paymentMethod=_paymentMethod - In the implementation block
@property (nonatomic,retain) ECPaymentMethod * creditCardNew;                       //@synthesize creditCardNew=_creditCardNew - In the implementation block
@property (nonatomic,retain) ECSectionMapDataSource * tableDataSource;              //@synthesize tableDataSource=_tableDataSource - In the implementation block
@property (readonly) BOOL shouldShowNewCardSection; 
@property (readonly) BOOL shouldShowSavedCardsSection; 
@property (readonly) BOOL isSavedCreditCardSelected; 
@property (nonatomic,retain) ECMetricsTracker * metricsTracker;                     //@synthesize metricsTracker=_metricsTracker - In the implementation block
@property (copy) id onCompletion;                                                   //@synthesize onCompletion=_onCompletion - In the implementation block
@property (retain) ECAd * ad;                                                       //@synthesize ad=_ad - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setAd:(ECAd *)arg1 ;
-(void)trackPageView;
-(void)updateEnable;
-(ECMetricsTracker *)metricsTracker;
-(void)setMetricsTracker:(ECMetricsTracker *)arg1 ;
-(id)onCompletion;
-(void)setOnCompletion:(id)arg1 ;
-(UIView *)saveCardWarningView;
-(void)setupTableDataSource;
-(void)setupFooterForTableView;
-(UILabel *)saveCardWarningLabel;
-(id)cellForSavedCardRow:(long long)arg1 ;
-(id)cellForAddCardRow:(long long)arg1 ;
-(BOOL)isSavedCreditCardSelected;
-(id)cellForNewCardRow;
-(BOOL)shouldShowNewCardSection;
-(ECPaymentMethod *)creditCardNew;
-(void)setCreditCardNew:(ECPaymentMethod *)arg1 ;
-(void)creditCardDidChange:(id)arg1 ;
-(BOOL)shouldShowSavedCardsSection;
-(void)setSaveCardWarningLabel:(UILabel *)arg1 ;
-(void)setSaveCardWarningView:(UIView *)arg1 ;
-(void)doneAction:(id)arg1 ;
-(id)initWithPaymentMethod:(id)arg1 ;
-(id)defaultPaymentMethod;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)viewDidLayoutSubviews;
-(UITableView *)tableView;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)setTableDataSource:(ECSectionMapDataSource *)arg1 ;
-(ECSectionMapDataSource *)tableDataSource;
-(ECAd *)ad;
-(void)setPaymentMethod:(ECPaymentMethod *)arg1 ;
-(ECPaymentMethod *)paymentMethod;
@end

