/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:49:34 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A861CD42-DC74-45D3-9030-D3B6F185E279/Gumtree.app/Gumtree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol GAIReachabilityDelegate;
#import <Gumtree/Gumtree-Structs.h>
@class NSString;

@interface GAIReachabilityChecker : NSObject {

	int reachabilityStatus_;
	const GAIReachabilityApi* reachabilityApi_;
	SCNetworkReachabilityRef reachability_;
	NSString* host_;
	id<GAIReachabilityDelegate> delegate_;

}

@property (assign,nonatomic) int reachabilityStatus; 
@property (nonatomic,copy) NSString * host; 
@property (assign,nonatomic) id<GAIReachabilityDelegate> delegate; 
@property (nonatomic,readonly) BOOL isActive; 
@property (assign,nonatomic) const GAIReachabilityApi* reachabilityApi; 
@property (assign,nonatomic) SCNetworkReachabilityRef reachability; 
-(id)initWithDelegate:(id)arg1 withHost:(id)arg2 ;
-(int)statusForFlags:(unsigned)arg1 ;
-(const GAIReachabilityApi*)reachabilityApi;
-(void)setReachabilityApi:(const GAIReachabilityApi*)arg1 ;
-(void)reachabilityFlagsChanged:(unsigned)arg1 ;
-(void)setDelegate:(id<GAIReachabilityDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<GAIReachabilityDelegate>)delegate;
-(BOOL)isActive;
-(void)stop;
-(BOOL)start;
-(NSString *)host;
-(void)setHost:(NSString *)arg1 ;
-(void)setReachabilityStatus:(int)arg1 ;
-(int)reachabilityStatus;
-(SCNetworkReachabilityRef)reachability;
-(void)setReachability:(SCNetworkReachabilityRef)arg1 ;
@end

