/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:46:32 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/D20B482D-7A4B-420E-BEFA-D4B2B5C94752/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/Telegram-Structs.h>
#import <UIKit/UIView.h>
#import <Telegram/TGModernGalleryDefaultFooterView.h>

@class UILabel, UIView, NSMutableDictionary, NSString;

@interface TGGenericPeerMediaGalleryDefaultFooterView : UIView <TGModernGalleryDefaultFooterView> {

	BOOL _hasAppeared;
	UILabel* _nameLabel;
	UILabel* _dateLabel;
	UIView* _captionPanelView;
	UILabel* _captionLabel;
	NSMutableDictionary* _captionHeightForWidth;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setContentHidden:(BOOL)arg1 ;
-(void)setCaptionPanelHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setTransitionOutProgress:(double)arg1 ;
-(double)captionHeightForWidth:(double)arg1 ;
-(CGRect)captionPanelFrameForParentWidth:(double)arg1 captionHeight:(double)arg2 ;
-(double)captionWidthForWidth:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setItem:(id)arg1 ;
@end

