/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:46:33 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/D20B482D-7A4B-420E-BEFA-D4B2B5C94752/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/Telegram-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIScrollViewDelegate.h>

@class TGInstantPageControllerNavigationBar, UIView, UIScrollView, TGInstantPageLayout, NSArray, NSDictionary, NSMutableDictionary, TGWebPageMediaAttachment, NSString;

@interface TGInstantPageControllerView : UIView <UIScrollViewDelegate> {

	TGInstantPageControllerNavigationBar* _navigationBar;
	UIView* _scrollViewHeader;
	UIScrollView* _scrollView;
	/*^block*/id _urlItemTapped;
	/*^block*/id _openMediaWrapper;
	/*^block*/id _openFeedbackWrapper;
	TGInstantPageLayout* _currentLayout;
	NSArray* _currentLayoutTiles;
	NSArray* _currentLayoutItemsWithViews;
	NSArray* _currentLayoutItemsWithLinks;
	NSDictionary* _distanceThresholdGroupCount;
	NSMutableDictionary* _visibleTiles;
	NSMutableDictionary* _visibleItemsWithViews;
	NSMutableDictionary* _visibleLinkSelectionViews;
	CGPoint _previousContentOffset;
	BOOL _isDeceleratingBecauseOfDragging;
	/*^block*/id _backPressed;
	/*^block*/id _sharePressed;
	/*^block*/id _openUrl;
	/*^block*/id _openMedia;
	/*^block*/id _openFeedback;
	/*^block*/id _statusBarOffsetUpdated;
	TGWebPageMediaAttachment* _webPage;
	double _statusBarOffset;
	double _statusBarHeight;

}

@property (nonatomic,copy) id backPressed;                                    //@synthesize backPressed=_backPressed - In the implementation block
@property (nonatomic,copy) id sharePressed;                                   //@synthesize sharePressed=_sharePressed - In the implementation block
@property (nonatomic,copy) id openUrl;                                        //@synthesize openUrl=_openUrl - In the implementation block
@property (nonatomic,copy) id openMedia;                                      //@synthesize openMedia=_openMedia - In the implementation block
@property (nonatomic,copy) id openFeedback;                                   //@synthesize openFeedback=_openFeedback - In the implementation block
@property (nonatomic,copy) id statusBarOffsetUpdated;                         //@synthesize statusBarOffsetUpdated=_statusBarOffsetUpdated - In the implementation block
@property (nonatomic,retain) TGWebPageMediaAttachment * webPage;              //@synthesize webPage=_webPage - In the implementation block
@property (nonatomic,readonly) double statusBarOffset;                        //@synthesize statusBarOffset=_statusBarOffset - In the implementation block
@property (assign,nonatomic) double statusBarHeight;                          //@synthesize statusBarHeight=_statusBarHeight - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)backPressed;
-(void)setBackPressed:(id)arg1 ;
-(id)sharePressed;
-(void)setSharePressed:(id)arg1 ;
-(void)updateVisibleItems;
-(void)setOpenMedia:(id)arg1 ;
-(id)transitionViewForMedia:(id)arg1 ;
-(void)updateHiddenMedia:(id)arg1 ;
-(void)setOpenFeedback:(id)arg1 ;
-(void)setOpenUrl:(id)arg1 ;
-(double)statusBarOffset;
-(void)setStatusBarOffsetUpdated:(id)arg1 ;
-(void)updateNavigationBar;
-(void)updateNavigationBar:(BOOL)arg1 ;
-(id)openUrl;
-(id)openMedia;
-(id)openFeedback;
-(id)statusBarOffsetUpdated;
-(TGWebPageMediaAttachment *)webPage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(double)statusBarHeight;
-(void)updateLayout;
-(void)setWebPage:(TGWebPageMediaAttachment *)arg1 ;
-(void)setStatusBarHeight:(double)arg1 ;
@end

