/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:46:35 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/D20B482D-7A4B-420E-BEFA-D4B2B5C94752/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/Telegram-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <UIKit/UIPopoverPresentationControllerDelegate.h>
#import <UIKit/UIPopoverControllerDelegate.h>
#import <UIKit/UIViewControllerPreviewingDelegate.h>

@class UIView, TGMenuSheetDimView, TGMenuSheetView, SMetaDisposable, TGMenuPanGestureRecognizer, UIViewController, NSDictionary, UIPopoverController, SDisposableSet, NSArray, UIBarButtonItem, UIPanGestureRecognizer, NSString;

@interface TGMenuSheetController : UIViewController <UIGestureRecognizerDelegate, UIPopoverPresentationControllerDelegate, UIPopoverControllerDelegate, UIViewControllerPreviewingDelegate> {

	UIView* _containerView;
	TGMenuSheetDimView* _dimView;
	TGMenuSheetView* _sheetView;
	BOOL _presented;
	SMetaDisposable* _sizeClassDisposable;
	long long _sizeClass;
	BOOL _hasSwipeGesture;
	TGMenuPanGestureRecognizer* _gestureRecognizer;
	double _gestureStartPosition;
	double _gestureActualStartPosition;
	BOOL _shouldPassPanOffset;
	BOOL _wasPanning;
	BOOL _hasDistractableItems;
	UIView* _sourceView;
	UIViewController* _parentController;
	double _keyboardOffset;
	id _keyboardWillChangeFrameProxy;
	BOOL _checked3dTouch;
	NSDictionary* _3dTouchHandlers;
	UIPopoverController* _popoverController;
	BOOL _requiuresDimView;
	BOOL _dismissesByOutsideTap;
	BOOL _followsKeyboard;
	BOOL _narrowInLandscape;
	BOOL _inhibitPopoverPresentation;
	BOOL _packIsArchived;
	BOOL _packIsMask;
	SDisposableSet* _disposables;
	NSArray* _itemViews;
	/*^block*/id _willPresent;
	/*^block*/id _didDismiss;
	unsigned long long _permittedArrowDirections;
	/*^block*/id _sourceRect;
	UIBarButtonItem* _barButtonItem;
	UIPanGestureRecognizer* _panGestureRecognizer;
	double _maxHeight;

}

@property (nonatomic,readonly) SDisposableSet * disposables;                               //@synthesize disposables=_disposables - In the implementation block
@property (assign,nonatomic) BOOL requiuresDimView;                                        //@synthesize requiuresDimView=_requiuresDimView - In the implementation block
@property (assign,nonatomic) BOOL dismissesByOutsideTap;                                   //@synthesize dismissesByOutsideTap=_dismissesByOutsideTap - In the implementation block
@property (assign,nonatomic) BOOL hasSwipeGesture; 
@property (assign,nonatomic) BOOL followsKeyboard;                                         //@synthesize followsKeyboard=_followsKeyboard - In the implementation block
@property (assign,nonatomic) BOOL narrowInLandscape;                                       //@synthesize narrowInLandscape=_narrowInLandscape - In the implementation block
@property (assign,nonatomic) BOOL inhibitPopoverPresentation;                              //@synthesize inhibitPopoverPresentation=_inhibitPopoverPresentation - In the implementation block
@property (nonatomic,readonly) NSArray * itemViews;                                        //@synthesize itemViews=_itemViews - In the implementation block
@property (nonatomic,copy) id willPresent;                                                 //@synthesize willPresent=_willPresent - In the implementation block
@property (nonatomic,copy) id didDismiss;                                                  //@synthesize didDismiss=_didDismiss - In the implementation block
@property (assign,nonatomic) unsigned long long permittedArrowDirections;                  //@synthesize permittedArrowDirections=_permittedArrowDirections - In the implementation block
@property (nonatomic,copy) id sourceRect;                                                  //@synthesize sourceRect=_sourceRect - In the implementation block
@property (nonatomic,readonly) UIView * sourceView; 
@property (nonatomic,retain) UIBarButtonItem * barButtonItem;                              //@synthesize barButtonItem=_barButtonItem - In the implementation block
@property (nonatomic,readonly) long long sizeClass; 
@property (nonatomic,readonly) UIPanGestureRecognizer * panGestureRecognizer;              //@synthesize panGestureRecognizer=_panGestureRecognizer - In the implementation block
@property (nonatomic,readonly) UIViewController * parentController; 
@property (assign,nonatomic) double maxHeight;                                             //@synthesize maxHeight=_maxHeight - In the implementation block
@property (nonatomic,readonly) double statusBarHeight; 
@property (assign,nonatomic) BOOL packIsArchived;                                          //@synthesize packIsArchived=_packIsArchived - In the implementation block
@property (assign,nonatomic) BOOL packIsMask;                                              //@synthesize packIsMask=_packIsMask - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setDismissesByOutsideTap:(BOOL)arg1 ;
-(void)setHasSwipeGesture:(BOOL)arg1 ;
-(void)setNarrowInLandscape:(BOOL)arg1 ;
-(void)dismissAnimated:(BOOL)arg1 manual:(BOOL)arg2 ;
-(void)presentInViewController:(id)arg1 sourceView:(id)arg2 animated:(BOOL)arg3 ;
-(void)keyboardWillChangeFrame:(id)arg1 ;
-(void)dismissAnimated:(BOOL)arg1 manual:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)setDidDismiss:(id)arg1 ;
-(void)setup3DTouch;
-(BOOL)hasSwipeGesture;
-(double)swipeOffsetForOffset:(double)arg1 ;
-(double)clampVelocity:(double)arg1 ;
-(id)didDismiss;
-(void)setPackIsArchived:(BOOL)arg1 ;
-(void)setPackIsMask:(BOOL)arg1 ;
-(void)updateTraitsWithSizeClass:(long long)arg1 ;
-(void)setWillPresent:(id)arg1 ;
-(BOOL)followsKeyboard;
-(void)setFollowsKeyboard:(BOOL)arg1 ;
-(void)setItemViews:(id)arg1 animated:(BOOL)arg2 ;
-(SDisposableSet *)disposables;
-(void)updateKeyboardOffset:(double)arg1 ;
-(BOOL)packIsArchived;
-(void)dimViewPressed;
-(void)repositionMenuWithReferenceSize:(CGSize)arg1 ;
-(void)updateGestureRecognizer;
-(void)applySheetOffset:(double)arg1 ;
-(void)animateSheetViewToPosition:(double)arg1 velocity:(double)arg2 type:(int)arg3 completion:(/*^block*/id)arg4 ;
-(void)_presentPopoverInController:(id)arg1 ;
-(BOOL)dismissesByOutsideTap;
-(BOOL)inhibitPopoverPresentation;
-(BOOL)narrowInLandscape;
-(void)setDimViewHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)willPresent;
-(id)initWithItemViews:(id)arg1 ;
-(BOOL)requiuresDimView;
-(void)setRequiuresDimView:(BOOL)arg1 ;
-(void)setInhibitPopoverPresentation:(BOOL)arg1 ;
-(BOOL)packIsMask;
-(id)init;
-(void)dealloc;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(UIPanGestureRecognizer *)panGestureRecognizer;
-(double)statusBarHeight;
-(void)loadView;
-(void)viewWillLayoutSubviews;
-(void)handlePan:(id)arg1 ;
-(UIView *)sourceView;
-(id)sourceRect;
-(void)setSourceRect:(id)arg1 ;
-(UIBarButtonItem *)barButtonItem;
-(void)setBarButtonItem:(UIBarButtonItem *)arg1 ;
-(void)removeFromParentViewController;
-(void)dismissAnimated:(BOOL)arg1 ;
-(void)popoverControllerDidDismissPopover:(id)arg1 ;
-(void)popoverPresentationControllerDidDismissPopover:(id)arg1 ;
-(void)setPermittedArrowDirections:(unsigned long long)arg1 ;
-(void)popoverPresentationController:(id)arg1 willRepositionPopoverToRect:(inout CGRect*)arg2 inView:(inout id*)arg3 ;
-(void)popoverController:(id)arg1 willRepositionPopoverToRect:(inout CGRect*)arg2 inView:(inout id*)arg3 ;
-(unsigned long long)permittedArrowDirections;
-(void)setMaxHeight:(double)arg1 ;
-(BOOL)isInPopover;
-(UIViewController *)parentController;
-(double)maxHeight;
-(NSArray *)itemViews;
-(void)setItemViews:(NSArray *)arg1 ;
-(long long)sizeClass;
@end

