/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:46:32 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/D20B482D-7A4B-420E-BEFA-D4B2B5C94752/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/TGWallpaperInfo.h>

@class NSString;

@interface TGRemoteWallpaperInfo : TGWallpaperInfo {

	int _remoteId;
	NSString* _thumbnailUri;
	NSString* _fullscreenUri;
	int _tintColor;

}
+(id)infoWithDictionary:(id)arg1 ;
-(id)thumbnailUrl;
-(id)fullscreenUrl;
-(id)initWithRemoteId:(int)arg1 thumbnailUri:(id)arg2 fullscreenUri:(id)arg3 tintColor:(int)arg4 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)infoDictionary;
-(id)image;
-(int)tintColor;
-(BOOL)hasData;
-(id)imageData;
@end

