/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:30:35 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/16C752D5-8F70-4E83-B0AB-94FF56CA8C26/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Twitter/T1StatusTableRowAdapter.h>

@class TFNDataViewController, T1ActivityAutolayoutTableRowSubAdapter, T1ComposeController;

@interface T1ActivityTableRowAdapter : T1StatusTableRowAdapter {

	long long _style;
	TFNDataViewController* _controller;
	T1ActivityAutolayoutTableRowSubAdapter* _autolayoutAdapter;
	T1ComposeController* _composeController;

}

@property (assign,nonatomic) long long style;                                                         //@synthesize style=_style - In the implementation block
@property (assign,nonatomic,__weak) TFNDataViewController * controller;                               //@synthesize controller=_controller - In the implementation block
@property (nonatomic,retain) T1ActivityAutolayoutTableRowSubAdapter * autolayoutAdapter;              //@synthesize autolayoutAdapter=_autolayoutAdapter - In the implementation block
@property (nonatomic,retain) T1ComposeController * composeController;                                 //@synthesize composeController=_composeController - In the implementation block
-(id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4 ;
-(double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4 ;
-(void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4 ;
-(void)dataViewController:(id)arg1 willDisplayCell:(id)arg2 forItem:(id)arg3 withOptions:(id)arg4 atIndexPath:(id)arg5 ;
-(void)dataViewController:(id)arg1 showContextModeActionSheetForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4 ;
-(id)_scribeContextForActivityItem:(id)arg1 inViewController:(id)arg2 indexPath:(id)arg3 ;
-(void)setAutolayoutAdapter:(T1ActivityAutolayoutTableRowSubAdapter *)arg1 ;
-(T1ActivityAutolayoutTableRowSubAdapter *)autolayoutAdapter;
-(BOOL)_isActivityFiltered:(id)arg1 forAccount:(id)arg2 ;
-(id)init;
-(long long)style;
-(void)setStyle:(long long)arg1 ;
-(TFNDataViewController *)controller;
-(void)setController:(TFNDataViewController *)arg1 ;
-(T1ComposeController *)composeController;
-(void)setComposeController:(T1ComposeController *)arg1 ;
@end

