/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:30:42 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/16C752D5-8F70-4E83-B0AB-94FF56CA8C26/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Twitter/TFNTextCell.h>

@class UIImageView, UILabel;

@interface TFNPickableItemCell : TFNTextCell {

	BOOL _editable;
	UIImageView* _accessoryView;
	long long _accessoryType;
	UILabel* _unpickableLabel;

}

@property (assign,nonatomic) long long accessoryType;                        //@synthesize accessoryType=_accessoryType - In the implementation block
@property (nonatomic,readonly) UIImageView * accessoryView;                  //@synthesize accessoryView=_accessoryView - In the implementation block
@property (nonatomic,readonly) UILabel * unpickableLabel;                    //@synthesize unpickableLabel=_unpickableLabel - In the implementation block
@property (getter=isEditable,nonatomic,readonly) BOOL editable;              //@synthesize editable=_editable - In the implementation block
+(id)cellForTableView:(id)arg1 reuseIdentifier:(id)arg2 indexPath:(id)arg3 editable:(BOOL)arg4 ;
-(void)updateAccessoryView:(BOOL)arg1 ;
-(UILabel *)unpickableLabel;
-(void)_layoutAccessoryView;
-(void)_layoutUnpickableLabel;
-(void)layoutSubviews;
-(BOOL)isEditable;
-(long long)accessoryType;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setAccessoryType:(long long)arg1 ;
-(UIImageView *)accessoryView;
@end

