/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:30:37 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/16C752D5-8F70-4E83-B0AB-94FF56CA8C26/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Twitter/TFNTwitterActivityStream.h>

@interface TFNTwitterNetworkActivityStream : TFNTwitterActivityStream {

	long long _maxNetworkActivityItems;

}
-(id)initWithAccount:(id)arg1 serializationDictionary:(id)arg2 options:(unsigned long long)arg3 antispamConnectTweetCount:(long long)arg4 antispamConnectUserCount:(long long)arg5 ;
-(void)postUpdateNotification;
-(id)itemsToBeSerialized;
-(void)loadNewer:(id)arg1 sinceID:(id)arg2 count:(id)arg3 source:(long long)arg4 ;
-(void)loadOlder:(id)arg1 sinceID:(id)arg2 maxID:(id)arg3 count:(id)arg4 source:(long long)arg5 ;
@end

