/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:30:41 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/16C752D5-8F70-4E83-B0AB-94FF56CA8C26/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Twitter/TBase.h>
#import <Twitter/NSCoding.h>

@class NSString, TFNTwitterScribeThriftClientNetworkStatus, TFNTwitterScribeThriftClientNetworkRequestDetails;

@interface TFNTwitterScribeThriftClientNetworkRequest : NSObject <TBase, NSCoding> {

	BOOL _uriSchemeIsSet;
	BOOL _uriHostNameIsSet;
	BOOL _uriPathIsSet;
	BOOL _httpMethodIsSet;
	BOOL _protocol_IsSet;
	BOOL _startNetworkStatusIsSet;
	BOOL _endNetworkStatusIsSet;
	BOOL _serverNameIsSet;
	BOOL _serverIpIsSet;
	BOOL _httpStatusCodeIsSet;
	BOOL _twitterApiErrorCodeIsSet;
	BOOL _clientErrorInfoIsSet;
	BOOL _responseSourceIsSet;
	BOOL _requestDetailsIsSet;
	BOOL _proxyStatusIsSet;
	BOOL _viaProxy;
	BOOL _viaProxyIsSet;
	int _httpStatusCode;
	int _twitterApiErrorCode;
	NSString* _uriScheme;
	NSString* _uriHostName;
	NSString* _uriPath;
	NSString* _httpMethod;
	NSString* _protocol_;
	TFNTwitterScribeThriftClientNetworkStatus* _startNetworkStatus;
	TFNTwitterScribeThriftClientNetworkStatus* _endNetworkStatus;
	NSString* _serverName;
	NSString* _serverIp;
	NSString* _clientErrorInfo;
	long long _responseSource;
	TFNTwitterScribeThriftClientNetworkRequestDetails* _requestDetails;
	long long _proxyStatus;

}

@property (nonatomic,copy) NSString * uriScheme;                                                              //@synthesize uriScheme=_uriScheme - In the implementation block
@property (nonatomic,readonly) BOOL uriSchemeIsSet;                                                           //@synthesize uriSchemeIsSet=_uriSchemeIsSet - In the implementation block
@property (nonatomic,copy) NSString * uriHostName;                                                            //@synthesize uriHostName=_uriHostName - In the implementation block
@property (nonatomic,readonly) BOOL uriHostNameIsSet;                                                         //@synthesize uriHostNameIsSet=_uriHostNameIsSet - In the implementation block
@property (nonatomic,copy) NSString * uriPath;                                                                //@synthesize uriPath=_uriPath - In the implementation block
@property (nonatomic,readonly) BOOL uriPathIsSet;                                                             //@synthesize uriPathIsSet=_uriPathIsSet - In the implementation block
@property (nonatomic,copy) NSString * httpMethod;                                                             //@synthesize httpMethod=_httpMethod - In the implementation block
@property (nonatomic,readonly) BOOL httpMethodIsSet;                                                          //@synthesize httpMethodIsSet=_httpMethodIsSet - In the implementation block
@property (nonatomic,copy) NSString * protocol_;                                                              //@synthesize protocol_=_protocol_ - In the implementation block
@property (nonatomic,readonly) BOOL protocol_IsSet;                                                           //@synthesize protocol_IsSet=_protocol_IsSet - In the implementation block
@property (nonatomic,retain) TFNTwitterScribeThriftClientNetworkStatus * startNetworkStatus;                  //@synthesize startNetworkStatus=_startNetworkStatus - In the implementation block
@property (nonatomic,readonly) BOOL startNetworkStatusIsSet;                                                  //@synthesize startNetworkStatusIsSet=_startNetworkStatusIsSet - In the implementation block
@property (nonatomic,retain) TFNTwitterScribeThriftClientNetworkStatus * endNetworkStatus;                    //@synthesize endNetworkStatus=_endNetworkStatus - In the implementation block
@property (nonatomic,readonly) BOOL endNetworkStatusIsSet;                                                    //@synthesize endNetworkStatusIsSet=_endNetworkStatusIsSet - In the implementation block
@property (nonatomic,copy) NSString * serverName;                                                             //@synthesize serverName=_serverName - In the implementation block
@property (nonatomic,readonly) BOOL serverNameIsSet;                                                          //@synthesize serverNameIsSet=_serverNameIsSet - In the implementation block
@property (nonatomic,copy) NSString * serverIp;                                                               //@synthesize serverIp=_serverIp - In the implementation block
@property (nonatomic,readonly) BOOL serverIpIsSet;                                                            //@synthesize serverIpIsSet=_serverIpIsSet - In the implementation block
@property (assign,nonatomic) int httpStatusCode;                                                              //@synthesize httpStatusCode=_httpStatusCode - In the implementation block
@property (nonatomic,readonly) BOOL httpStatusCodeIsSet;                                                      //@synthesize httpStatusCodeIsSet=_httpStatusCodeIsSet - In the implementation block
@property (assign,nonatomic) int twitterApiErrorCode;                                                         //@synthesize twitterApiErrorCode=_twitterApiErrorCode - In the implementation block
@property (nonatomic,readonly) BOOL twitterApiErrorCodeIsSet;                                                 //@synthesize twitterApiErrorCodeIsSet=_twitterApiErrorCodeIsSet - In the implementation block
@property (nonatomic,copy) NSString * clientErrorInfo;                                                        //@synthesize clientErrorInfo=_clientErrorInfo - In the implementation block
@property (nonatomic,readonly) BOOL clientErrorInfoIsSet;                                                     //@synthesize clientErrorInfoIsSet=_clientErrorInfoIsSet - In the implementation block
@property (assign,nonatomic) long long responseSource;                                                        //@synthesize responseSource=_responseSource - In the implementation block
@property (nonatomic,readonly) BOOL responseSourceIsSet;                                                      //@synthesize responseSourceIsSet=_responseSourceIsSet - In the implementation block
@property (nonatomic,retain) TFNTwitterScribeThriftClientNetworkRequestDetails * requestDetails;              //@synthesize requestDetails=_requestDetails - In the implementation block
@property (nonatomic,readonly) BOOL requestDetailsIsSet;                                                      //@synthesize requestDetailsIsSet=_requestDetailsIsSet - In the implementation block
@property (assign,nonatomic) long long proxyStatus;                                                           //@synthesize proxyStatus=_proxyStatus - In the implementation block
@property (nonatomic,readonly) BOOL proxyStatusIsSet;                                                         //@synthesize proxyStatusIsSet=_proxyStatusIsSet - In the implementation block
@property (assign,nonatomic) BOOL viaProxy;                                                                   //@synthesize viaProxy=_viaProxy - In the implementation block
@property (nonatomic,readonly) BOOL viaProxyIsSet;                                                            //@synthesize viaProxyIsSet=_viaProxyIsSet - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)read:(id)arg1 ;
-(void)setServerName:(NSString *)arg1 ;
-(BOOL)serverNameIsSet;
-(void)setUriHostName:(NSString *)arg1 ;
-(void)setUriPath:(NSString *)arg1 ;
-(void)setProtocol_:(NSString *)arg1 ;
-(void)setStartNetworkStatus:(TFNTwitterScribeThriftClientNetworkStatus *)arg1 ;
-(void)setEndNetworkStatus:(TFNTwitterScribeThriftClientNetworkStatus *)arg1 ;
-(void)setServerIp:(NSString *)arg1 ;
-(void)setHttpStatusCode:(int)arg1 ;
-(void)setTwitterApiErrorCode:(int)arg1 ;
-(void)setClientErrorInfo:(NSString *)arg1 ;
-(void)setResponseSource:(long long)arg1 ;
-(void)setRequestDetails:(TFNTwitterScribeThriftClientNetworkRequestDetails *)arg1 ;
-(void)setProxyStatus:(long long)arg1 ;
-(void)setViaProxy:(BOOL)arg1 ;
-(id)initWithUriScheme:(id)arg1 uriHostName:(id)arg2 uriPath:(id)arg3 httpMethod:(id)arg4 protocol_:(id)arg5 startNetworkStatus:(id)arg6 endNetworkStatus:(id)arg7 serverName:(id)arg8 serverIp:(id)arg9 httpStatusCode:(int)arg10 twitterApiErrorCode:(int)arg11 clientErrorInfo:(id)arg12 responseSource:(long long)arg13 requestDetails:(id)arg14 proxyStatus:(long long)arg15 viaProxy:(BOOL)arg16 ;
-(BOOL)uriSchemeIsSet;
-(NSString *)uriHostName;
-(BOOL)uriHostNameIsSet;
-(NSString *)uriPath;
-(BOOL)uriPathIsSet;
-(BOOL)httpMethodIsSet;
-(NSString *)protocol_;
-(BOOL)protocol_IsSet;
-(TFNTwitterScribeThriftClientNetworkStatus *)startNetworkStatus;
-(BOOL)startNetworkStatusIsSet;
-(TFNTwitterScribeThriftClientNetworkStatus *)endNetworkStatus;
-(BOOL)endNetworkStatusIsSet;
-(NSString *)serverIp;
-(BOOL)serverIpIsSet;
-(BOOL)httpStatusCodeIsSet;
-(int)twitterApiErrorCode;
-(BOOL)twitterApiErrorCodeIsSet;
-(NSString *)clientErrorInfo;
-(BOOL)clientErrorInfoIsSet;
-(long long)responseSource;
-(BOOL)responseSourceIsSet;
-(TFNTwitterScribeThriftClientNetworkRequestDetails *)requestDetails;
-(BOOL)requestDetailsIsSet;
-(long long)proxyStatus;
-(BOOL)proxyStatusIsSet;
-(BOOL)viaProxy;
-(BOOL)viaProxyIsSet;
-(int)httpStatusCode;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)description;
-(void)validate;
-(NSString *)serverName;
-(void)write:(id)arg1 ;
-(NSString *)httpMethod;
-(void)setUriScheme:(NSString *)arg1 ;
-(NSString *)uriScheme;
-(void)setHttpMethod:(NSString *)arg1 ;
@end

