/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 11:30:42 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/16C752D5-8F70-4E83-B0AB-94FF56CA8C26/Twitter.app/Twitter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Twitter/TFSTwitterModel.h>

@class NSString;

@interface TFNTwitterAccountDerivedInfo : NSObject <TFSTwitterModel> {

	unsigned long long _state;
	unsigned long long _cohort;

}

@property (nonatomic,readonly) unsigned long long state;               //@synthesize state=_state - In the implementation block
@property (nonatomic,readonly) unsigned long long cohort;              //@synthesize cohort=_cohort - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)derivedInfoWithJSONData:(id)arg1 error:(id*)arg2 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(unsigned long long)cohort;
-(unsigned long long)_userStateForString:(id)arg1 ;
-(unsigned long long)_userCohortForString:(id)arg1 ;
-(id)init;
-(unsigned long long)state;
@end

