/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 1:28:00 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/21F2B006-1C28-48A8-85CE-538D78391B66/Gumtree.app/Gumtree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol SDWebImagePrefetcherDelegate;
#import <Gumtree/Gumtree-Structs.h>
@class SDWebImageManager, NSArray;

@interface SDWebImagePrefetcher : NSObject {

	SDWebImageManager* _manager;
	unsigned long long _options;
	dispatch_queue_sRef _prefetcherQueue;
	id<SDWebImagePrefetcherDelegate> _delegate;
	NSArray* _prefetchURLs;
	unsigned long long _requestedCount;
	unsigned long long _skippedCount;
	unsigned long long _finishedCount;
	double _startedTime;
	/*^block*/id _completionBlock;
	/*^block*/id _progressBlock;

}

@property (nonatomic,retain) SDWebImageManager * manager;                                   //@synthesize manager=_manager - In the implementation block
@property (assign,nonatomic) unsigned long long maxConcurrentDownloads; 
@property (assign,nonatomic) unsigned long long options;                                    //@synthesize options=_options - In the implementation block
@property (assign,nonatomic) dispatch_queue_sRef prefetcherQueue;                           //@synthesize prefetcherQueue=_prefetcherQueue - In the implementation block
@property (assign,nonatomic,__weak) id<SDWebImagePrefetcherDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSArray * prefetchURLs;                                        //@synthesize prefetchURLs=_prefetchURLs - In the implementation block
@property (assign,nonatomic) unsigned long long requestedCount;                             //@synthesize requestedCount=_requestedCount - In the implementation block
@property (assign,nonatomic) unsigned long long skippedCount;                               //@synthesize skippedCount=_skippedCount - In the implementation block
@property (assign,nonatomic) unsigned long long finishedCount;                              //@synthesize finishedCount=_finishedCount - In the implementation block
@property (assign,nonatomic) double startedTime;                                            //@synthesize startedTime=_startedTime - In the implementation block
@property (nonatomic,copy) id completionBlock;                                              //@synthesize completionBlock=_completionBlock - In the implementation block
@property (nonatomic,copy) id progressBlock;                                                //@synthesize progressBlock=_progressBlock - In the implementation block
+(id)sharedImagePrefetcher;
-(void)prefetchURLs:(id)arg1 ;
-(unsigned long long)finishedCount;
-(void)setMaxConcurrentDownloads:(unsigned long long)arg1 ;
-(unsigned long long)maxConcurrentDownloads;
-(NSArray *)prefetchURLs;
-(unsigned long long)requestedCount;
-(void)setRequestedCount:(unsigned long long)arg1 ;
-(void)setFinishedCount:(unsigned long long)arg1 ;
-(unsigned long long)skippedCount;
-(void)setSkippedCount:(unsigned long long)arg1 ;
-(dispatch_queue_sRef)prefetcherQueue;
-(void)startPrefetchingAtIndex:(unsigned long long)arg1 ;
-(void)reportStatus;
-(void)prefetchURLs:(id)arg1 progress:(/*^block*/id)arg2 completed:(/*^block*/id)arg3 ;
-(void)cancelPrefetching;
-(void)setStartedTime:(double)arg1 ;
-(void)setPrefetchURLs:(NSArray *)arg1 ;
-(void)setPrefetcherQueue:(dispatch_queue_sRef)arg1 ;
-(double)startedTime;
-(void)setDelegate:(id<SDWebImagePrefetcherDelegate>)arg1 ;
-(id)init;
-(id<SDWebImagePrefetcherDelegate>)delegate;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(void)setOptions:(unsigned long long)arg1 ;
-(unsigned long long)options;
-(SDWebImageManager *)manager;
-(void)setManager:(SDWebImageManager *)arg1 ;
-(id)progressBlock;
-(void)setProgressBlock:(id)arg1 ;
@end

