/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 2, 2015 at 10:04:55 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/6EA2C334-4708-4A2A-9290-87A765CA9E42/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <WhatsApp/WhatsApp-Structs.h>
@interface TextRect : NSObject {

	long long _line;
	NSRange _range;
	CGRect _rect;

}

@property (assign,nonatomic) CGRect rect;                 //@synthesize rect=_rect - In the implementation block
@property (assign,nonatomic) NSRange range;               //@synthesize range=_range - In the implementation block
@property (assign,nonatomic) long long line;              //@synthesize line=_line - In the implementation block
+(id)rectWithRect:(CGRect)arg1 range:(NSRange)arg2 ;
-(id)initWithRect:(CGRect)arg1 range:(NSRange)arg2 ;
-(CGRect)rect;
-(void)setRect:(CGRect)arg1 ;
-(NSRange)range;
-(long long)line;
-(void)setLine:(long long)arg1 ;
-(void)setRange:(NSRange)arg1 ;
@end

