/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 2, 2015 at 10:04:57 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/6EA2C334-4708-4A2A-9290-87A765CA9E42/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, WAGradientView, UIImageView, NSMutableArray, UIImage;

@interface WACameraWellView : UIView {

	UIView* _wellContainer;
	WAGradientView* _gradientView;
	UIImageView* _imageView;
	NSMutableArray* _stackedViews;
	UIView* _topSlice;
	long long _currentValue;
	long long _maximumValue;

}

@property (assign,nonatomic) long long currentValue;              //@synthesize currentValue=_currentValue - In the implementation block
@property (assign,nonatomic) long long maximumValue;              //@synthesize maximumValue=_maximumValue - In the implementation block
@property (nonatomic,retain) UIImage * image; 
-(void)addImage:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)adjustImageViewToFit:(id)arg1 ;
-(id)newStackView;
-(void)animateInImageInWell:(id)arg1 completion:(/*^block*/id)arg2 ;
-(long long)currentValue;
-(void)setCurrentValue:(long long)arg1 ;
-(void)setImage:(UIImage *)arg1 ;
-(void)layoutSubviews;
-(void)reset;
-(UIImage *)image;
-(void)awakeFromNib;
-(long long)maximumValue;
-(void)setMaximumValue:(long long)arg1 ;
@end

