/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 2, 2015 at 10:04:53 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/6EA2C334-4708-4A2A-9290-87A765CA9E42/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <WhatsApp/WAFieldStatsEvent.h>

@interface WAFieldStatsEventPushReceive : WAFieldStatsEvent {

	double _push_receive_while_offline;
	double _network_change_delay_t;
	double _push_receive_delay_t;

}

@property (assign,nonatomic) double push_receive_while_offline;              //@synthesize push_receive_while_offline=_push_receive_while_offline - In the implementation block
@property (assign,nonatomic) double network_change_delay_t;                  //@synthesize network_change_delay_t=_network_change_delay_t - In the implementation block
@property (assign,nonatomic) double push_receive_delay_t;                    //@synthesize push_receive_delay_t=_push_receive_delay_t - In the implementation block
-(double)push_receive_while_offline;
-(void)setPush_receive_while_offline:(double)arg1 ;
-(double)network_change_delay_t;
-(void)setNetwork_change_delay_t:(double)arg1 ;
-(double)push_receive_delay_t;
-(void)setPush_receive_delay_t:(double)arg1 ;
-(id)init;
-(void)submit;
@end

