/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 2, 2015 at 10:04:54 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/6EA2C334-4708-4A2A-9290-87A765CA9E42/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class WAMapTypeSegmentedControl, UIBarButtonItem, NSString, WAChatSession, NSMutableDictionary, NSTimer, MKMapView, UIToolbar;

@interface WAFriendsLocationViewController : UIViewController {

	WAMapTypeSegmentedControl* _segmentedControl;
	UIBarButtonItem* _barButtonSearch;
	UIBarButtonItem* _segmentedControlBarItem;
	NSString* _groupJID;
	WAChatSession* _chatSession;
	NSMutableDictionary* _participantsLocations;
	BOOL _autoScale;
	BOOL _sharingIsActive;
	NSTimer* _annotationsUpdateTimer;
	MKMapView* _mapViewMain;
	UIToolbar* _toolbar;

}

@property (nonatomic,retain) MKMapView * mapViewMain;              //@synthesize mapViewMain=_mapViewMain - In the implementation block
@property (nonatomic,retain) UIToolbar * toolbar;                  //@synthesize toolbar=_toolbar - In the implementation block
-(id)chatSession;
-(MKMapView *)mapViewMain;
-(void)setMapViewMain:(MKMapView *)arg1 ;
-(id)initWithTitle:(id)arg1 groupJID:(id)arg2 ;
-(void)xmppConnectionLocationNotification:(id)arg1 ;
-(void)xmppConnectionLocationSharingChangedNotification:(id)arg1 ;
-(void)nextFriend;
-(void)onAnnotationsUpdateTimer;
-(void)requestLocationsWithParticipants:(BOOL)arg1 ;
-(void)resubscribeForLocations;
-(void)autosetMapRegion;
-(void)setLocation:(id)arg1 forJid:(id)arg2 ;
-(void)mapView:(id)arg1 regionWillChangeAnimated:(BOOL)arg2 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2 ;
-(void)dealloc;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(UIToolbar *)toolbar;
-(void)setToolbar:(UIToolbar *)arg1 ;
-(void)mapTypeChanged:(id)arg1 ;
@end

