/*
* This header is generated by classdump-dyld 0.7
* on Monday, November 2, 2015 at 10:04:58 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/6EA2C334-4708-4A2A-9290-87A765CA9E42/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSMetadataQuery, WACloudBackupManager_Documents;

@interface WASharedMetadataQuery : NSObject {

	BOOL _finishedGathering;
	NSMetadataQuery* _internalQuery;
	WACloudBackupManager_Documents* _manager;
	unsigned long long _queryRetainCount;
	/*^block*/id _creator;

}

@property (nonatomic,retain) NSMetadataQuery * internalQuery;                                //@synthesize internalQuery=_internalQuery - In the implementation block
@property (assign,getter=isFinishedGathering,nonatomic) BOOL finishedGathering;              //@synthesize finishedGathering=_finishedGathering - In the implementation block
@property (assign,nonatomic,__weak) WACloudBackupManager_Documents * manager;                //@synthesize manager=_manager - In the implementation block
@property (assign,nonatomic) unsigned long long queryRetainCount;                            //@synthesize queryRetainCount=_queryRetainCount - In the implementation block
@property (nonatomic,copy) id creator;                                                       //@synthesize creator=_creator - In the implementation block
-(void)cloudAccountChanged:(id)arg1 ;
-(void)postUpdatedNotification;
-(id)initWithManager:(id)arg1 queryCreator:(/*^block*/id)arg2 ;
-(void)jidDidChange:(id)arg1 ;
-(void)setInternalQuery:(NSMetadataQuery *)arg1 ;
-(void)queryReady:(id)arg1 ;
-(void)queryUpdated:(id)arg1 ;
-(void)setFinishedGathering:(BOOL)arg1 ;
-(NSMetadataQuery *)internalQuery;
-(unsigned long long)queryRetainCount;
-(void)startInternalQuery;
-(void)setQueryRetainCount:(unsigned long long)arg1 ;
-(BOOL)isFinishedGathering;
-(void)restartQuery;
-(void)setManager:(WACloudBackupManager_Documents *)arg1 ;
-(WACloudBackupManager_Documents *)manager;
-(void)dealloc;
-(id)init;
-(void)stopQuery;
-(void)startQuery;
-(void)setCreator:(id)arg1 ;
-(id)creator;
@end

