/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:44:44 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/BCB8F06C-D639-4947-A2BF-415A0A66C023/Skype.app/Skype
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSData;

@interface BITHockeyAttachment : NSObject <NSCoding> {

	NSString* _filename;
	NSData* _hockeyAttachmentData;
	NSString* _contentType;

}

@property (nonatomic,readonly) NSString * filename;                        //@synthesize filename=_filename - In the implementation block
@property (nonatomic,readonly) NSData * hockeyAttachmentData;              //@synthesize hockeyAttachmentData=_hockeyAttachmentData - In the implementation block
@property (nonatomic,readonly) NSString * contentType;                     //@synthesize contentType=_contentType - In the implementation block
-(NSData *)hockeyAttachmentData;
-(id)initWithFilename:(id)arg1 hockeyAttachmentData:(id)arg2 contentType:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)contentType;
-(NSString *)filename;
@end

