/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:42:15 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/2E0DF6B4-8C57-4F66-9862-2B2C129D4027/SolitaireFree.app/SolitaireFree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SolitaireFree/AMAAdvancedOption.h>

@class NSString, AmazonAdOptions, NSArray;

@interface AMASlotsAdvancedOption : AMAAdvancedOption {

	NSString* _adSize;
	NSString* _containerSize;
	AmazonAdOptions* _adOptions;
	NSArray* _optionProcessors;

}

@property (nonatomic,retain) NSString * adSize;                        //@synthesize adSize=_adSize - In the implementation block
@property (nonatomic,retain) NSString * containerSize;                 //@synthesize containerSize=_containerSize - In the implementation block
@property (nonatomic,retain) AmazonAdOptions * adOptions;              //@synthesize adOptions=_adOptions - In the implementation block
@property (nonatomic,retain) NSArray * optionProcessors;               //@synthesize optionProcessors=_optionProcessors - In the implementation block
-(NSString *)adSize;
-(void)setAdSize:(NSString *)arg1 ;
-(void)setAdOptions:(AmazonAdOptions *)arg1 ;
-(id)getValueFromOptions:(id)arg1 forAd:(id)arg2 ;
-(void)removeOptionFromOptions:(id)arg1 ;
-(void)addOptionFromOptions:(id)arg1 toParameters:(id)arg2 forAd:(id)arg3 ;
-(id)initWithAdSize:(id)arg1 containerSize:(id)arg2 adOptions:(id)arg3 ;
-(NSArray *)optionProcessors;
-(AmazonAdOptions *)adOptions;
-(void)setOptionProcessors:(NSArray *)arg1 ;
-(NSString *)containerSize;
-(id)key;
-(void)setContainerSize:(NSString *)arg1 ;
-(Class)valueType;
@end

