/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:42:14 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/2E0DF6B4-8C57-4F66-9862-2B2C129D4027/SolitaireFree.app/SolitaireFree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Chartboost_AFQueryStringPair : NSObject {

	id _field;
	id _value;

}

@property (nonatomic,retain) id field;              //@synthesize field=_field - In the implementation block
@property (nonatomic,retain) id value;              //@synthesize value=_value - In the implementation block
-(id)URLEncodedStringValue;
-(id)value;
-(void)setValue:(id)arg1 ;
-(id)field;
-(void)setField:(id)arg1 ;
-(id)initWithField:(id)arg1 value:(id)arg2 ;
@end

