/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:42:13 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/2E0DF6B4-8C57-4F66-9862-2B2C129D4027/SolitaireFree.app/SolitaireFree
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TremorVideoAdDelegate <NSObject>
@optional
-(void)adReady:(BOOL)arg1;
-(void)adStart;
-(void)adComplete:(BOOL)arg1 responseCode:(long long)arg2;
-(void)adSkipped;
-(void)adClickThru;
-(void)adImpression;
-(void)adVideoStart:(id)arg1;
-(void)adVideoFirstQuartile:(id)arg1;
-(void)adVideoMidPoint:(id)arg1;
-(void)adVideoThirdQuartile:(id)arg1;
-(void)adVideoComplete:(id)arg1;

@end

