/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 10:21:52 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/6DE74A4E-11EF-47B8-8E27-4C42F9CB282C/Palaver.app/Palaver
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, _TtC7Palaver12ThemeVariant;

@interface Palaver.Theme : NSObject {

	 name;
	 lightVariant;
	 darkVariant;

}

@property (readonly,nonatomic) NSString * name; 
@property (readonly,nonatomic) _TtC7Palaver12ThemeVariant * lightVariant; 
@property (readonly,nonatomic) _TtC7Palaver12ThemeVariant * darkVariant; 
-(id)initWithName:(id)arg1 lightVariant:(id)arg2 darkVariant:(id)arg3 ;
-(_TtC7Palaver12ThemeVariant *)darkVariant;
-(_TtC7Palaver12ThemeVariant *)lightVariant;
-(id)init;
-(NSString *)name;
@end

