//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BCOVVideo.h"

@class BCOVCuePointCollection, NSArray, NSDictionary;

@protocol BCOVMutableVideo <BCOVVideo>
@property(copy, nonatomic) NSArray *sources;
@property(copy, nonatomic) NSDictionary *properties;
@property(copy, nonatomic) BCOVCuePointCollection *cuePoints;
@end

