//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BCOV_RACSignal.h"

@interface BCOV_RACSignal (Subscription)
- (id)subscribeError:(CDUnknownBlockType)arg1 completed:(CDUnknownBlockType)arg2;
- (id)subscribeNext:(CDUnknownBlockType)arg1 error:(CDUnknownBlockType)arg2;
- (id)subscribeCompleted:(CDUnknownBlockType)arg1;
- (id)subscribeError:(CDUnknownBlockType)arg1;
- (id)subscribeNext:(CDUnknownBlockType)arg1 error:(CDUnknownBlockType)arg2 completed:(CDUnknownBlockType)arg3;
- (id)subscribeNext:(CDUnknownBlockType)arg1 completed:(CDUnknownBlockType)arg2;
- (id)subscribeNext:(CDUnknownBlockType)arg1;
- (id)subscribe:(id)arg1;
@end

