//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCGrowingButton.h"

@interface FeedButton : SCGrowingButton
{
}

- (void)setBadgeNumber:(long long)arg1 hasUnviewedSnaps:(_Bool)arg2 hasUnviewedCash:(_Bool)arg3 hasUnviewedChats:(_Bool)arg4;

@end

