//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, NSURL, SCAdController, SCAdResolutionError;

@interface SCAdTransformResponse : NSObject <NSCoding>
{
    _Bool _forSplashView;
    NSString *_endpoint;
    NSDictionary *_data;
    NSString *_adRequestClientId;
    double _impressionViewThreshold;
    SCAdResolutionError *_error;
    NSURL *_impressionURL;
    long long _adStreamPosition;
    SCAdController *_adController;
    double _timestampSeconds;
}

@property(nonatomic) double timestampSeconds; // @synthesize timestampSeconds=_timestampSeconds;
@property(nonatomic) _Bool forSplashView; // @synthesize forSplashView=_forSplashView;
@property(nonatomic) SCAdController *adController; // @synthesize adController=_adController;
@property(nonatomic) long long adStreamPosition; // @synthesize adStreamPosition=_adStreamPosition;
@property(retain, nonatomic) NSURL *impressionURL; // @synthesize impressionURL=_impressionURL;
@property(retain, nonatomic) SCAdResolutionError *error; // @synthesize error=_error;
@property(nonatomic) double impressionViewThreshold; // @synthesize impressionViewThreshold=_impressionViewThreshold;
@property(retain, nonatomic) NSString *adRequestClientId; // @synthesize adRequestClientId=_adRequestClientId;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(copy, nonatomic) NSString *endpoint; // @synthesize endpoint=_endpoint;
- (void).cxx_destruct;
- (id)adBrandId;
- (id)adKey;
- (id)adLineItemId;
- (id)adPlacementId;
- (_Bool)isExpiredWithTTL:(double)arg1 withNow:(double)arg2;
- (_Bool)isSuccess;
- (_Bool)isNoFill;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithError:(id)arg1 data:(id)arg2 impressionUrlString:(id)arg3 adRequestClientId:(id)arg4 adController:(id)arg5;
- (void)initWithEndpointHelper:(id)arg1 data:(id)arg2 viewThreshold:(double)arg3 impressionUrlString:(id)arg4 adRequestClientId:(id)arg5 adController:(id)arg6;
- (id)initForSplashView:(id)arg1 viewThreshold:(double)arg2 adRequestClientId:(id)arg3 adController:(id)arg4;
- (id)initWithEndpoint:(id)arg1 data:(id)arg2 viewThreshold:(double)arg3 impressionUrlString:(id)arg4 adRequestClientId:(id)arg5 adController:(id)arg6;

@end

