//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MASConstraint, NSString, UIImageView, UILabel, UIView;

@interface SelectContactCell : UITableViewCell
{
    _Bool _isForSponsor;
    NSString *_page;
    UIImageView *_circle;
    MASConstraint *_circleRightConstraint;
    unsigned long long _circleType;
    UILabel *_nameLabel;
    UILabel *_subNameLabel;
    UIView *_friendMojiContainerView;
}

@property(retain, nonatomic) UIView *friendMojiContainerView; // @synthesize friendMojiContainerView=_friendMojiContainerView;
@property(retain, nonatomic) UILabel *subNameLabel; // @synthesize subNameLabel=_subNameLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) unsigned long long circleType; // @synthesize circleType=_circleType;
@property(retain, nonatomic) MASConstraint *circleRightConstraint; // @synthesize circleRightConstraint=_circleRightConstraint;
@property(retain, nonatomic) UIImageView *circle; // @synthesize circle=_circle;
@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
@property(nonatomic, setter=setIsForSponsor:) _Bool isForSponsor; // @synthesize isForSponsor=_isForSponsor;
- (void).cxx_destruct;
- (void)hideCircleViewAndUpdateEmojiView;
- (id)detailTextLabel;
- (id)textLabel;
- (void)addFriendMojiView:(id)arg1;
- (void)prepareForReuse;
- (void)setUnselectedHighlightedBackground;
- (void)setUnselectedBackground;
- (void)setSelectedBackground;
- (void)toggleRightOffsetIsSearching:(_Bool)arg1 isFastStoryPost:(_Bool)arg2;
- (void)setFontSelected:(_Bool)arg1;
- (void)setCircleSelected:(_Bool)arg1;
- (void)setBackgroundSelected:(_Bool)arg1;
- (void)setCellSelected:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 page:(id)arg3;

@end

