//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJURichStoryRichStoryItemPropertiesResponse.h"

@class NSArray, NSNumber, NSString;

@interface SOJURichStoryRichStoryItemPropertiesResponse : NSObject <SOJURichStoryRichStoryItemPropertiesResponse>
{
    NSString *_file;
    NSArray *_images;
    NSString *_background;
    NSString *_backgroundType;
    NSString *_overlay;
    NSString *_videoId;
    NSString *_mode;
    NSString *_docking;
    NSString *_sponsoredOverlay;
    NSString *_videoFirstFrame;
    NSString *_videoShareFrame;
    NSNumber *_zIndex;
}

@property(readonly, copy, nonatomic) NSNumber *zIndex; // @synthesize zIndex=_zIndex;
@property(readonly, copy, nonatomic) NSString *videoShareFrame; // @synthesize videoShareFrame=_videoShareFrame;
@property(readonly, copy, nonatomic) NSString *videoFirstFrame; // @synthesize videoFirstFrame=_videoFirstFrame;
@property(readonly, copy, nonatomic) NSString *sponsoredOverlay; // @synthesize sponsoredOverlay=_sponsoredOverlay;
@property(readonly, copy, nonatomic) NSString *docking; // @synthesize docking=_docking;
@property(readonly, copy, nonatomic) NSString *mode; // @synthesize mode=_mode;
@property(readonly, copy, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(readonly, copy, nonatomic) NSString *overlay; // @synthesize overlay=_overlay;
@property(readonly, copy, nonatomic) NSString *backgroundType; // @synthesize backgroundType=_backgroundType;
@property(readonly, copy, nonatomic) NSString *background; // @synthesize background=_background;
@property(readonly, copy, nonatomic) NSArray *images; // @synthesize images=_images;
@property(readonly, copy, nonatomic) NSString *file; // @synthesize file=_file;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFile:(id)arg1 images:(id)arg2 background:(id)arg3 backgroundType:(id)arg4 overlay:(id)arg5 videoId:(id)arg6 mode:(id)arg7 docking:(id)arg8 sponsoredOverlay:(id)arg9 videoFirstFrame:(id)arg10 videoShareFrame:(id)arg11 zIndex:(id)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

