//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUGeofilterLayoutParametersBuilder.h"

@interface SOJUGeofilterLayoutParametersBuilder (Setter)
- (id)setRotationValue:(float)arg1;
- (id)setYSizeValue:(float)arg1;
- (id)setXSizeValue:(float)arg1;
- (id)setYOffsetValue:(float)arg1;
- (id)setXOffsetValue:(float)arg1;
@end

