//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUStoryViewRecordBuilder.h"

@interface SOJUStoryViewRecordBuilder (Setter)
- (id)setScreenshotCountValue:(int)arg1;
- (id)setTimestampValue:(long long)arg1;
@end

