//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, TGCollectionViewUpdateContext;

@interface TGCollectionMenuSectionList : NSObject
{
    _Bool _recordingChanges;
    TGCollectionViewUpdateContext *_updateContext;
    NSMutableArray *_sections;
}

- (void).cxx_destruct;
- (_Bool)commitRecordedChanges:(id)arg1 additionalActions:(CDUnknownBlockType)arg2;
- (_Bool)commitRecordedChanges:(id)arg1;
- (void)beginRecordingChanges;
- (void)replaceItemInSection:(unsigned long long)arg1 atIndex:(unsigned long long)arg2 withItem:(id)arg3;
- (void)deleteItemFromSection:(unsigned long long)arg1 atIndex:(unsigned long long)arg2;
- (void)insertItem:(id)arg1 toSection:(unsigned long long)arg2 atIndex:(unsigned long long)arg3;
- (void)addItemToSection:(unsigned long long)arg1 item:(id)arg2;
- (void)deleteSection:(unsigned long long)arg1;
- (void)insertSection:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addSection:(id)arg1;
@property(readonly, nonatomic) NSArray *sections;
- (id)init;

@end

