//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TGViewController.h"

#import "ASWatcher.h"
#import "HPGrowingTextViewDelegate.h"
#import "NSUserActivityDelegate.h"
#import "TGAudioRecorderDelegate.h"
#import "TGForwardContactPickerControllerDelegate.h"
#import "TGImagePickerControllerDelegate.h"
#import "TGLegacyCameraControllerDelegate.h"
#import "TGModernConversationAudioPlayerDelegate.h"
#import "TGModernConversationEditingPanelDelegate.h"
#import "TGModernConversationInputPanelDelegate.h"
#import "TGModernConversationInputTextPanelDelegate.h"
#import "TGModernConversationTitleViewDelegate.h"
#import "TGModernConversationViewLayoutDelegate.h"
#import "TGSearchBarDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIDocumentPickerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class ASHandle, NSArray, NSMutableArray, NSMutableSet, NSNumber, NSString, NSUserActivity, SDisposableSet, SMetaDisposable, TGAttachmentSheetWindow, TGAudioRecorder, TGBotReplyMarkup, TGICloudItemRequest, TGMenuContainerView, TGModernConversationAudioPlayer, TGModernConversationAvatarButton, TGModernConversationCollectionView, TGModernConversationCompanion, TGModernConversationControllerView, TGModernConversationEmptyListPlaceholderView, TGModernConversationInputPanel, TGModernConversationInputTextPanel, TGModernConversationSearchInputPanel, TGModernConversationTitlePanel, TGModernConversationTitleView, TGModernConversationViewLayout, TGModernTemporaryView, TGModernViewStorage, TGObserverProxy, TGSearchBar, TGShareSheetWindow, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIDocumentInteractionController, UIImageView, UIScrollView, UIView;

@interface TGModernConversationController : TGViewController <UICollectionViewDataSource, TGModernConversationViewLayoutDelegate, UIViewControllerTransitioningDelegate, HPGrowingTextViewDelegate, UIGestureRecognizerDelegate, TGLegacyCameraControllerDelegate, TGModernConversationInputTextPanelDelegate, TGModernConversationEditingPanelDelegate, TGModernConversationTitleViewDelegate, TGForwardContactPickerControllerDelegate, TGModernConversationAudioPlayerDelegate, TGAudioRecorderDelegate, NSUserActivityDelegate, UIDocumentInteractionControllerDelegate, UIDocumentPickerDelegate, TGImagePickerControllerDelegate, TGSearchBarDelegate, ASWatcher, TGModernConversationInputPanelDelegate>
{
    _Bool _alreadyHadWillAppear;
    _Bool _alreadyHadDidAppear;
    double _willAppearTimestamp;
    _Bool _receivedWillDisappear;
    _Bool _didDisappearBeforeAppearing;
    NSString *_initialInputText;
    struct _NSRange _initialSelectRange;
    NSArray *_initialForwardMessages;
    _Bool _shouldHaveTitlePanelLoaded;
    _Bool _editingMode;
    NSMutableArray *_items;
    NSMutableSet *_collectionRegisteredIdentifiers;
    TGModernConversationControllerView *_view;
    TGModernConversationCollectionView *_collectionView;
    TGModernConversationViewLayout *_collectionLayout;
    UIScrollView *_collectionViewScrollToTopProxy;
    TGModernViewStorage *_viewStorage;
    NSMutableArray *_itemsBoundToTemporaryContainer;
    _Bool _disableItemBinding;
    struct CGImage *_snapshotImage;
    TGModernTemporaryView *_snapshotBackgroundView;
    UIView *_snapshotImageView;
    UIImageView *_backgroundView;
    TGModernConversationInputTextPanel *_inputTextPanel;
    TGModernConversationInputPanel *_currentInputPanel;
    TGModernConversationInputPanel *_customInputPanel;
    UIView *_titlePanelWrappingView;
    TGModernConversationTitlePanel *_primaryTitlePanel;
    TGModernConversationTitlePanel *_secondaryTitlePanel;
    TGModernConversationTitlePanel *_currentTitlePanel;
    TGModernConversationEmptyListPlaceholderView *_emptyListPlaceholder;
    _Bool _isRotating;
    double _keyboardHeight;
    double _halfTransitionKeyboardHeight;
    TGObserverProxy *_keyboardWillHideProxy;
    TGObserverProxy *_keyboardWillChangeFrameProxy;
    TGObserverProxy *_keyboardDidChangeFrameProxy;
    TGObserverProxy *_applicationWillResignActiveProxy;
    TGObserverProxy *_applicationDidEnterBackgroundProxy;
    TGObserverProxy *_applicationDidBecomeActiveProxy;
    TGObserverProxy *_screenshotProxy;
    TGObserverProxy *_dropboxProxy;
    struct CGPoint _collectionPanTouchContentOffset;
    _Bool _collectionPanStartedAtBottom;
    TGModernConversationTitleView *_titleView;
    TGModernConversationAvatarButton *_avatarButton;
    UIBarButtonItem *_avatarButtonItem;
    UIBarButtonItem *_infoButtonItem;
    TGMenuContainerView *_menuContainerView;
    UIButton *_unseenMessagesButton;
    _Bool _disableScrollProcessing;
    _Bool _enableAboveHistoryRequests;
    _Bool _enableBelowHistoryRequests;
    _Bool _enableUnloadHistoryRequests;
    _Bool _canReadHistory;
    TGAudioRecorder *_currentAudioRecorder;
    TGModernConversationAudioPlayer *_currentAudioPlayer;
    int _currentAudioPlayerMessageId;
    _Bool _streamAudioItems;
    int _currentStreamingAudioMessageId;
    NSUserActivity *_currentActivity;
    TGAttachmentSheetWindow *_attachmentSheetWindow;
    TGShareSheetWindow *_shareSheetWindow;
    UIDocumentInteractionController *_interactionController;
    TGICloudItemRequest *_currentICloudItemRequest;
    SDisposableSet *_disposable;
    int _temporaryHighlightMessageIdUponDisplay;
    _Bool _hasUnseenMessagesBelow;
    int _scrollBackMessageId;
    _Bool _canCheckScrollBackMessageId;
    NSString *_currentLinkParseLink;
    SMetaDisposable *_currentLinkParseDisposable;
    _Bool _disableLinkPreviewsForMessage;
    TGBotReplyMarkup *_replyMarkup;
    _Bool _hasBots;
    _Bool _canBroadcast;
    _Bool _isBroadcasting;
    _Bool _isAlwaysBroadcasting;
    _Bool _inputDisabled;
    _Bool _isChannel;
    UIView *_conversationHeader;
    NSNumber *_scrollingToBottom;
    TGSearchBar *_searchBar;
    TGModernConversationSearchInputPanel *_searchPanel;
    NSString *_query;
    SMetaDisposable *_searchDisposable;
    NSArray *_searchResultsIds;
    unsigned long long _searchResultsOffset;
    int _messageIdForVisibleHoleDirection;
    _Bool _loadingMessages;
    UIActivityIndicatorView *_loadingMessagesIndicator;
    _Bool _shouldIgnoreAppearAnimationOnce;
    _Bool _shouldOpenKeyboardOnce;
    ASHandle *_actionHandle;
    TGModernConversationCompanion *_companion;
}

@property(nonatomic) _Bool shouldOpenKeyboardOnce; // @synthesize shouldOpenKeyboardOnce=_shouldOpenKeyboardOnce;
@property(nonatomic) _Bool shouldIgnoreAppearAnimationOnce; // @synthesize shouldIgnoreAppearAnimationOnce=_shouldIgnoreAppearAnimationOnce;
@property(retain, nonatomic) TGModernConversationCompanion *companion; // @synthesize companion=_companion;
@property(retain, nonatomic) ASHandle *actionHandle; // @synthesize actionHandle=_actionHandle;
- (void).cxx_destruct;
- (void)setLoadingMessages:(_Bool)arg1;
- (void)broadcastForwardMessages:(id)arg1 caption:(id)arg2 toPeerIds:(id)arg3;
- (void)forwardMessages:(id)arg1 fastForward:(_Bool)arg2;
- (id)previewActionItems;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)check3DTouch;
- (_Bool)isEditing;
- (void)updateControllerShouldHideInputTextByDefault;
- (void)setIsChannel:(_Bool)arg1;
- (void)setInputDisabled:(_Bool)arg1;
- (void)setSearchResultsOffset:(unsigned long long)arg1;
- (void)setSearchResultsIds:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)beginSearchWithQuery:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 willChangeHeight:(double)arg2;
- (void)activateSearch;
- (void)hideKeyboard;
- (void)openEmbed:(id)arg1;
- (void)userActivity:(id)arg1 didReceiveInputStream:(id)arg2 outputStream:(id)arg3;
- (void)userActivityWasContinued:(id)arg1;
- (id)utiForFileExtension:(id)arg1;
- (void)actionStageActionRequested:(id)arg1 options:(id)arg2;
- (void)_performSizeChangesWithDuration:(double)arg1 size:(struct CGSize)arg2;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (id)keyboardView;
- (void)keyboardWillHide:(id)arg1;
- (void)_adjustCollectionViewForSize:(struct CGSize)arg1 keyboardHeight:(double)arg2 inputContainerHeight:(double)arg3 scrollToBottom:(_Bool)arg4 duration:(double)arg5 animationCurve:(int)arg6;
- (void)_adjustCollectionViewForSize:(struct CGSize)arg1 keyboardHeight:(double)arg2 inputContainerHeight:(double)arg3 duration:(double)arg4 animationCurve:(int)arg5;
- (void)inputPanelWillChangeHeight:(id)arg1 height:(double)arg2 duration:(double)arg3 animationCurve:(int)arg4;
- (void)unseenMessagesButtonPressed;
- (void)doneButtonPressed;
- (void)_commitDeleteCheckedMessages;
- (void)_commitClearAllMessages;
- (void)clearAllButtonPressed;
- (void)_leaveEditingModeAnimated:(_Bool)arg1;
- (_Bool)canDeleteSelectedMessages;
- (void)_enterEditingMode:(int)arg1;
- (void)inputPanelToggleBroadcastMode:(id)arg1;
- (id)inputPanelParentViewController:(id)arg1;
- (_Bool)inputPanelSendShouldBeAlwaysEnabled:(id)arg1;
- (void)audioRecorderDidStartRecording:(id)arg1;
- (double)inputPanelAudioRecordingDuration:(id)arg1;
- (void)inputPanelAudioRecordingComplete:(id)arg1;
- (void)inputPanelAudioRecordingCancel:(id)arg1;
- (void)inputPanelAudioRecordingStart:(id)arg1;
- (_Bool)inputPanelAudioRecordingEnabled:(id)arg1;
- (id)_dictionaryString:(id)arg1;
- (void)forwardContactPickerController:(id)arg1 didSelectContact:(id)arg2;
- (void)_displayContactPicker;
- (void)inputPanelRequestedToggleCommandKeyboard:(id)arg1 showCommandKeyboard:(_Bool)arg2;
- (void)inputPanelRequestedActivateCommand:(id)arg1 command:(id)arg2 userId:(int)arg3 messageId:(int)arg4;
- (void)inputPanelRequestedSendSticker:(id)arg1 sticker:(id)arg2;
- (void)inputPanelRequestedSendData:(id)arg1 data:(id)arg2;
- (void)inputPanelRequestedSendImages:(id)arg1 images:(id)arg2;
- (void)legacyCameraControllerCompletedWithNoResult;
- (void)legacyCameraControllerCompletedWithExistingMedia:(id)arg1;
- (void)legacyCameraControllerCapturedVideoWithTempFilePath:(id)arg1 fileSize:(int)arg2 previewImage:(id)arg3 duration:(double)arg4 dimensions:(struct CGSize)arg5 assetUrl:(id)arg6;
- (void)_displayWebImagePicker;
- (void)_displayPhotoPicker;
- (void)legacyCameraControllerCompletedWithDocument:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3;
- (void)imagePickerController:(id)arg1 didFinishPickingWithAssets:(id)arg2;
- (void)_displayPhotoVideoFilePickerFromFileMenu:(_Bool)arg1;
- (void)documentPicker:(id)arg1 didPickDocumentAtURL:(id)arg2;
- (void)dropboxFilesReceived:(id)arg1;
- (void)_displaySendFileMenu;
- (void)_displayGoogleDrivePicker;
- (void)_displayDropboxPicker;
- (void)_displayICloudDrivePicker;
- (void)_displayVideoPicker;
- (void)_displayLegacyCamera;
- (void)_displayCameraWithView:(id)arg1;
- (void)_displayLocationPicker;
- (void)inputPanelRequestedAttachmentsMenu:(id)arg1;
- (void)_dismissBannersForCurrentConversation;
- (void)_asyncProcessMediaAssetSignals:(id)arg1 forIntent:(int)arg2;
- (void)inputPanelRequestedSendMessage:(id)arg1 text:(id)arg2;
- (id)currentForwardMessages;
- (id)currentReplyMessage;
- (int)currentReplyMessageId;
- (void)inputTextPanelHasCancelledTypingActivity:(id)arg1;
- (void)inputPanelFocused:(id)arg1;
- (_Bool)isInputPanelTextEnabled:(id)arg1;
- (void)inputPanelLinkParsed:(id)arg1 link:(id)arg2 probablyComplete:(_Bool)arg3;
- (void)inputPanelCommandEntered:(id)arg1 command:(id)arg2;
- (void)inputPanelHashtagEntered:(id)arg1 hashtag:(id)arg2;
- (void)inputPanelMentionEntered:(id)arg1 mention:(id)arg2;
- (void)inputPanelTextChanged:(id)arg1 text:(id)arg2;
- (void)inputTextPanelHasIndicatedTypingActivity:(id)arg1;
- (void)editingPanelRequestedForwardMessages:(id)arg1;
- (void)editingPanelRequestedDeleteMessages:(id)arg1;
- (void)titleViewTapped:(id)arg1;
- (void)_maybeUnloadHistory;
- (id)inlineMediaContext:(int)arg1;
- (void)_updateItemsAnimationsEnabled;
- (void)setEnableUnloadHistoryRequests:(_Bool)arg1;
- (void)appendCommand:(id)arg1;
- (void)setIsAlwaysBroadcasting:(_Bool)arg1;
- (void)setIsBroadcasting:(_Bool)arg1;
- (void)setCanBroadcast:(_Bool)arg1;
- (void)setHasBots:(_Bool)arg1;
- (void)setReplyMarkup:(id)arg1;
- (id)_currentForwardMessageDescs;
- (int)_currentReplyMessageId;
- (id)_items;
- (_Bool)canReadHistory;
- (void)_updateCanRegroupIncomingUnreadMessages;
- (void)_updateCanReadHistory:(int)arg1;
- (void)setEnableSendButton:(_Bool)arg1;
- (void)setEnableBelowHistoryRequests:(_Bool)arg1;
- (void)setEnableAboveHistoryRequests:(_Bool)arg1;
- (void)setConversationHeader:(id)arg1;
- (void)setEmptyListPlaceholder:(id)arg1 animated:(_Bool)arg2;
- (void)setEmptyListPlaceholder:(id)arg1;
- (void)setCurrentTitlePanel:(id)arg1 animation:(int)arg2;
- (id)secondaryTitlePanel;
- (void)setSecondaryTitlePanel:(id)arg1 animated:(_Bool)arg2;
- (void)setSecondaryTitlePanel:(id)arg1;
- (id)primaryTitlePanel;
- (void)setPrimaryTitlePanel:(id)arg1;
- (id)customInputPanel;
- (void)setCustomInputPanel:(id)arg1;
- (id)defaultInputPanel;
- (void)setGlobalUnreadCount:(int)arg1;
- (void)setTypingStatus:(id)arg1 activity:(int)arg2;
- (void)setAttributedStatus:(id)arg1 allowAnimation:(_Bool)arg2;
- (void)setStatus:(id)arg1 accentColored:(_Bool)arg2 allowAnimation:(_Bool)arg3 toggleMode:(int)arg4;
- (void)setAvatarUrl:(id)arg1;
- (void)setAvatarConversationId:(long long)arg1 firstName:(id)arg2 lastName:(id)arg3;
- (void)setAvatarConversationId:(long long)arg1 title:(id)arg2 icon:(id)arg3;
- (void)setTitleModalProgressStatus:(id)arg1;
- (void)setTitleIcons:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setInlineStickerList:(id)arg1;
- (void)setForwardMessages:(id)arg1 animated:(_Bool)arg2;
- (void)setReplyMessage:(id)arg1 animated:(_Bool)arg2;
- (id)inputText;
- (void)setInputText:(id)arg1 replace:(_Bool)arg2 selectRange:(struct _NSRange)arg3;
- (void)refreshMetrics;
- (void)reloadBackground;
- (void)hideTitlePanel;
- (void)openKeyboard;
- (void)leaveEditingMode;
- (void)enterEditingMode;
- (void)showCallNumberMenu:(id)arg1;
- (void)showAddContactMenu:(id)arg1;
- (void)showActionsMenuForContact:(id)arg1 isContact:(_Bool)arg2;
- (void)showActionsMenuForLink:(id)arg1;
- (void)temporaryHighlightMessage:(int)arg1 automatically:(_Bool)arg2;
- (void)highlightAndShowActionsMenuForMessage:(int)arg1;
- (void)showActionsMenuForUnsentMessage:(int)arg1;
- (void)openBrowserFromMessage:(int)arg1 url:(id)arg2;
- (void)updateInlineMediaContexts;
- (void)resumeInlineMedia;
- (void)stopInlineMedia;
- (void)closeMediaFromMessage:(int)arg1 instant:(_Bool)arg2;
- (void)closeExistingMediaGallery;
- (void)playAudioFromMessage:(int)arg1 media:(id)arg2;
- (void)audioPlayerDidFinish;
- (void)openMediaFromMessage:(int)arg1 instant:(_Bool)arg2;
- (int)convertMessageId:(int)arg1 toPeerId:(long long)arg2;
- (int)convertMessageId:(int)arg1 fromPeerId:(long long)arg2;
- (long long)peerId;
- (void)scrollToMessage:(int)arg1 sourceMessageId:(int)arg2 animated:(_Bool)arg3;
- (void)updateItems:(id)arg1 atIndices:(id)arg2;
- (void)_endReloadDataWithTemporaryContainer;
- (void)_beginReloadDataWithTemporaryContainer;
- (void)_updateEditingPanel;
- (void)_updateUnseenMessagesButton;
- (void)setScrollBackButtonVisible:(_Bool)arg1;
- (void)setScrollBackMessageId:(int)arg1;
- (void)setUnreadMessageRangeIfAppropriate:(CDStruct_bb3f6764)arg1;
- (void)setHasUnseenMessagesBelow:(_Bool)arg1;
- (void)updateMessageAttributes:(int)arg1;
- (void)updateCheckedMessages;
- (void)imageDataInvalidated:(id)arg1;
- (void)updateItemProgressAtIndex:(unsigned long long)arg1 toProgress:(double)arg2 animated:(_Bool)arg3;
- (void)updateItemAtIndex:(unsigned long long)arg1 toItem:(id)arg2;
- (void)insertItems:(id)arg1 atIndices:(id)arg2 animated:(_Bool)arg3 intent:(int)arg4 removeAtIndices:(id)arg5;
- (void)insertItems:(id)arg1 atIndices:(id)arg2 animated:(_Bool)arg3 intent:(int)arg4;
- (void)moveItems:(id)arg1;
- (void)_deleteItemsAtIndices:(id)arg1 animated:(_Bool)arg2 animationFactor:(double)arg3;
- (void)deleteItemsAtIndices:(id)arg1 animated:(_Bool)arg2;
- (void)replaceItems:(id)arg1 atIndices:(id)arg2;
- (void)replaceItemsWithFastScroll:(id)arg1 intent:(int)arg2 scrollToMessageId:(int)arg3 scrollBackMessageId:(int)arg4 animated:(_Bool)arg5;
- (void)replaceItems:(id)arg1 positionAtMessageId:(int)arg2 expandAt:(int)arg3 jump:(_Bool)arg4 top:(_Bool)arg5 messageIdForVisibleHoleDirection:(int)arg6 scrollBackMessageId:(int)arg7 animated:(_Bool)arg8;
- (id)visibleMessageIds;
- (id)latestVisibleMessage;
- (void)addOffsetAnimation:(id)arg1 delay:(double)arg2 offset:(double)arg3;
- (void)addAlphaAnimation:(id)arg1 delay:(double)arg2;
- (void)addScaleAnimation:(id)arg1 delay:(double)arg2;
- (void)replaceItems:(id)arg1 messageIdForVisibleHoleDirection:(int)arg2;
- (id)_currentItems;
- (void)collectionViewPan:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_checkScrollBackMessage;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)_bindItem:(id)arg1 toCell:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)_updateVisibleItemIndices:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)items;
- (void)setInputPanel:(id)arg1 animated:(_Bool)arg2;
- (void)infoButtonPressed;
- (void)closeButtonPressed;
- (void)avatarPressed;
- (void)navigationBarAction;
- (void)tableTouchesCancelled;
- (void)touchedTableBackground;
- (void)stopInlineMediaIfPlaying;
- (void)stopAudioRecording;
- (void)_adjustCollectionInset;
- (void)controllerInsetUpdated:(struct UIEdgeInsets)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotate;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)serviceNotificationReceived:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)defaultRightBarButtonItem;
- (void)setIsFirstInStack:(_Bool)arg1;
- (id)defaultLeftBarButtonItem;
- (void)setInitialSnapshot:(struct CGImage *)arg1 backgroundView:(id)arg2 viewStorage:(id)arg3 topEdge:(double)arg4;
- (double)contentOffsetForMessageId:(int)arg1 scrollPosition:(int)arg2 initial:(_Bool)arg3 additionalOffset:(double)arg4;
- (void)_resetCollectionView:(_Bool)arg1;
- (void)_resetCollectionView;
- (long long)_indexForCollectionView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

