/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 1:06:46 AM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/ECBB6493-3CD3-4031-8AE5-B625F29152BF/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <Tweetbot/PTHViewController.h>
#import <UIKit/UITextFieldDelegate.h>
#import <UIKit/UIImagePickerControllerDelegate.h>
#import <UIKit/UINavigationControllerDelegate.h>

@class PTHTweetbotAccount, UIScrollView, PTHStaticSectionCell, NSDictionary, NSString;

@interface PTHTweetbotEditAccountController : PTHViewController <UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate> {

	PTHTweetbotAccount* _account;
	UIScrollView* _scrollView;
	PTHStaticSectionCell* _avatarCell;
	PTHStaticSectionCell* _nameCell;
	PTHStaticSectionCell* _locationCell;
	PTHStaticSectionCell* _urlCell;
	PTHStaticSectionCell* _userDescriptionCell;
	BOOL _keyboardHidden;
	NSDictionary* _imageInfo;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)updateAvatar:(id)arg1 ;
-(void)_showImagePicker:(long long)arg1 avatarCell:(id)arg2 ;
-(void)save;
-(void)dealloc;
-(unsigned long long)supportedInterfaceOrientations;
-(void)loadView;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)imagePickerControllerDidCancel:(id)arg1 ;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2 ;
-(void)updateUI;
-(id)initWithAccount:(id)arg1 ;
-(void)keyboardWasShown:(id)arg1 ;
-(void)keyboardWillBeHidden:(id)arg1 ;
-(void)_updateImage;
-(void)_hideKeyboard;
@end

