/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 13, 2015 at 2:24:43 AM Greenwich Mean Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /private/var/mobile/Containers/Bundle/Application/8DFB78BE-38F8-46CD-A2D2-C1EE6F510A67/Slack.app/Slack
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Slack/Slack-Structs.h>
#import <Slack/CLSCrashReport.h>

@class NSString, NSDictionary, NSDate, CLSInternalReport;

@interface CLSReport : NSObject <CLSCrashReport> {

	CLSInternalReport* _internalReport;
	unsigned _internalKVCounter;

}

@property (nonatomic,copy,readonly) NSString * identifier; 
@property (nonatomic,copy,readonly) NSDictionary * customKeys; 
@property (nonatomic,copy,readonly) NSString * bundleVersion; 
@property (nonatomic,copy,readonly) NSString * bundleShortVersionString; 
@property (nonatomic,copy,readonly) NSDate * dateCreated; 
@property (nonatomic,copy,readonly) NSString * OSVersion; 
@property (nonatomic,copy,readonly) NSString * OSBuildVersion; 
@property (nonatomic,readonly) BOOL isCrash; 
@property (nonatomic,copy) NSString * userIdentifier; 
@property (nonatomic,copy) NSString * userName; 
@property (nonatomic,copy) NSString * userEmail; 
@property (nonatomic,readonly) CLSInternalReport * internalReport;                    //@synthesize internalReport=_internalReport - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSDate * crashedOnDate; 
-(CLSInternalReport *)internalReport;
-(SCD_Struct_CL52)internalKVStorage;
-(NSString *)OSBuildVersion;
-(BOOL)isCrash;
-(void)recordValue:(id)arg1 forInternalKey:(id)arg2 ;
-(NSDictionary *)customKeys;
-(NSDate *)crashedOnDate;
-(id)initWithInternalReport:(id)arg1 ;
-(void)setObjectValue:(id)arg1 forKey:(id)arg2 ;
-(NSString *)userIdentifier;
-(NSString *)userName;
-(NSDate *)dateCreated;
-(NSString *)identifier;
-(void)setUserEmail:(NSString *)arg1 ;
-(NSString *)userEmail;
-(NSString *)bundleVersion;
-(NSString *)OSVersion;
-(void)setUserName:(NSString *)arg1 ;
-(void)setUserIdentifier:(NSString *)arg1 ;
-(NSString *)bundleShortVersionString;
@end

