/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 7:32:37 PM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/7A9B3F5D-7CE0-4395-B5B1-42A1050C3CA9/AngryBirdsClassic.app/AngryBirdsClassic
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AngryBirdsClassic/SKProductsRequestDelegate.h>

@protocol OS_dispatch_queue;
@class SKProductsRequest, NSObject, NSString;

@interface GADProductsRequest : NSObject <SKProductsRequestDelegate> {

	SKProductsRequest* _productsRequest;
	/*^block*/id _completionHandler;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)requestProductsWithProductIdentifiers:(id)arg1 queue:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)requestWithQueue:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)request:(id)arg1 didFailWithError:(id)arg2 ;
-(id)initWithProductIdentifiers:(id)arg1 ;
-(void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2 ;
@end

