/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:50:48 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/F01A5503-B253-4A30-B0BC-B7B5406FD725/WhatsApp.app/WhatsApp
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WhatsApp/WhatsApp-Structs.h>
#import <WhatsApp/WAMessageHelper.h>

@interface WAImageMessageHelper : WAMessageHelper
+(void)copyContentToPasteboardOfType:(unsigned long long)arg1 inMessage:(id)arg2 ;
+(id)stringRepresentationForMessage:(id)arg1 ;
+(id)stringRepresentationForChatForMessage:(id)arg1 ;
+(id)formattedStringWithVoiceOverSummaryForMessage:(id)arg1 ;
+(id)attributedTextForMessage:(id)arg1 ;
+(BOOL)needsImageLoader;
+(BOOL)canCopyContentToPasteboardOfType:(unsigned long long)arg1 inMessage:(id)arg2 ;
+(BOOL)needsMediaBrowserThumbnail;
+(double)blurredImageMaximumWidth;
-(id)activitySubjectForActivityType:(id)arg1 ;
-(id)smallImageForMessageImageLoaderWithInfo:(id)arg1 ;
-(id)largeImageForMessageImageLoaderWithInfo:(id)arg1 ;
-(void)storeOutgoingMedia:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)internalGenerateMediaBrowserThumbnailFromImageRepresentation:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)messageDidDownloadMedia;
-(CGSize)transformedLargeImageSizeWithOriginalImageSizeInPixels:(CGSize)arg1 ;
@end

