/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:22 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/ASContextTransitioning.h>

@protocol _ASTransitionContextLayoutDelegate, _ASTransitionContextCompletionDelegate;
@class NSString;

@interface _ASTransitionContext : NSObject <ASContextTransitioning> {

	BOOL _animated;
	id<_ASTransitionContextLayoutDelegate> _layoutDelegate;
	id<_ASTransitionContextCompletionDelegate> _completionDelegate;

}

@property (assign,nonatomic,__weak) id<_ASTransitionContextLayoutDelegate> layoutDelegate;                      //@synthesize layoutDelegate=_layoutDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<_ASTransitionContextCompletionDelegate> completionDelegate;              //@synthesize completionDelegate=_completionDelegate - In the implementation block
@property (getter=isAnimated,nonatomic,readonly) BOOL animated;                                                 //@synthesize animated=_animated - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithAnimation:(BOOL)arg1 layoutDelegate:(id)arg2 completionDelegate:(id)arg3 ;
-(id)layoutForKey:(id)arg1 ;
-(CKSizeRange)constrainedSizeForKey:(id)arg1 ;
-(id)subnodesForKey:(id)arg1 ;
-(id)insertedSubnodes;
-(id)removedSubnodes;
-(CGRect)initialFrameForNode:(id)arg1 ;
-(CGRect)finalFrameForNode:(id)arg1 ;
-(void)completeTransition:(BOOL)arg1 ;
-(BOOL)isAnimated;
-(id<_ASTransitionContextCompletionDelegate>)completionDelegate;
-(void)setCompletionDelegate:(id<_ASTransitionContextCompletionDelegate>)arg1 ;
-(void)setLayoutDelegate:(id<_ASTransitionContextLayoutDelegate>)arg1 ;
-(id<_ASTransitionContextLayoutDelegate>)layoutDelegate;
@end

