/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:23 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FB360PhotoRendererLoopDelegate;
@class CADisplayLink, GLKView;

@interface FB360PhotoRendererLoop : NSObject {

	CADisplayLink* _displayLink;
	BOOL _paused;
	GLKView* _glView;
	id<FB360PhotoRendererLoopDelegate> _delegate;

}

@property (assign,nonatomic,__weak) GLKView * glView;                                         //@synthesize glView=_glView - In the implementation block
@property (assign,getter=isPaused,nonatomic) BOOL paused;                                     //@synthesize paused=_paused - In the implementation block
@property (assign,nonatomic,__weak) id<FB360PhotoRendererLoopDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(GLKView *)glView;
-(void)setGlView:(GLKView *)arg1 ;
-(void)_applicationWillForeground;
-(id)init;
-(void)setDelegate:(id<FB360PhotoRendererLoopDelegate>)arg1 ;
-(void)dealloc;
-(id<FB360PhotoRendererLoopDelegate>)delegate;
-(void)setPaused:(BOOL)arg1 ;
-(void)_applicationWillResignActive;
-(BOOL)isPaused;
-(void)_displayLinkCallback:(id)arg1 ;
@end

