/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:08 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <Facebook/FBComposerAudienceTargetingPickerControllerDelegate.h>
#import <Facebook/FBComposerPickerController.h>
#import <Facebook/FBComposerCompositionStateChangedListener.h>

@protocol FBComposerUpdateHandler;
@class FBComposerCompositionState, FBComposerAudienceTargetingPickerViewController, FBUserSession, NSString;

@interface FBComposerTargetingSelectionFlowController : NSObject <FBComposerAudienceTargetingPickerControllerDelegate, FBComposerPickerController, FBComposerCompositionStateChangedListener> {

	FBComposerCompositionState* _currentCompositionState;
	FBComposerAudienceTargetingPickerViewController* _pickerController;
	id<FBComposerUpdateHandler> _composerUpdateHandler;
	FBUserSession* _userSession;
	BOOL _canTargetToFollowers;
	BOOL _isFollowerTargeted;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)composerCompositionStateChangedFromPreviousCompositionState:(id)arg1 toCurrentCompositionState:(id)arg2 ;
-(id)presentableViewControllerWithNavigationPayload:(id)arg1 ;
-(unsigned long long)popoverStyle;
-(CGSize)popoverContentSizeForOrientation:(long long)arg1 ;
-(void)dismissPopoverController;
-(void)audiencePickerControllerDidTapCancelNavigationButton:(id)arg1 ;
-(void)audiencePickerController:(id)arg1 userDidMakeSelection:(id)arg2 shouldDismiss:(BOOL)arg3 ;
-(id)initWithUserSession:(id)arg1 composerUpdateHandler:(id)arg2 ;
-(void)_setTargetingEnabled:(BOOL)arg1 destinationUpdate:(id)arg2 ;
-(void)audiencePickerControllerDidTapDoneNavigationButton:(id)arg1 selectedAudienceType:(long long)arg2 ;
@end

