/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:11 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol FBWebView;
@class UILabel, UIView, UIButton, NSString;

@interface FBComposerSponsorTaggingTermsView : UIView <UIScrollViewDelegate> {

	UILabel* _titleLabel;
	UIView*<FBWebView> _termsWebView;
	UIButton* _agreeButton;
	UIButton* _laterButton;

}

@property (nonatomic,readonly) UIButton * agreeButton;              //@synthesize agreeButton=_agreeButton - In the implementation block
@property (nonatomic,readonly) UIButton * laterButton;              //@synthesize laterButton=_laterButton - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 policyURL:(id)arg2 ;
-(UIButton *)agreeButton;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1 ;
-(UIButton *)laterButton;
@end

