/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:15 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBAuthUIPresenterAnimationDelegate.h>
#import <Facebook/FBAuthSpinnerUIProviding.h>
#import <Facebook/FBDeviceBasedLoginFlowUIProviding.h>

@protocol FBDBLViewConfiguring;
@class FBImageDownloader, NSString;

@interface FBDeviceBasedLoginPadUIProvider : NSObject <FBAuthUIPresenterAnimationDelegate, FBAuthSpinnerUIProviding, FBDeviceBasedLoginFlowUIProviding> {

	id<FBDBLViewConfiguring> _configuration;
	FBImageDownloader* _imageDownloader;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)usernamePasswordViewControllerWithIdentifier:(id)arg1 error:(id)arg2 ;
-(id)passwordViewControllerWithUserInfo:(id)arg1 error:(id)arg2 ;
-(id)animationControllerForPresenter:(id)arg1 operation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4 ;
-(id)spinnerControllerWithLabelText:(id)arg1 ;
-(id)usernamePasswordViewControllerWithIdentifier:(id)arg1 ;
-(id)userChooserViewControllerForUsers:(id)arg1 ;
-(id)noPinLoadingViewControllerForUser:(id)arg1 ;
-(id)passwordViewControllerWithUserInfo:(id)arg1 ;
-(id)pinViewControllerWithUserInfo:(id)arg1 retry:(BOOL)arg2 ;
-(id)pinRecoveryViewControllerWithUserInfo:(id)arg1 ;
-(id)ssoLoadingViewControllerForUser:(id)arg1 ;
-(id)ssoWarningForUser:(id)arg1 ;
-(id)faceRecViewController;
-(id)init;
-(id)initWithConfiguration:(id)arg1 ;
@end

