/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:03 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/CKCompositeComponent.h>

@class FBEventGuestlistViewModel, FBEventPermalinkToolbox, FIGProfilePhotoComponent;

@interface FBEventGuestSectionComponent : CKCompositeComponent {

	FBEventGuestlistViewModel* _model;
	FBEventPermalinkToolbox* _toolbox;
	FIGProfilePhotoComponent* _facepileComponent;

}
+(id)newWithModel:(id)arg1 imageDownloader:(id)arg2 toolbox:(id)arg3 ;
-(void)_didTapGoing:(id)arg1 ;
-(void)facepileComponent:(id)arg1 didSelectItemAtIndex:(id)arg2 ;
-(void)_pushFilteredGuestlistDetailViewController:(long long)arg1 view:(id)arg2 ;
-(void)_didTapMaybe:(id)arg1 ;
-(void)_didTapInvited:(id)arg1 ;
@end

