/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:11 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Facebook/Facebook-Structs.h>
@interface FBEventPermalinkChangesetAdapter : NSObject
+(Changeset*)changesetForLoadingModel:(id)arg1 againstState:(id)arg2 session:(id)arg3 ;
+(Items*)_changesetItemsForLoadingModel:(id)arg1 stencil:(vector<FBEventPermalinkStencilCellType, std::__1::allocator<FBEventPermalinkStencilCellType> >*)arg2 againstState:(id)arg3 section:(long long)arg4 session:(id)arg5 ;
+(id)valueModelForLoadingModel:(id)arg1 cellType:(unsigned long long)arg2 session:(id)arg3 ;
@end

