/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:16 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBStreamListener.h>
#import <Facebook/FBGraphQLConnectionStoreListener.h>
#import <Facebook/FBFriendingPossibilitiesStateListener.h>

@class FBUserSession, FBStream, FBGraphQLConnectionStore, FBFriendingPossibilitiesStateFetcher, FBFriendingPossibilitiesDataUpdateListenerAnnouncer, NSError, FBFriendingPossibilitiesDataSource, NSString;

@interface FBFriendingPossibilitiesDataCoordinator : NSObject <FBStreamListener, FBGraphQLConnectionStoreListener, FBFriendingPossibilitiesStateListener> {

	FBUserSession* _session;
	FBStream* _friendingStream;
	FBGraphQLConnectionStore* _friendingStore;
	FBFriendingPossibilitiesStateFetcher* _stateFetcher;
	FBFriendingPossibilitiesDataUpdateListenerAnnouncer* _dataUpdateAnnouncer;
	BOOL _includeHidden;
	BOOL _stateFetcherHasFetchedInitialState;
	BOOL _connectionStoreHasFinishedRestoring;
	BOOL _hasFinishedInitialization;
	BOOL _friendingPossibilitiesStateChangeNotHandled;
	BOOL _friendingPossibilitiesStateChangedDuringHeadLoad;
	NSError* _errorDuringInitialization;
	BOOL _enabled;
	FBFriendingPossibilitiesDataSource* _friendingDataSource;

}

@property (assign,nonatomic) BOOL enabled;                                                            //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,readonly) FBFriendingPossibilitiesDataSource * friendingDataSource;              //@synthesize friendingDataSource=_friendingDataSource - In the implementation block
@property (nonatomic,readonly) BOOL isLoading; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)stream:(id)arg1 didFinishLoading:(unsigned long long)arg2 withResults:(id)arg3 requestAnalyticsUUID:(id)arg4 userInfo:(id)arg5 ;
-(void)processDataLocallyForMQTTRemoveWithFBID:(id)arg1 ;
-(FBFriendingPossibilitiesDataSource *)friendingDataSource;
-(void)loadForType:(long long)arg1 ;
-(void)removeStaleEdges;
-(void)markAllUnseenAsUnread;
-(void)markAllAsSeen;
-(void)markAllSeenAsRead;
-(void)graphQLConnectionStoreDidFinishAttemptingToRestoreFirstPersistedPage:(id)arg1 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byInsertingChunkAtIndex:(unsigned long long)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byRemovingChunksAtIndexes:(id)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byMergingChunkAtIndexWithPrecedingChunk:(unsigned long long)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byInsertingEdgesAtIndexPaths:(id)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byRemovingEdgesAtIndexPaths:(id)arg3 deletionReason:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byUpdatingEdgesAtIndexPaths:(id)arg3 userInfo:(id)arg4 ;
-(void)graphQLConnectionStore:(id)arg1 didModifyPreviousState:(id)arg2 byUpdatingLocations:(id)arg3 userInfo:(id)arg4 ;
-(void)fetchLatestState;
-(void)_setupFriendingDataSource;
-(BOOL)_connectionStoreIsUpToDate;
-(void)_doReload;
-(id)_latestNonHiddenTimestampInConnectionStore;
-(void)_finishInitializationAndCheckUpToDateWithError:(id)arg1 ;
-(void)friendingPossibilitiesDidFetchInitialState:(id)arg1 ;
-(void)friendingPossibilitiesDidFetchUpdatedState:(id)arg1 ;
-(void)friendingPossibilitiesDidUpdateStateLocally:(id)arg1 ;
-(void)friendingPossibilitiesFetchInitialStateFailedWithError:(id)arg1 ;
-(void)friendingPossibilitiesFetchUpdatedStateFailedWithError:(id)arg1 ;
-(id)initWithSession:(id)arg1 stateFetcher:(id)arg2 includeHidden:(BOOL)arg3 enabled:(BOOL)arg4 ;
-(id)initWithSession:(id)arg1 friendingPossibilitiesDataSource:(id)arg2 friendingPossibilitiesStream:(id)arg3 friendingPossibilitiesConnectionStore:(id)arg4 stateFetcher:(id)arg5 includeHidden:(BOOL)arg6 enabled:(BOOL)arg7 ;
-(void)addDataUpdateListener:(id)arg1 ;
-(void)removeDataUpdateListener:(id)arg1 ;
-(BOOL)enabled;
-(void)dealloc;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isLoading;
-(void)_reload;
@end

