/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:11 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <UIKit/UIView.h>

@protocol FBMLPermalinkBottomBarWrapperViewResponder;
@class FBMLHitTestSloppyButton, FBMLPermalinkBottomBarMembershipView;

@interface FBMLPermalinkBottomBarWrapperView : UIView {

	FBMLHitTestSloppyButton* _moreButton;
	FBMLHitTestSloppyButton* _addPhotosButton;
	FBMLPermalinkBottomBarMembershipView* _membersView;
	id<FBMLPermalinkBottomBarWrapperViewResponder> _responder;

}

@property (nonatomic,readonly) FBMLPermalinkBottomBarMembershipView * membersView;                         //@synthesize membersView=_membersView - In the implementation block
@property (assign,nonatomic,__weak) id<FBMLPermalinkBottomBarWrapperViewResponder> responder;              //@synthesize responder=_responder - In the implementation block
-(id)initWithImageDownloader:(id)arg1 ;
-(void)_didTapMore;
-(void)_didTapAddPhotos;
-(FBMLPermalinkBottomBarMembershipView *)membersView;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setResponder:(id<FBMLPermalinkBottomBarWrapperViewResponder>)arg1 ;
-(id<FBMLPermalinkBottomBarWrapperViewResponder>)responder;
@end

