/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:16 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/Facebook-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDictionary;

@interface FBModifiedFilterState : NSObject <NSCopying> {

	NSString* _name;
	NSString* _handle;
	NSString* _action;
	NSString* _text;
	NSString* _value;

}

@property (nonatomic,copy,readonly) NSString * name;                               //@synthesize name=_name - In the implementation block
@property (nonatomic,copy,readonly) NSString * handle;                             //@synthesize handle=_handle - In the implementation block
@property (nonatomic,copy,readonly) NSString * action;                             //@synthesize action=_action - In the implementation block
@property (nonatomic,copy,readonly) NSString * text;                               //@synthesize text=_text - In the implementation block
@property (nonatomic,copy,readonly) NSString * value;                              //@synthesize value=_value - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * apiDictionary; 
@property (nonatomic,copy,readonly) NSDictionary * loggingDictionary; 
+(id)identifierForModifiedFilter:(id)arg1 handle:(id)arg2 ;
-(id)initWithName:(id)arg1 handle:(id)arg2 action:(id)arg3 text:(id)arg4 value:(id)arg5 ;
-(NSDictionary *)apiDictionary;
-(NSDictionary *)loggingDictionary;
-(NSString *)name;
-(NSString *)action;
-(NSString *)value;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)text;
-(NSString *)handle;
@end

