/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:02 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Facebook/FBNearbyPlacesResultListViewControllerDelegate.h>
#import <Facebook/FBNearbyPlacesRecommendationsLoggerDatasource.h>
#import <Facebook/FBSearchResultsTransientViewStateHelperDelegate.h>
#import <Facebook/FBScrollableViewController.h>
#import <Facebook/FBSearchFocusedViewControllerProtocol.h>
#import <Facebook/FBSearchResultsControllerProtocol.h>

@protocol FBNearbyPlacesResultListDataFetching;
@class FBSerpConfig, FBNearbyPlacesSearchTabContainerView, FBNearbyPlacesResultListViewController, FBUserSession, FBScenePath, FBNearbyPlacesSearchData, FBSearchResultsActivityListenerAnnouncer, FBSearchResultsTransientViewStateHelper, FBNearbyPlacesLoggerHelper, UIViewController, FBTimer, NSString, UIScrollView, NSDictionary;

@interface FBPlacesSearchBarTabViewController : UIViewController <FBNearbyPlacesResultListViewControllerDelegate, FBNearbyPlacesRecommendationsLoggerDatasource, FBSearchResultsTransientViewStateHelperDelegate, FBScrollableViewController, FBSearchFocusedViewControllerProtocol, FBSearchResultsControllerProtocol> {

	FBSerpConfig* _serpConfig;
	FBNearbyPlacesSearchTabContainerView* _searchTabContainerView;
	FBNearbyPlacesResultListViewController* _resultListViewController;
	FBUserSession* _session;
	FBScenePath* _scenePath;
	FBNearbyPlacesSearchData* _searchData;
	FBSearchResultsActivityListenerAnnouncer* _announcer;
	FBSearchResultsTransientViewStateHelper* _viewStateHelper;
	FBNearbyPlacesLoggerHelper* _loggerHelper;
	id<FBNearbyPlacesResultListDataFetching> _dataFetcher;
	UIViewController* _hostViewController;
	FBTimer* _surveyTimer;
	BOOL _isCurrentlyVisible;
	BOOL _initialResultsReceived;
	BOOL _didTapAtLeastOneResult;
	BOOL _focused;
	unsigned long long _searchResultsChildVCPriority;

}

@property (nonatomic,readonly) unsigned long long resultType; 
@property (nonatomic,copy,readonly) NSString * resultsSessionID; 
@property (nonatomic,readonly) unsigned long long searchResultsChildVCPriority;              //@synthesize searchResultsChildVCPriority=_searchResultsChildVCPriority - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIScrollView * contentScrollView; 
@property (getter=isFocused,nonatomic,readonly) BOOL focused;                                //@synthesize focused=_focused - In the implementation block
@property (nonatomic,readonly) FBSerpConfig * serpConfig;                                    //@synthesize serpConfig=_serpConfig - In the implementation block
@property (nonatomic,copy,readonly) NSString * analyticsModule; 
@property (nonatomic,copy,readonly) NSDictionary * analyticsExtras; 
-(NSString *)analyticsModule;
-(NSDictionary *)analyticsExtras;
-(SEL)fb_actionForBackArrowButton;
-(NSString *)resultsSessionID;
-(void)viewStateHelperWillSetViewNeedsLayout:(id)arg1 ;
-(id)currentFilterTypeSets;
-(BOOL)supportMapToggleButton;
-(BOOL)isMapButtonEnabled;
-(id)titleForMapToggleButton;
-(void)didTapOnMapButton;
-(FBSerpConfig *)serpConfig;
-(id)filteredSemantic;
-(void)loadHeadIfEmpty;
-(void)setNeedsToYieldImpressionWithSource:(id)arg1 ;
-(void)startEarlyLoad;
-(void)setHostViewControllerForSurvey:(id)arg1 ;
-(id)filtersTitle;
-(id)downloaderFilters;
-(unsigned long long)filtersColorScheme;
-(void)applyFilterChangeset:(id)arg1 expectedFilters:(id)arg2 ;
-(id)newFilterableControllerWithFiltersChangeset:(id)arg1 expectedFilters:(id)arg2 ;
-(void)notifyFocused;
-(void)notifyUnfocused;
-(void)_didTapBackArrowButton;
-(id)initWithSession:(id)arg1 serpConfig:(id)arg2 announcer:(id)arg3 scenePath:(id)arg4 ;
-(id)_buildSearchData:(id)arg1 ;
-(id)_buildSearchContext;
-(void)_showSurveyWithIntegrationPointId:(id)arg1 ;
-(void)_prepareResultsView;
-(void)_prepareTransientView;
-(void)_stopSurveyTimer;
-(unsigned long long)_resultListDisplayMode;
-(void)_logExperienceBeganIfNeeded;
-(void)_startSurveyTimer;
-(void)_logExperienceEndedIfNeeded;
-(id)_convertDisplayModeToString:(unsigned long long)arg1 ;
-(BOOL)_shouldShowSurvey;
-(void)nearbyPlacesResultListViewControllerDidChangeDisplayState:(unsigned long long)arg1 ;
-(void)nearbyPlacesResultListViewControllerDidReceiveResults:(BOOL)arg1 ;
-(void)nearbyPlacesResultListViewControllerDidFail;
-(void)nearbyPlacesResultListViewControllerDidTapResult:(id)arg1 ;
-(BOOL)userHasLocationServices;
-(unsigned long long)searchResultsChildVCPriority;
-(void)dealloc;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)isFocused;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewWillLayoutSubviews;
-(UIScrollView *)contentScrollView;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(unsigned long long)resultType;
@end

