/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:08 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Facebook/FBBackstagePublishingHandlerListener.h>
#import <Facebook/FBAppService.h>

@protocol OS_dispatch_queue;
@class FBUserSession, NSObject, FBShareSheetCache, NSString;

@interface FBShareSheetDataUpdater : NSObject <FBBackstagePublishingHandlerListener, FBAppService> {

	FBUserSession* _session;
	NSObject*<OS_dispatch_queue> _cacheQueue;
	FBShareSheetCache* _shareSheetCache;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)startAppService;
-(void)stopAppService;
-(void)publishingHandler:(id)arg1 willPublishTask:(id)arg2 ;
-(void)publishingHandler:(id)arg1 didEnqueueTask:(id)arg2 ;
-(void)publishingHandler:(id)arg1 didFinishTask:(id)arg2 error:(id)arg3 ;
-(void)publishingHandlerDidFinishAllPublications:(id)arg1 ;
-(void)publishingHandler:(id)arg1 didUpdateProgress:(double)arg2 forTask:(id)arg3 ;
-(void)publishingHandler:(id)arg1 didTimeoutForTask:(id)arg2 ;
-(void)publishingHandler:(id)arg1 didChangeCancelEligibilityForTask:(id)arg2 ;
-(void)_queryAndSaveShareSheetFriends;
-(void)dealloc;
-(id)initWithSession:(id)arg1 ;
@end

