/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 24, 2016 at 12:21:15 AM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/FE7A361D-639E-4E8F-9E98-6A4739748428/Facebook.app/Facebook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MessageStoryAttachmentFragmentBuilder <FBFragmentModelBuilderProtocol>
@required
-(id)getResult;
-(id)setStyleList:(id)arg1;
-(id)setActionLinks:(id)arg1;
-(id)setTitle:(id)arg1;
-(id)setSource:(id)arg1;
-(id)setTarget:(id)arg1;
-(id)setTracking:(id)arg1;
-(id)setSubtitle:(id)arg1;
-(id)setProperties:(id)arg1;
-(id)setSnippet:(id)arg1;
-(id)setDescriptionText:(id)arg1;
-(id)setUrlString:(id)arg1;
-(id)setMedia:(id)arg1;

@end

