/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 11:44:43 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/197B1B60-1AA0-4A72-98F6-7C55CCB87C93/TestFlight.app/TestFlight
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ITCStateMachineDelegate;
@class NSString, NSDictionary;

@interface ITCStateMachine : NSObject {

	int _lock;
	BOOL _shouldLogStateTransitions;
	NSString* _currentState;
	NSDictionary* _validTransitions;
	id<ITCStateMachineDelegate> _delegate;

}

@property (copy) NSString * currentState;                                 //@synthesize currentState=_currentState - In the implementation block
@property (retain) NSDictionary * validTransitions;                       //@synthesize validTransitions=_validTransitions - In the implementation block
@property (__weak) id<ITCStateMachineDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL shouldLogStateTransitions;              //@synthesize shouldLogStateTransitions=_shouldLogStateTransitions - In the implementation block
-(void)setDelegate:(id<ITCStateMachineDelegate>)arg1 ;
-(id)init;
-(id<ITCStateMachineDelegate>)delegate;
-(NSString *)currentState;
-(id)target;
-(void)setCurrentState:(NSString *)arg1 ;
-(BOOL)_setCurrentState:(id)arg1 ;
-(BOOL)shouldLogStateTransitions;
-(id)_validateTransitionFromState:(id)arg1 toState:(id)arg2 ;
-(void)_performTransitionFromState:(id)arg1 toState:(id)arg2 ;
-(NSDictionary *)validTransitions;
-(BOOL)applyState:(id)arg1 ;
-(void)setShouldLogStateTransitions:(BOOL)arg1 ;
-(id)_missingTransitionFromState:(id)arg1 toState:(id)arg2 ;
-(id)missingTransitionFromState:(id)arg1 toState:(id)arg2 ;
-(void)setValidTransitions:(NSDictionary *)arg1 ;
@end

