/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 8:46:55 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/11A60D99-01E0-433C-ADB9-36971BECDA0C/Slack.app/Slack
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Slack/SLKFileDocumentViewController.h>

@class UITextView, UIView;

@interface SLKFileDocumentTextViewController : SLKFileDocumentViewController {

	UITextView* _textView;
	UIView* _statusBarBackground;

}

@property (nonatomic,retain) UITextView * textView;                     //@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) UIView * statusBarBackground;              //@synthesize statusBarBackground=_statusBarBackground - In the implementation block
-(void)animateContentBodyIn;
-(void)animateContentBodyOut;
-(void)setupSnippet;
-(UIView *)statusBarBackground;
-(void)updateInsets;
-(void)setStatusBarBackground:(UIView *)arg1 ;
-(void)setTextView:(UITextView *)arg1 ;
-(UITextView *)textView;
-(void)setupData;
@end

