/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 8:46:55 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/11A60D99-01E0-433C-ADB9-36971BECDA0C/Slack.app/Slack
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Slack/Slack-Structs.h>
#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont, UILabel;

@interface SLKTitleView : UIView {

	BOOL _showCaret;
	BOOL _showMuted;
	BOOL _showPresence;
	BOOL _showActive;
	BOOL _showSharedIcon;
	BOOL _showPrivateIcon;
	NSString* _text;
	UIColor* _textColor;
	UIFont* _font;
	long long _statusIcon;
	UILabel* _label;

}

@property (nonatomic,retain) UILabel * label;                      //@synthesize label=_label - In the implementation block
@property (nonatomic,retain) NSString * text;                      //@synthesize text=_text - In the implementation block
@property (nonatomic,retain) UIColor * textColor;                  //@synthesize textColor=_textColor - In the implementation block
@property (nonatomic,retain) UIFont * font;                        //@synthesize font=_font - In the implementation block
@property (assign,nonatomic) long long statusIcon;                 //@synthesize statusIcon=_statusIcon - In the implementation block
@property (assign,nonatomic) BOOL showCaret;                       //@synthesize showCaret=_showCaret - In the implementation block
@property (assign,nonatomic) BOOL showMuted;                       //@synthesize showMuted=_showMuted - In the implementation block
@property (assign,nonatomic) BOOL showPresence;                    //@synthesize showPresence=_showPresence - In the implementation block
@property (assign,nonatomic) BOOL showActive;                      //@synthesize showActive=_showActive - In the implementation block
@property (assign,nonatomic) BOOL showSharedIcon;                  //@synthesize showSharedIcon=_showSharedIcon - In the implementation block
@property (assign,nonatomic) BOOL showPrivateIcon;                 //@synthesize showPrivateIcon=_showPrivateIcon - In the implementation block
@property (assign,nonatomic) long long lineBreakMode; 
-(long long)statusIcon;
-(BOOL)showPresence;
-(BOOL)showSharedIcon;
-(BOOL)showCaret;
-(BOOL)showMuted;
-(BOOL)showPrivateIcon;
-(BOOL)showActive;
-(void)setNeedsUpdateString;
-(void)setStatusIcon:(long long)arg1 ;
-(void)setShowCaret:(BOOL)arg1 ;
-(void)setShowMuted:(BOOL)arg1 ;
-(void)setShowPresence:(BOOL)arg1 ;
-(void)setShowActive:(BOOL)arg1 ;
-(void)setShowSharedIcon:(BOOL)arg1 ;
-(void)setShowPrivateIcon:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setTextColor:(UIColor *)arg1 ;
-(void)setFont:(UIFont *)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(void)setLineBreakMode:(long long)arg1 ;
-(UIFont *)font;
-(UIColor *)textColor;
-(UILabel *)label;
-(void)setLabel:(UILabel *)arg1 ;
-(long long)lineBreakMode;
-(void)commonInit;
@end

