/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 8:53:13 PM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/B79A6C91-6A31-4B98-98DF-DAB1E6185487/eBay.app/eBay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <eBay/eBay-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableDictionary, FrameView;

@interface EBUItemCellAccessoryView : UIView {

	double _maxWidth;
	NSMutableDictionary* _viewDict;
	FrameView* _dividerLine;

}

@property (assign,nonatomic) double maxWidth;                             //@synthesize maxWidth=_maxWidth - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * viewDict;              //@synthesize viewDict=_viewDict - In the implementation block
@property (nonatomic,retain) FrameView * dividerLine;                     //@synthesize dividerLine=_dividerLine - In the implementation block
-(double)optimalHeight;
-(double)actualHeight;
-(double)labelPadding;
-(double)heightForLabel:(id)arg1 ;
-(double)heightForLabel:(id)arg1 width:(double)arg2 ;
-(double)widthForLabel:(id)arg1 ;
-(NSMutableDictionary *)viewDict;
-(void)setViewDict:(NSMutableDictionary *)arg1 ;
-(double)dividerLineWidth;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(double)topMargin;
-(double)rightMargin;
-(double)maxWidth;
-(void)setMaxWidth:(double)arg1 ;
-(double)imageWidth;
-(double)imageHeight;
-(double)leftMargin;
-(FrameView *)dividerLine;
-(void)setDividerLine:(FrameView *)arg1 ;
@end

