/*
* This header is generated by classdump-dyld 1.0
* on Friday, December 23, 2016 at 8:53:14 PM Greenwich Mean Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /var/containers/Bundle/Application/B79A6C91-6A31-4B98-98DF-DAB1E6185487/eBay.app/eBay
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, UIImageView, NSLayoutConstraint;

@interface EBUSimpleCheckoutHeader : UIView {

	UILabel* _titleLabel;
	UIImageView* _imageView;
	NSLayoutConstraint* _placeholderConstraint;

}

@property (assign,nonatomic,__weak) UILabel * titleLabel;                                    //@synthesize titleLabel=_titleLabel - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * imageView;                                 //@synthesize imageView=_imageView - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * placeholderConstraint;              //@synthesize placeholderConstraint=_placeholderConstraint - In the implementation block
+(id)viewWithText:(id)arg1 labelStyle:(id)arg2 ;
+(id)viewWithImage:(id)arg1 ;
-(void)setupHeaderWithText:(id)arg1 labelStyle:(id)arg2 ;
-(void)setupHeaderWithImage:(id)arg1 ;
-(void)setLabelTextAlignment:(long long)arg1 ;
-(NSLayoutConstraint *)placeholderConstraint;
-(void)setPlaceholderConstraint:(NSLayoutConstraint *)arg1 ;
-(UILabel *)titleLabel;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(double)heightForWidth:(double)arg1 ;
@end

