/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:53:38 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D5AA3D7F-F68B-43D8-8CC1-85DAFE886350/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface TGHolderSet : NSObject {

	NSMutableArray* _holders;
	/*^block*/id _emptyStateChanged;

}

@property (nonatomic,copy) id emptyStateChanged;              //@synthesize emptyStateChanged=_emptyStateChanged - In the implementation block
-(void)setEmptyStateChanged:(id)arg1 ;
-(void)addHolder:(id)arg1 ;
-(void)removeHolder:(id)arg1 ;
-(id)emptyStateChanged;
-(id)init;
-(BOOL)isEmpty;
@end

