/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:53:37 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D5AA3D7F-F68B-43D8-8CC1-85DAFE886350/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/Telegram-Structs.h>
#import <Telegram/TGOpenInAppItem.h>

@interface TGOpenInLocationItem : TGOpenInAppItem
+(id)appItemsClasses;
+(BOOL)canOpen:(id)arg1 directions:(BOOL)arg2 ;
+(id)appItemsForLocationAttachment:(id)arg1 directions:(BOOL)arg2 ;
+(CGPoint)coordinateForLocation:(id)arg1 ;
+(void)openURL:(id)arg1 ;
@end

