/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:53:39 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D5AA3D7F-F68B-43D8-8CC1-85DAFE886350/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/TGMenuSheetItemView.h>

@class UIActivityIndicatorView, UILabel;

@interface TGPreviewAboutItemView : TGMenuSheetItemView {

	UIActivityIndicatorView* _indicatorView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	BOOL _loading;

}
-(double)preferredHeightForWidth:(double)arg1 screenHeight:(double)arg2 ;
-(id)initWithWebPageAttachment:(id)arg1 ;
-(id)initWithLocationAttachment:(id)arg1 ;
-(id)initWithDocumentAttachment:(id)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 subtitle:(id)arg2 ;
@end

