/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:53:38 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D5AA3D7F-F68B-43D8-8CC1-85DAFE886350/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString;

@interface TGVenueAttachment : NSObject <NSCoding> {

	NSString* _title;
	NSString* _address;
	NSString* _provider;
	NSString* _venueId;

}

@property (nonatomic,readonly) NSString * title;                 //@synthesize title=_title - In the implementation block
@property (nonatomic,readonly) NSString * address;               //@synthesize address=_address - In the implementation block
@property (nonatomic,readonly) NSString * provider;              //@synthesize provider=_provider - In the implementation block
@property (nonatomic,readonly) NSString * venueId;               //@synthesize venueId=_venueId - In the implementation block
-(NSString *)venueId;
-(id)initWithTitle:(id)arg1 address:(id)arg2 provider:(id)arg3 venueId:(id)arg4 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)title;
-(NSString *)provider;
-(NSString *)address;
@end

