/*
* This header is generated by classdump-dyld 1.0
* on Friday, August 26, 2016 at 5:53:38 PM British Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D5AA3D7F-F68B-43D8-8CC1-85DAFE886350/Telegram.app/Telegram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Telegram/TLBotInlineResult.h>

@class NSString, TLBotInlineMessage;

@interface TLBotInlineResult$botInlineResult : TLBotInlineResult {

	int _flags;
	int _w;
	int _h;
	int _duration;
	NSString* _n_id;
	NSString* _type;
	NSString* _title;
	NSString* _n_description;
	NSString* _url;
	NSString* _thumb_url;
	NSString* _content_url;
	NSString* _content_type;
	TLBotInlineMessage* _send_message;

}

@property (assign,nonatomic) int flags;                                      //@synthesize flags=_flags - In the implementation block
@property (nonatomic,retain) NSString * n_id;                                //@synthesize n_id=_n_id - In the implementation block
@property (nonatomic,retain) NSString * type;                                //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSString * title;                               //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * n_description;                       //@synthesize n_description=_n_description - In the implementation block
@property (nonatomic,retain) NSString * url;                                 //@synthesize url=_url - In the implementation block
@property (nonatomic,retain) NSString * thumb_url;                           //@synthesize thumb_url=_thumb_url - In the implementation block
@property (nonatomic,retain) NSString * content_url;                         //@synthesize content_url=_content_url - In the implementation block
@property (nonatomic,retain) NSString * content_type;                        //@synthesize content_type=_content_type - In the implementation block
@property (assign,w,nonatomic) int w;                                        //@synthesize w=_w - In the implementation block
@property (assign,h,nonatomic) int h;                                        //@synthesize h=_h - In the implementation block
@property (assign,nonatomic) int duration;                                   //@synthesize duration=_duration - In the implementation block
@property (nonatomic,retain) TLBotInlineMessage * send_message;              //@synthesize send_message=_send_message - In the implementation block
-(id)TLdeserialize:(id)arg1 signature:(int)arg2 environment:(id)arg3 context:(id)arg4 error:(id*)arg5 ;
-(void)TLserialize:(id)arg1 ;
-(void)setN_id:(NSString *)arg1 ;
-(NSString *)n_id;
-(NSString *)n_description;
-(NSString *)content_url;
-(NSString *)thumb_url;
-(void)setN_description:(NSString *)arg1 ;
-(void)setThumb_url:(NSString *)arg1 ;
-(void)setContent_url:(NSString *)arg1 ;
-(void)setContent_type:(NSString *)arg1 ;
-(NSString *)content_type;
-(void)setSend_message:(TLBotInlineMessage *)arg1 ;
-(TLBotInlineMessage *)send_message;
-(void)setTitle:(NSString *)arg1 ;
-(int)duration;
-(NSString *)url;
-(void)setDuration:(int)arg1 ;
-(void)setType:(NSString *)arg1 ;
-(NSString *)type;
-(NSString *)title;
-(void)setUrl:(NSString *)arg1 ;
-(int)w;
-(int)h;
-(void)setW:(int)arg1 ;
-(void)setH:(int)arg1 ;
-(BOOL)isMedia;
-(void)setFlags:(int)arg1 ;
-(int)flags;
@end

