/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 12:10:16 PM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/EECA69E8-8DA6-473D-BDCA-9D4EFB22C6CE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Instagram/IGImpressionTracker.h>

@class NSString;

@interface IGFeedItemTracker : IGImpressionTracker {

	BOOL _trackWithNoLatency;
	/*^block*/id _trackingTokenBlock;
	NSString* _eventPrefix;

}

@property (nonatomic,copy) id trackingTokenBlock;                  //@synthesize trackingTokenBlock=_trackingTokenBlock - In the implementation block
@property (assign,nonatomic) BOOL trackWithNoLatency;              //@synthesize trackWithNoLatency=_trackWithNoLatency - In the implementation block
@property (nonatomic,copy) NSString * eventPrefix;                 //@synthesize eventPrefix=_eventPrefix - In the implementation block
-(void)setTrackWithNoLatency:(BOOL)arg1 ;
-(void)setEventPrefix:(NSString *)arg1 ;
-(id)eventWithSuffix:(id)arg1 ;
-(BOOL)trackWithNoLatency;
-(id)trackingTokenBlock;
-(NSString *)eventPrefix;
-(id)trackEvent:(id)arg1 forFeedItem:(id)arg2 ;
-(void)logRaindropEventForFeedItem:(id)arg1 withType:(int)arg2 analyticsMetadata:(id)arg3 ;
-(id)trackTimespentForFeedItem:(id)arg1 withTimespent:(double)arg2 ;
-(void)logRaindropTimespentForFeedItem:(id)arg1 withTimespent:(double)arg2 analyticsMetadata:(id)arg3 ;
-(void)setTrackingTokenBlock:(id)arg1 ;
@end

