/*
* This header is generated by classdump-dyld 0.7
* on Friday, August 21, 2015 at 12:10:15 PM British Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /private/var/mobile/Containers/Bundle/Application/EECA69E8-8DA6-473D-BDCA-9D4EFB22C6CE/Instagram.app/Instagram
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UIViewControllerAnimatedTransitioning.h>
#import <UIKit/UIViewControllerInteractiveTransitioning.h>

@protocol IGNavigationAnimatorDelegate, UIViewControllerContextTransitioning;
@class IGViewController, UIView, IGNavigationBar, NSString;

@interface IGNavigationAnimator : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning> {

	BOOL _userInteractionDisabled;
	BOOL _transitioning;
	id<IGNavigationAnimatorDelegate> _delegate;
	IGViewController* _toViewController;
	IGViewController* _fromViewController;
	UIView* _containerView;
	id<UIViewControllerContextTransitioning> _transitionContext;

}

@property (assign,nonatomic,__weak) id<IGNavigationAnimatorDelegate> delegate;                               //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) IGViewController * toViewController;                                     //@synthesize toViewController=_toViewController - In the implementation block
@property (assign,nonatomic,__weak) IGViewController * fromViewController;                                   //@synthesize fromViewController=_fromViewController - In the implementation block
@property (nonatomic,__weak,readonly) IGNavigationBar * navigationBar; 
@property (nonatomic,__weak,readonly) UIView * tabBar; 
@property (assign,nonatomic,__weak) UIView * containerView;                                                  //@synthesize containerView=_containerView - In the implementation block
@property (assign,nonatomic,__weak) id<UIViewControllerContextTransitioning> transitionContext;              //@synthesize transitionContext=_transitionContext - In the implementation block
@property (assign,getter=isUserInteractionDisabled,nonatomic) BOOL userInteractionDisabled;                  //@synthesize userInteractionDisabled=_userInteractionDisabled - In the implementation block
@property (nonatomic,readonly) BOOL bottomBarWillBeHidden; 
@property (nonatomic,readonly) BOOL bottomBarIsHidden; 
@property (nonatomic,readonly) BOOL navigationBarIsHidden; 
@property (nonatomic,readonly) BOOL navigationBarWillBeHidden; 
@property (assign,getter=isTransitioning,nonatomic) BOOL transitioning;                                      //@synthesize transitioning=_transitioning - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)dynamicsProperties;
-(void)setUserInteractionDisabled:(BOOL)arg1 ;
-(void)setTransitioning:(BOOL)arg1 ;
-(void)setStatusBarDimmed:(BOOL)arg1 animated:(BOOL)arg2 ;
-(BOOL)bottomBarWillBeHidden;
-(BOOL)bottomBarIsHidden;
-(BOOL)navigationBarIsHidden;
-(BOOL)navigationBarWillBeHidden;
-(BOOL)isUserInteractionDisabled;
-(void)setFromViewController:(IGViewController *)arg1 ;
-(void)setToViewController:(IGViewController *)arg1 ;
-(void)setDelegate:(id<IGNavigationAnimatorDelegate>)arg1 ;
-(id<IGNavigationAnimatorDelegate>)delegate;
-(UIView *)containerView;
-(void)setTransitionContext:(id<UIViewControllerContextTransitioning>)arg1 ;
-(double)transitionDuration:(id)arg1 ;
-(void)animateTransition:(id)arg1 ;
-(void)animationEnded:(BOOL)arg1 ;
-(id<UIViewControllerContextTransitioning>)transitionContext;
-(void)startInteractiveTransition:(id)arg1 ;
-(IGNavigationBar *)navigationBar;
-(void)setContainerView:(UIView *)arg1 ;
-(BOOL)isTransitioning;
-(IGViewController *)fromViewController;
-(IGViewController *)toViewController;
-(UIView *)tabBar;
@end

